<div class="video-detail">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-12">
            <iframe width="100%" height="450" src="https://www.youtube.com/embed/p_3O-huWHd8" frameborder="0" allowfullscreen></iframe>
          </div>
          <div class="col-md-12">
            <div class="watch-header">
            <div class="watch7-headline">
              <h1 class="watch-title-container">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</h1>
            </div>
            <div class="watch-user-header">
              <div class="view">
                  1,621,070 views
                </div>
            </div>
            <div class="watch-action-buttons">
              <div class="watch-secondary-actions">
                <ul class="share">
                  <li><a href="#"><span>Chia sẻ lên facebook</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên google+</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên twiter</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên introgram</span></a></li>
                </ul>
              </div>
              <div class="watch-sentiment-actions">

                <span class="like"><var class="icon icon-thumbs-up-hand-symbol"></var> 123,545</span>
                <span class="unlike"><var class="icon icon-thumbs-up-hand-symbol"></var> 158</span>
              </div>
            </div>
          </div>
            <div class="action-panel-details">
              <h2>Published on Jul 22, 2014</h2>
              <h3>Tac gia: <strong>Pham Long</strong></h3>
              <h4>Danh muc: <a href="#">Am thuc</a></h4>
              <div class="description">
                <p>nhớ. nhớ lắm mối tình đầu. dại khờ lắm. chỉ cái nắm tay cũng ngại chín mặt. để rồi a nói chia tay chính thức sống bên người con gái khác. cánh thiệp hồng gửi đến e sau chia tay 1tháng. e buồn. e đạp xe đi lang thang, đi đến những nơi hai đứa từng đến. ôi mỗi tình đầu. mới đó mà 13 năm rồi. kể từ đó hai ta ko gặp lại nhau nữa﻿</p>
                <p>nhớ. nhớ lắm mối tình đầu. dại khờ lắm. chỉ cái nắm tay cũng ngại chín mặt. để rồi a nói chia tay chính thức sống bên người con gái khác. cánh thiệp hồng gửi đến e sau chia tay 1tháng. e buồn. e đạp xe đi lang thang, đi đến những nơi hai đứa từng đến. ôi mỗi tình đầu. mới đó mà 13 năm rồi. kể từ đó hai ta ko gặp lại nhau nữa﻿</p>
                <p>nhớ. nhớ lắm mối tình đầu. dại khờ lắm. chỉ cái nắm tay cũng ngại chín mặt. để rồi a nói chia tay chính thức sống bên người con gái khác. cánh thiệp hồng gửi đến e sau chia tay 1tháng. e buồn. e đạp xe đi lang thang, đi đến những nơi hai đứa từng đến. ôi mỗi tình đầu. mới đó mà 13 năm rồi. kể từ đó hai ta ko gặp lại nhau nữa﻿</p>
                <p>nhớ. nhớ lắm mối tình đầu. dại khờ lắm. chỉ cái nắm tay cũng ngại chín mặt. để rồi a nói chia tay chính thức sống bên người con gái khác. cánh thiệp hồng gửi đến e sau chia tay 1tháng. e buồn. e đạp xe đi lang thang, đi đến những nơi hai đứa từng đến. ôi mỗi tình đầu. mới đó mà 13 năm rồi. kể từ đó hai ta ko gặp lại nhau nữa﻿</p>
                <p>nhớ. nhớ lắm mối tình đầu. dại khờ lắm. chỉ cái nắm tay cũng ngại chín mặt. để rồi a nói chia tay chính thức sống bên người con gái khác. cánh thiệp hồng gửi đến e sau chia tay 1tháng. e buồn. e đạp xe đi lang thang, đi đến những nơi hai đứa từng đến. ôi mỗi tình đầu. mới đó mà 13 năm rồi. kể từ đó hai ta ko gặp lại nhau nữa﻿</p>
              </div>
              <div class="readmove">
                <a href="javascript:void(0);">Xem thêm</a>
              </div>
              <script type="text/javascript">
                jQuery(document).ready(function($){
                  $(".readmove a").on('click', function(){
                    $(".description").toggleClass('on');
                  });
                });
              </script>
            </div>
            
            <div class="watch-discussion">
              <div id="fb-root"></div>
              <script type="text/javascript">
                (function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9&appId=1335573093153899";
                fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
              </script>
              <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-width="100%" data-numposts="5"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="video-related">
          <ul class="row">
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
          </ul>
          <div class="readmove">
            <a href="#">Xem thêm</a>
          </div>
               
        </div>
      </div>
    </div>
  </div>
</div>