<div class="video-detail">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-12">
            <iframe width="100%" height="450" src="https://www.youtube.com/embed/p_3O-huWHd8" frameborder="0" allowfullscreen></iframe>
          </div>
          <div class="col-md-12">
            <div class="watch-header">
            <div class="watch7-headline">
              <h1 class="watch-title-container">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</h1>
            </div>
            <div class="watch-user-header">
              <div class="view">
                  1,621,070 views
                </div>
            </div>
            <div class="watch-action-buttons">
              <div class="watch-secondary-actions">
                <ul class="share">
                  <li><a href="#"><span>Chia sẻ lên facebook</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên google+</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên twiter</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên introgram</span></a></li>
                </ul>
              </div>
              <div class="watch-sentiment-actions">

                <span class="like"><var class="icon icon-thumbs-up-hand-symbol"></var> 123,545</span>
                <span class="unlike"><var class="icon icon-thumbs-up-hand-symbol"></var> 158</span>
              </div>
            </div>
          </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="video-related">
          <ul class="row">
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
            
            <li class="col-md-12">
              <div class="video-item">
                <div class="row">
                  <div class="col-md-5">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                    </a>
                  </div>
                  <div class="col-md-7">
                    <h3><a href="#">
      PHIM HÀNH ĐỘNG ll Hội Nữ Sát Thủ Tập 1 Thuyết Minh
                      </a></h3>
                    <p class="author">Hồ Trung Kiên</p>
                    <p class="view-count"><span>294,535</span> views</p>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>