<div class="home-news video-list">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3><a href="#"><span>Ẩm thực</span></a></h3>
      </div>
    </div>
    <ul class="row">
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="home-news video-list">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3><a href="#"><span>Du lịch</span></a></h3>
      </div>
    </div>
    <ul class="row">
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-video">
          <div class="img">
            <a href="#" class="hover-posts">
              <span><i class="icon icon-play-button"></i>Xem Video</span>
            </a>
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="date">
              <span>September 13th, 2015</span>
            </div>
          </div>
          <div class="content">
            <h2 class="title"><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a></h2>
            <ul class="block-like">
              <li class="view">
                <var class="icon icon-eye-1"></var>
                <span class="total-view">1,123,444</span> <span>View</span>
              </li>
              <li class="like-post">
                <var class="icon icon-heart"></var> <span>1,521</span>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>