<?php if ($listVideo): ?>
  <div id="video" class="video">
    <h2>Video</h2>
    <ul class="row list-data-video">
      <?php foreach ($listVideo as $video): ?>
        <li class="col-md-4">
          <div class="item-video">
            <div class="video-thumbnail">
              <div class="author-view"><?php echo number_format($video['view'], 0, ',', ','); ?> lượt xem</div>
              <a href="#">
                <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
            </div>
            <div class="video-content">
              <div class="title">
                <a href="#"><?php echo $video['name']; ?></a>
              </div>
              <div class="view">
                <ul>
                  <li><span><?php echo date('d/m/Y H:i:s', $video['created']); ?></span></li>
                  <li><a href="#"><?php echo $video['fullname']; ?></a></li>
                </ul>
              </div>
            </div>
          </div>
        </li>
      <?php endforeach; ?>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="views-all-video">
          <a ng-page="<?php echo $currentPage; ?>" data-id="<?php echo $postId; ?>">Xem thêm</a>
        </div>
      </div>
    </div>
  </div>
<?php endif; ?>