<div class="search">
  <div class="page-search">
    <?php echo $this->searchTravel(); ?>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="page-search-title">
        <div class="item-title">
          <h1><span class="icon icon-menu"></span> Thành phố Hồ Chí Minh</h1>
        </div>
      </div>
      <div class="province-container">
        <div class="province">
          <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
          <div class="province-help">
            <ul>
              <li class="tours"><span></span> 1.500 điểm du lịch</li>
              <li class="hotel"><span></span> 1.500 Khách sạn</li>
              <li class="taste"><span></span> 1.500 Điểm ăn uống</li>
              <li class="park"><span></span> 1.500 Công viên giải trí</li>
            </ul>
          </div>
        </div>
        <div class="current-position">
          <div class="row">
            <div class="col-md-9">
              <input class="form-control" name="current-map" id="current-map" placeholder="Nhập vị trí của bạn">
            </div>
            <div class="col-md-3">
              <a class="btn-filter-advance">Nâng cao</a>
            </div>
            <div class="col-md-12">
              <div class="filter-advance">
                <ul>
                  <li><a href="#">Giá: Thấp đến Cao</a></li>
                  <li><a href="#">Giá: Cao đến Thấp</a></li>
                  <li><a href="#">Giảm giá nhiều nhất</a></li>
                  <li><a href="#">Bán chạy nhất</a></li>
                  <li><a href="#">Mới nhất</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="list-province-item">
          <ul class="list-travel">
            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-5">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                    <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
                  </div>
                  <div class="col-md-7">
                    <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                    <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                    <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                    <div class="fs-game">
                      <ul class="list-game">
                        <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                        <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                        <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                      </ul>
                      <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                    </div>
                  </div>
                </div>
              </div>
            </li>

            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-5">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                    <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
                  </div>
                  <div class="col-md-7">
                    <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                    <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                    <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                    <div class="fs-game">
                      <ul class="list-game">
                        <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                        <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                        <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                      </ul>
                      <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                    </div>
                  </div>
                </div>
              </div>
            </li>

            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-5">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                    <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
                  </div>
                  <div class="col-md-7">
                    <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                    <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                    <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                    <div class="fs-game">
                      <ul class="list-game">
                        <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                        <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                        <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                      </ul>
                      <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
        
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    <!--<div class="loading"></div>-->
  </div>
  <div class="map-content">
    <div style="width: 100%; height: 100%;" id="map"></div>
    <div class="shoppingcart">
      <?php $this->cart() ?>
    </div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
      
      
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>-->
<script>
  jQuery(document).ready(function($){
    $(".list-province-item .list-travel li").on('click','a',function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/travel-view';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".popup-page").addClass('on');
            $(".popup-page").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".popup-container").empty().append(data.html);
            
            // call royalSlider
            var slider = $('.royalSlider').royalSlider({
            fullscreen: {
              enabled: true,
              nativeFS: true
            },
            controlNavigation: 'thumbnails',
            autoScaleSlider: true, 
            autoScaleSliderWidth: 725,
            autoScaleSliderHeight: 478,
            loop: false,
            imageScaleMode: 'none',
            navigateByClick: true,
            numImagesToPreload:2,
            arrowsNav:true,
            arrowsNavAutoHide: true,
            arrowsNavHideOnTouch: true,
            keyboardNavEnabled: true,
            fadeinLoadedSlide: true,
            globalCaption: false,
            globalCaptionInside: false,
            imageScalePadding: 0,
            slidesSpacing: 0,
            thumbs: {
              appendSpan: false,
              firstMargin: false,
              paddingBottom: 4
            }
            }).data('royalSlider');

            $('.rsFullscreenBtn').click(function(e){
              slider.enterFullscreen();
              e.preventDefault();
            });

            slider.ev.on("rsEnterFullscreen", function() {
              // enter fullscreen mode 
              $(".popup-page").css('position', 'relative');
            });
            slider.ev.on('rsExitFullscreen', function(event) {
              // exit fullscreen mode
              $(".popup-page").removeAttr('style');
            });
          }
        });
    });
    // close popup
    $(".popup-page").on('click','.popup-close' ,function(){
      $(".popup-page").removeClass('on');
      $(".popup-page .popup-container").empty();
    });
    
    // view map
    $(".list-province-item ul > li").on('click','.strict-views', function(){
      var current = $("#current-map").val();
      var id = 'abc';
      var url = 'http://localhost/tours/public/view-map';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".views-popup").addClass('view');
            $(".views-popup").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".views-popup .views-container").empty().append(data.html);
            var pyrmont = {lat: -33.867, lng: 151.195};
            // view google map
            map = new google.maps.Map(document.getElementById('view-map'), {
              center: pyrmont,
              zoom: 15
            });

            infowindow = new google.maps.InfoWindow();
            var service = new google.maps.places.PlacesService(map);
            service.nearbySearch({
              location: pyrmont,
              radius: 500,
              type: ['store']
            }, callback);
            // view map popup
            $(".views-popup .views-container").addClass('open');
          }
        });
    });
    
    
    // show detail gallery
    $(".game-entertainment tr td").on('click','.history', function(){
      alert('a');
      var id = 'abc';
      var url = 'http://localhost/tours/public/view-map';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".views-popup").addClass('view');
            $(".views-popup").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".views-popup .views-container").empty().append(data.html);
            var pyrmont = {lat: -33.867, lng: 151.195};
            // view google map
            map = new google.maps.Map(document.getElementById('view-map'), {
              center: pyrmont,
              zoom: 15
            });

            infowindow = new google.maps.InfoWindow();
            var service = new google.maps.places.PlacesService(map);
            service.nearbySearch({
              location: pyrmont,
              radius: 500,
              type: ['store']
            }, callback);
            // view map popup
            $(".views-popup .views-container").addClass('open');
          }
        });
    });
    
    // view map popup close
    $(".views-popup").on('click','.views-close' ,function(){
      $(".views-popup .views-container").removeClass('open');
      setTimeout(function () {
       $(".views-popup").removeClass('view');
       $(".views-popup .views-container").empty();
      }, 350);
    });
  });
</script>




<div class="views-popup">
  <div class="views-container">
    
  </div>
</div>

<div class="popup-page">
  <div class="popup-container">
    
  </div>
</div>

<div class="video-play">
  <div class="warpper-video">
    <div class="container">
      <div class="content-video">
        <div class="row">
          <div class="col-md-8">
            <div class="player-container">
              <div class="player-position">
                 <div id="player"></div>
              </div>
            </div>
            <div class="watch-header">
              <div class="watch7-headline">
                <h1 class="watch-title-container">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</h1>
              </div>
              <div class="watch-user-header">
                <div class="view">
                    1,621,070 views
                  </div>
              </div>
              <div class="watch-action-buttons">
                <div class="watch-secondary-actions">
                  
                </div>
                <div class="watch-sentiment-actions">
                  
                  <span class="like"><var class="icon icon-thumbs-up-hand-symbol"></var> 123,545</span>
                  <span class="unlike"><var class="icon icon-thumbs-up-hand-symbol"></var> 158</span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <a href="#"><img src="<?php echo $this->basePath('/assets/banner-video.jpg'); ?>"></a>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="list-video">
              <ul class="row">
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
                <li class="col-md-3">
                  <div class="video-item">
                    <div class="video-thumbnail">
                      <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                    </div>
                    <div class="content">
                      <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                      <p>
                        <a class="author" href="#">Bike Legend</a>
                      </p>
                      <p class="view">1,182,384 views</p>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>

<script type="text/javascript">

// initialize jwplayer
var playerInstance = jwplayer('player');

// player dom elements
var playerContainerEl = document.querySelector('.player-container');

// returns video player position from top of document
function getElementOffsetTop(el) {
  var boundingClientRect = el.getBoundingClientRect();
  var bodyEl = document.body;
  var docEl = document.documentElement;
  var scrollTop = window.pageYOffset || docEl.scrollTop || bodyEl.scrollTop;
  var clientTop = docEl.clientTop || bodyEl.clientTop || 0;
  return Math.round(boundingClientRect.top + scrollTop - clientTop);
}

// returns the current y scroll position
function getScrollTop() {
  var docEl = document.documentElement;
  return (window.pageYOffset || docEl.scrollTop) - (docEl.clientTop || 0);
}

// configure jwplayer instance
playerInstance.setup({
  autostart: false,
  file: '//content.jwplatform.com/manifests/vM7nH0Kl.m3u8',
  primary: 'html5',
  setFullscreen: true,
  width: '100%'
});

// when jwplayer instance is ready
playerInstance.on('ready', function() {
        var config = playerInstance.getConfig();
        var utils = playerInstance.utils;
        // get height of player element
        var playerHeight = config.containerHeight;

        // get player element position from top of document
        var playerOffsetTop = getElementOffsetTop(playerContainerEl);

        // set player container to match height of actual video element
        // this prevents container from disappearing and changing element positions
        // on page when player becomes minimized. this also leaves a nice visual
        // placeholder space for minimized player to return to when appropriate
        playerContainerEl.style.height = playerHeight + 'px';

        // below we handle window scroll event without killing performance
        // this is a minimal approach. please consider implementing something more extensive:
        // i.e. http://joji.me/en-us/blog/how-to-develop-high-performance-onscroll-event

        // determine player display when scroll event is called
        // if inline player is no longer visible in viewport, add class
        // .player-minimize to minimize and float. otherwise, remove the class to put
        // player back to inline inline position
        function onScrollViewHandler() {
            var minimize = getScrollTop() >= playerOffsetTop;

            utils.toggleClass(playerContainerEl, 'player-minimize', minimize);
            // update the player's size so the controls are adjusted
            playerInstance.resize();
        }

        // namespace for whether or not we are waiting for setTimeout() to finish
        var isScrollTimeout = false;

        // window onscroll event handler
        window.onscroll = function() {
            // skip if we're waiting on a scroll update timeout to finish
            if (isScrollTimeout) return;
            // flag that a new timeout will begin
            isScrollTimeout = true;
            // otherwise, call scroll event view handler
            onScrollViewHandler();
            // set new timeout
            setTimeout(function() {
                // reset timeout flag to false (no longer waiting)
                isScrollTimeout = false;
            }, 80);

        };

    });
</script>