<div class="search">
  <div class="page-search">
    <div class="search-item">
      <div class="search-list">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="list-search">
                <div class="row">
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">-- Quốc gia -- </option>
                      <option value="">Việt Nam</option>
                      <option value="">Thái Lan</option>
                      <option>Ấn Độ</option>
                      <option>Mỹ</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker">
                      <option value="">-- Tỉnh/Thành Phố -- </option>
                      <option>Bình Phước</option>
                      <option>Hà Nội</option>
                      <option>Hải Dương</option>
                      <option>Bình Định</option>
                      <option>Quản Trị</option>
                      <option>Quảng Nam</option>
                      <option>Huế</option>
                      <option>Đà Nẵng</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <div class="item-search-type">
                      <ul class="level">
                        <li class="item">
                          <a>
                            <span>-- Loại --</span>
                          </a>
                          <ul class="search-type">
                            <li class="tours">
                              <input type="checkbox" class="for-type" name="fs-travel" id="fs-travel">
                              <label class="fs-home" data-key="listings-1" for="fs-travel">
                                <span class="root-radius"></span>
                                <span>Điểm du lịch</span>
                              </label>
                            </li>
                            <li class="hotel">
                              <input type="checkbox" class="for-type" name="fs-hotel" id="fs-hotel">
                              <label class="fs-home" data-key="listings-2"  for="fs-hotel">
                                <span class="root-radius"></span>
                                <span>Khách sạn</span>
                              </label>
                            </li>
                            <li class="taste">
                              <input type="checkbox" class="for-type" name="fs-taste" id="fs-taste">
                              <label class="fs-home" data-key="listings-3" for="fs-taste">
                                <span class="root-radius"></span>
                                <span>Điểm ăn uống</span> 
                              </label>
                            </li>
                            <li class="park">
                              <input type="checkbox" class="for-type" name="fs-park" id="fs-park">
                              <label class="fs-home" data-key="listings-4" for="fs-park">
                                <span class="root-radius"></span>
                                <span>Công viên giải trí</span> 
                              </label>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                    <script>
                    jQuery(document).ready(function($){
                      var isClick = false;
                      $(".item-search-type ul>li").on('click', function(e){
                        $(".menu-search li").removeClass('selected');
                        if(isClick != true){
                          $(this).addClass('selected');
                          isClick = true;
                        }else{
                          $(this).removeClass('selected');
                          isClick = false;
                        }
                        e.stopPropagation();
                    });
                    $(document).click(function(e) {
                      isClick = false;
                      if (!$(e.target).is('.item, .item *')) {
                        $(".item-search-type li.item").removeClass('selected');
                      }
                    });
                  });
                    </script>
<!--                    <select class="form-control">
                      <option value="">-- Loại -- </option>
                    </select>-->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> Thành phố Hồ Chí Minh</h1>
    </div>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="province-container">
        <div class="province">
          <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
          <div class="province-help">
            <ul>
              <li class="tours"><span></span> 1.500 điểm du lịch</li>
              <li class="hotel"><span></span> 1.500 Khách sạn</li>
              <li class="taste"><span></span> 1.500 Điểm ăn uống</li>
              <li class="park"><span></span> 1.500 Công viên giải trí</li>
            </ul>
          </div>
        </div>
        <div class="current-position">
          <input class="form-control" name="current-map" id="current-map" placeholder="Nhập vị trí của bạn">
        </div>
        <div class="list-province-item">
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#tours" aria-controls="tours" role="tab" data-toggle="tab">Du lịch</a></li>
            <li role="presentation"><a href="#taste" aria-controls="taste" role="tab" data-toggle="tab">Điểm ăn uống</a></li>
            <li role="presentation"><a href="#hotel" aria-controls="hotel" role="tab" data-toggle="tab">Khách sạn</a></li>
            <li role="presentation"><a href="#park" aria-controls="park" role="tab" data-toggle="tab">Công viên</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="tours">
              <ul class="list-travel">
                <li>
                  <div class="item">
                    <div class="row">
                      <div class="col-md-5">
                        <div class="item-img">
                          <a href="javascript:void(0);" title="dam sen">
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            <div class="overlay_border"></div>
                          </a>
                        </div>
                        <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
                      </div>
                      <div class="col-md-7">
                        <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                        <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                        <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                        <div class="fs-game">
                          <ul class="list-game">
                            <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                            <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                            <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                          </ul>
                          <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                
                <li>
                  <div class="item">
                    <div class="row">
                      <div class="col-md-5">
                        <div class="item-img">
                          <a href="javascript:void(0);" title="dam sen">
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            <div class="overlay_border"></div>
                          </a>
                        </div>
                        <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
                      </div>
                      <div class="col-md-7">
                        <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                        <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                        <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                        <div class="fs-game">
                          <ul class="list-game">
                            <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                            <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                            <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                          </ul>
                          <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                
                <li>
                  <div class="item">
                    <div class="row">
                      <div class="col-md-5">
                        <div class="item-img">
                          <a href="javascript:void(0);" title="dam sen">
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            <div class="overlay_border"></div>
                          </a>
                        </div>
                        <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
                      </div>
                      <div class="col-md-7">
                        <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                        <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                        <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                        <div class="fs-game">
                          <ul class="list-game">
                            <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                            <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                            <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                          </ul>
                          <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
            <div role="tabpanel" class="tab-pane" id="taste">...</div>
            <div role="tabpanel" class="tab-pane" id="hotel">...</div>
            <div role="tabpanel" class="tab-pane" id="park">...</div>
          </div>
          
        </div>
        
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content">
    <div style="width: 100%; height: 100%;" id="map"></div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
      
      
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>-->
<script>
  jQuery(document).ready(function($){
    $(".list-province-item .list-travel li").on('click','a',function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/dia-diem-di-choi/view';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".popup-page").addClass('on');
            $(".popup-page").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".popup-container").empty().append(data.html);
            
            // call royalSlider
            var slider = $('.royalSlider').royalSlider({
            fullscreen: {
              enabled: true,
              nativeFS: true
            },
            controlNavigation: 'thumbnails',
            autoScaleSlider: true, 
            autoScaleSliderWidth: 1024,
            autoScaleSliderHeight: 614,
            loop: false,
            imageScaleMode: 'none',
            navigateByClick: true,
            numImagesToPreload:2,
            arrowsNav:true,
            arrowsNavAutoHide: true,
            arrowsNavHideOnTouch: true,
            keyboardNavEnabled: true,
            fadeinLoadedSlide: true,
            globalCaption: true,
            globalCaptionInside: false,
            imageScalePadding: 0,
            slidesSpacing: 0,
            thumbs: {
              appendSpan: true,
              firstMargin: true,
              paddingBottom: 4
            }
            }).data('royalSlider');

            $('.rsFullscreenBtn').click(function(e){
              slider.enterFullscreen();
              e.preventDefault();
            });

            slider.ev.on("rsEnterFullscreen", function() {
              // enter fullscreen mode 
              $(".popup-page").css('position', 'relative');
            });
            slider.ev.on('rsExitFullscreen', function(event) {
              // exit fullscreen mode
              $(".popup-page").removeAttr('style');
            });
          }
        });
    });
    // close popup
    $(".popup-page").on('click','.popup-close' ,function(){
      $(".popup-page").removeClass('on');
      $(".popup-page .popup-container").empty();
    });
    
    // view map
    $(".list-province-item .tab-content ul > li").on('click','.strict-views', function(){
      var current = $("#current-map").val();
      var id = 'abc';
      var url = 'http://localhost/tours/public/dia-diem-di-choi/view-map';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".views-popup").addClass('view');
            $(".views-popup").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".views-popup .views-container").empty().append(data.html);
            var pyrmont = {lat: -33.867, lng: 151.195};
            // view google map
            map = new google.maps.Map(document.getElementById('view-map'), {
              center: pyrmont,
              zoom: 15
            });

            infowindow = new google.maps.InfoWindow();
            var service = new google.maps.places.PlacesService(map);
            service.nearbySearch({
              location: pyrmont,
              radius: 500,
              type: ['store']
            }, callback);
            // view map popup
            $(".views-popup .views-container").addClass('open');
          }
        });
    });
    
    // view map popup close
    $(".views-popup").on('click','.views-close' ,function(){
      $(".views-popup .views-container").removeClass('open');
      setTimeout(function () {
       $(".views-popup").removeClass('view');
       $(".views-popup .views-container").empty();
      }, 350);
    });
  });
</script>




<div class="views-popup">
  <div class="views-container">
    
  </div>
</div>

<div class="popup-page">
  <div class="popup-container">
    
  </div>
</div>