<div class="popup-content">
  <div class="popup-header">
   <h2><span class="icon icon-location"></span> Đầm sen</h2>
   <div class="close-zoom pull-right">
     <div class="zoom"><a href="<?php echo $this->url('travel-detail', array('category' => 'category', 'slug' => 'detail-travel-expand', 'id' => '2324234')) ?>"><span class="icon icon-full-screen-selector"></span> Xem rộng hơn</a></div>
     <div class="popup-close"><span class="icon icon-cancel-music"></span></div>
   </div>
  </div>
  <div class="popup-body">
    <div class="row">
      <div class="col-md-8">
        <div class="col-md-12">
          <div class="slider">
            <div class="royalSlider rsDefault">
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="content-page-popup">
            <div class="row">
              <div class="col-md-12 about">
                <ul class="tab-travel">
                  <li data-id="about" class="active"><h2>Giới thiệu</h2></li>
                  <li data-id="table-price"><h2>Bảng giá</h2></li>
                  <li data-id="history"><h2>Lịch sử</h2></li>
                  <li data-id="video"><h2>Video</h2></li>
                  <li data-id="rating"><h2>Đánh giá</h2></li>
                </ul>
                <div class="content">
                  <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
           aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
           Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
           occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
           aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
           Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
           occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
           aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
           Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
           occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                  </div>
                  
                  <div id="table-price" class="list-catelog">
                    <h2 class="title">Bảng giá vé trọn gói (combo)</h2>
                    <table class="game-entertainment">
                      <thead>
                        <tr>
                          <th class="no">STT</th>
                          <th class="name">Tên dịch vụ</th>
                          <th class="price">Mô tả</th>
                          <th class="price">Giá vé người lớn</th>
                          <th class="price">Giá vé trẻ em</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>1</td>
                          <td>Vé trọn giói</td>
                          <td>Bao gồm vé vào cồng và tất cả trò chơi.</td>
                          <td>500.000đ/1 người</td>
                          <td>500.000đ/1 người</td>
                        </tr>
                        <tr>
                          <td>2</td>
                          <td>Combo 20 trò chơi</td>
                          <td>Tàu lượn siêu tốc, ...</td>
                          <td>150.000đ/1 người</td>
                          <td>500.000đ/1 người</td>
                        </tr>
                        <tr>
                          <td>3</td>
                          <td>Vé vào cổng</td>
                          <td></td>
                          <td>90.000đ/1 người</td>
                          <td>50.000đ/1 người</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <div class="list-catelog">
                    <h2 class="title">Bảng giá trò chơi</h2>
                    <table class="game-entertainment">
                      <thead>
                        <tr>
                          <th class="no">STT</th>
                          <th class="name">Tên dịch vụ</th>
                          <th class="price">Giá người lớn</th>
                          <th class="price">Giá trẻ em</th>
                          <th class="price"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td colspan="5" class="colspan">Trò chơi cảm giác mạnh</td>
                        </tr>
                        <tr>
                          <td>1</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>2</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>3</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>4</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>5</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>                       
                      </tbody>
                      <tbody>
                        <tr>
                          <td colspan="5" class="colspan">Trò chơi giải trí - khám phá</td>
                        </tr>
                        <tr>
                          <td>1</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>2</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>3</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>4</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>
                        <tr>
                          <td>5</td>
                          <td>Trượt tuyết</td>
                          <td>150.000đ/1 người</td>
                          <td>150.000đ/1 người</td>
                          <td><a class="history" href="javascript:void(0);">
                              <div class="view-gallery">Xem album ảnh</div>
                              <i class="icon icon-picture-o"></i></a></td>
                        </tr>                       
                      </tbody>
                    </table>
                  </div>



                  <div class="list-catelog">
                    <h2 class="title">Bảng giá phương tiện</h2>
                    <table>
                      <thead>
                        <tr>
                          <th class="no">STT</th>
                          <th class="name">Tên dịch vụ</th>
                          <th colspan="2">Giá vé</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td rowspan="3">2</td>
                          <td rowspan="3">Vé giữ xe</td>
                          <td>Xe số</td>
                          <td>5.000 đ</td>
                        </tr>
                        <tr>
                          <td>Xe tay ga</td>
                          <td>10.000 đ</td>
                        </tr>
                        <tr>
                          <td>Xe đạp</td>
                          <td>2.000 đ</td>
                        </tr>
                        <tr>
                          <td rowspan="2"> 3</td>
                          <td rowspan="2"> Xe lửa</td>
                          <td>Người lớn</td>
                          <td>90.000 đ</td>
                        </tr>
                        <tr>
                          <td>Trẻ em</td>
                          <td>70.000 đ</td>
                        </tr>
                        <tr>
                          <td rowspan="2">4</td>
                          <td rowspan="2">Vé giữ ô tô</td>
                          <td>Dưới 10 chỗ</td>
                          <td>20.000 đ</td>
                        </tr>
                        <tr>
                          <td>Trên 10 chỗ</td>
                          <td>40.000 đ</td>
                        </tr>
                        <tr>
                          <td rowspan="2">5</td>
                          <td rowspan="2">Taxi du lịch</td>
                          <td>Dưới 10 chỗ</td>
                          <td>200.000 đ</td>
                        </tr>
                        <tr>
                          <td>Trên 10 chỗ</td>
                          <td>400.000 đ</td>
                        </tr>
                        <tr>
                          <td>6</td>
                          <td>Vé võng</td>
                          <td></td>
                          <td>200.000 đ</td>
                        </tr>
                        <tr>
                          <td>7</td>
                          <td>Vé xe đẩy</td>
                          <td></td>
                          <td>200.000 đ</td>
                        </tr>
                        <tr>
                          <td>8</td>
                          <td>Vé giữ hành lý</td>
                          <td></td>
                          <td>200.000 đ</td>
                        </tr>
                        <tr>
                          <td>9</td>
                          <td>Vé xe lăn</td>
                          <td></td>
                          <td>200.000 đ</td>
                        </tr>
                        <tr>
                          <td>10</td>
                          <td>Vé nhà rông</td>
                          <td></td>
                          <td>200.000 đ</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                
                <div id="video" class="video">
                  <h2>Video</h2>
                  <ul class="row">
                    <li class="col-md-4">
                      <div class="item-video">
                        <div class="video-thumbnail">
                          <div class="author-view">521 lượt xem</div>
                          <a href="#">
                            <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                          </a>
                        </div>
                        <div class="video-content">
                          <div class="title">
                            <a href="#">Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất.</a>
                          </div>
                          <div class="view">
                            <ul>
                              <li><a href="#">Pham Long</a> - <span>12/12/2017 18:40</span></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li class="col-md-4">
                      <div class="item-video">
                        <div class="video-thumbnail">
                          <div class="author-view">521 lượt xem</div>
                          <a href="#">
                            <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                          </a>
                        </div>
                        <div class="video-content">
                          <div class="title">
                            <a href="#">Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất.</a>
                          </div>
                          <div class="view">
                            <ul>
                              <li><a href="#">Pham Long</a> - <span>12/12/2017 18:40</span></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li class="col-md-4">
                      <div class="item-video">
                        <div class="video-thumbnail">
                          <div class="author-view">521 lượt xem</div>
                          <a href="#">
                            <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                          </a>
                        </div>
                        <div class="video-content">
                          <div class="title">
                            <a href="#">Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất.</a>
                          </div>
                          <div class="view">
                            <ul>
                              <li><a href="#">Pham Long</a> - <span>12/12/2017 18:40</span></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li class="col-md-4">
                      <div class="item-video">
                        <div class="video-thumbnail">
                          <div class="author-view">521 lượt xem</div>
                          <a href="#">
                            <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                          </a>
                        </div>
                        <div class="video-content">
                          <div class="title">
                            <a href="#">Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất.</a>
                          </div>
                          <div class="view">
                            <ul>
                              <li><a href="#">Pham Long</a> - <span>12/12/2017 18:40</span></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li class="col-md-4">
                      <div class="item-video">
                        <div class="video-thumbnail">
                          <div class="author-view">521 lượt xem</div>
                          <a href="#">
                            <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                          </a>
                        </div>
                        <div class="video-content">
                          <div class="title">
                            <a href="#">Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất.</a>
                          </div>
                          <div class="view">
                            <ul>
                              <li><a href="#">Pham Long</a> - <span>12/12/2017 18:40</span></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li class="col-md-4">
                      <div class="item-video">
                        <div class="video-thumbnail">
                          <div class="author-view">521 lượt xem</div>
                          <a href="#">
                            <div class="icon-video"><var class="icon icon-video-camera"></var></div>
                            <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                          </a>
                        </div>
                        <div class="video-content">
                          <div class="title">
                            <a href="#">Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất.</a>
                          </div>
                          <div class="view">
                            <ul>
                              <li><a href="#">Pham Long</a> - <span>12/12/2017 18:40</span></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    
                  </ul>
                </div>
                
                <div id="rating" class="rating">
                  <h2>Khách hàng nhận xét</h2>
                  <ul>
                    <li class="summary-rating">
                      <p>Đánh Giá Trung Bình</p>
                      <p>3.5/5</p>
                      <p class="rating-post">
                        <span class="rating-box">
                          <i class="icon icon-star"></i>
                          <i class="icon icon-star"></i>
                          <i class="icon icon-star"></i>
                          <i class="icon icon-star"></i>
                          <i class="icon icon-star"></i>
                          <span>
                            <i class="icon icon-star"></i>
                            <i class="icon icon-star"></i>
                            <i class="icon icon-star"></i>
                            <i class="icon icon-star"></i>
                            <i class="icon icon-star"></i>
                          </span>
                        </span>
                      </p>
                      <p>(10 nhận xét)</p>
                    </li>
                    <li class="rating__row">
                      <div class="row-box">
                        <div class="rrow__label">Tốt</div>
                        <div class="rrow__percent">
                          <div class="progress-bar">
                            <div class="progress-bar__inner" style="width: 70%;"></div>
                          </div>
                        </div>
                        <div class="rrow__counting">14</div>
                        <div class="rrow__descr">đánh giá</div>
                      </div>
                      
                      <div class="row-box">
                        <div class="rrow__label">Rất tốt</div>
                        <div class="rrow__percent">
                          <div class="progress-bar">
                            <div class="progress-bar__inner" style="width: 70%;"></div>
                          </div>
                        </div>
                        <div class="rrow__counting">14</div>
                        <div class="rrow__descr">đánh giá</div>
                      </div>
                      
                      <div class="row-box">
                        <div class="rrow__label">Trung bình</div>
                        <div class="rrow__percent">
                          <div class="progress-bar">
                            <div class="progress-bar__inner" style="width: 70%;"></div>
                          </div>
                        </div>
                        <div class="rrow__counting">14</div>
                        <div class="rrow__descr">đánh giá</div>
                      </div>
                      
                      <div class="row-box">
                        <div class="rrow__label">Không tốt</div>
                        <div class="rrow__percent">
                          <div class="progress-bar">
                            <div class="progress-bar__inner" style="width: 90%;"></div>
                          </div>
                        </div>
                        <div class="rrow__counting">14</div>
                        <div class="rrow__descr">đánh giá</div>
                      </div>
                      
                      <div class="row-box">
                        <div class="rrow__label">Rất tệ</div>
                        <div class="rrow__percent">
                          <div class="progress-bar">
                            <div class="progress-bar__inner" style="width: 30%;"></div>
                          </div>
                        </div>
                        <div class="rrow__counting">14</div>
                        <div class="rrow__descr">đánh giá</div>
                      </div>
<!--                      <p> <span>đánh giá</span></p>
                      <p>Tốt <span>đánh giá</span></p>
                      <p>Trung bình <span>đánh giá</span></p>
                      <p>Trung bình <span>đánh giá</span></p>
                      <p> <span>đánh giá</span></p>-->
                    </li>
                  </ul>
                </div>
                <div class="comment">
                  <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
                  <ul class="list-comment">
                    <li>
                      <div class="comment-item">
                        <div class="avartar">
                           <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        </div>
                        <div class="comment-content">
                          <div class="comment-info">
                            <div class="user-comment-info">
                              <p><a href="#"><b>Pham Van Long</b></a></p>
                              <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
                            </div>
                            <p><a href="#"><strong>Facebook for Developers</strong></a></p>
                            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                            <div class="review-options">
                              <ul>
                                <li><span>Số người: 4</span></li>
                                <li><span>Chi phí: 1,000,000đ</span></li>
                                <li><span>Muốn quay lại: Chắc chắn</span></li>
                              </ul>
                            </div>
                            <div class="list-gallery">
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                            </div>
                          </div>
                          <div class="form-replies">
                            <div class="view-replies">
                              <div class="fs-comment icon icon-comment">
                                Trả lời
                              </div>
                              <div class="fs-like icon icon-heart-1">
                                Thích (10)
                              </div>
                              <div class="fs-share">
                                Chia sẻ
                                <div class="share-page">
                                  <ul>
                                    <li>
                                      <span>Điểm đia chơi</span>
                                    </li>
                                    <li>
                                      <span>Chia sẻ lên Facebook</span>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            
                            <div class="comment-replies">
                              <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                              <div class="comment-content">
                                <p><strong><a href="#">Phạm Long </a></strong>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                                <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
                              </div>
                            </div>
                            
                            <div class="comment-form-replies">
                              <div class="icon">
                                <div class="avartar">
                                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                               </div>
                              </div>
                              <div class="replies">
                                <textarea class="form-control"></textarea>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>
                    
                    <li>
                      <div class="comment-item">
                        <div class="avartar">
                           <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        </div>
                        <div class="comment-content">
                          <div class="comment-info">
                            <div class="user-comment-info">
                              <p><a href="#"><b>Pham Van Long</b></a></p>
                              <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
                            </div>
                            <p><a href="#"><strong>Facebook for Developers</strong></a></p>
                            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                            <div class="list-gallery">
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                              <a href="#">
                                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                              </a>
                            </div>
                          </div>
                          <div class="form-replies">
                            <div class="view-replies">
                              <div class="fs-comment icon icon-comment">
                                Trả lời
                              </div>
                              <div class="fs-like icon icon-heart-1">
                                Thích (10)
                              </div>
                              <div class="fs-share">
                                Chia sẻ
                                <div class="share-page">
                                  <ul>
                                    <li>
                                      <span>Điểm đia chơi</span>
                                    </li>
                                    <li>
                                      <span>Chia sẻ lên Facebook</span>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            
                            <div class="comment-replies">
                              <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                              <div class="comment-content">
                                <p><strong><a href="#">Phạm Long </a></strong>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                                <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
                              </div>
                            </div>
                            
                            <div class="comment-form-replies">
                              <div class="icon">
                                <div class="avartar">
                                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                               </div>
                              </div>
                              <div class="replies">
                                <textarea class="form-control"></textarea>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>

                    

                    

                    
                  </ul>
                  <div class="views-all">
                    <a>Xem thêm</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="list-related">
          <div class="map-content">
            <h2>Địa điểm khác gần Đầm sen</h2>
            <div class="related-item">
              <div class="map-related"></div>
                <div class="list-icon-support">
                  <ul>
                    <li class="current"><span></span> Địa điểm hiện tại</li>
                    <li class="tours"><span></span> Địa du lịch</li>
                    <li class="hotel"><span></span> Khách sạn</li>
                    <li class="taste"><span></span> Địa điểm ăn uống</li>
                    <li class="park"><span></span> Công viên - giải trí</li>
                  </ul>
                </div>
            </div>
          </div>
          
          <div class="support">
            <h2>Liên hệ đặt trực tuyến</h2>
            <ul>
              <li>
                <div class="item">
                  <div class="icon">

                  </div>
                  <div class="content-support">
                    <p class="name">Pham Van Long</p>
                    <p><a href="#">vanlong200880@gmail.com</a></p>
                    <p class="hotline">Hotline: 1900 1248</p>
                  </div>
                </div>
              </li>
              <li>
                <div class="item">
                  <div class="icon">

                  </div>
                  <div class="content-support">
                    <p class="name">Pham Van Long</p>
                    <p><a href="#">vanlong200880@gmail.com</a></p>
                    <p class="hotline">Hotline: 1900 1248</p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
        <div class="list-related list-province-item">
          <h2 class="title"><span>Địa điểm khác</span></h2>
          <ul class="list-travel">
            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="/tours/public/assets/demo/photo.jpg">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="item-des">
                      <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                      <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                      <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                      <div class="fs-game">
                        <ul class="list-game">
                          <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                          <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                          <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                        </ul>
                        <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            
            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="/tours/public/assets/demo/photo.jpg">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="item-des">
                      <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                      <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                      <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                      <div class="fs-game">
                        <ul class="list-game">
                          <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                          <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                          <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                        </ul>
                        <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            
            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="/tours/public/assets/demo/photo.jpg">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="item-des">
                      <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                      <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                      <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                      <div class="fs-game">
                        <ul class="list-game">
                          <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                          <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                          <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                        </ul>
                        <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            
            <li>
              <div class="item">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-img">
                      <a href="javascript:void(0);" title="dam sen">
                        <img src="/tours/public/assets/demo/photo.jpg">
                        <div class="overlay_border"></div>
                      </a>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="item-des">
                      <h2><a href="javascript:void(0);" title="dam sen">Đầm sen</a></h2>
                      <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                      <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                      <div class="fs-game">
                        <ul class="list-game">
                          <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                          <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                          <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                        </ul>
                        <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            
          </ul>
        </div>
      </div>
    </div>

  </div>
  </div>

  <div class="poup-footer">
  <div class="row">
   <div class="col-md-4">
     <h2>Công ty TNHH Smart Connector</h2>
     <ul>
       <li>294 Hòa bình, P. Hiệp Tân, Q. Tân Phú, TP.HCM</li>
       <li>ĐT: 08.73055707 - Fax: 08.38666237</li>
       <li><a href="#">sales@abc.vn</a></li>
       <li>Mã số thuế: 0310955176 do Sở Kế hoạch đầu tư TP HCM 
  cấp ngày 29/06/2011</li>
     </ul>
   </div>
   <div class="col-md-2">
     <h2>Về chúng tôi</h2>
     <ul>
       <li><a href="#">Giới thiệu</a></li>
       <li><a href="#">Quy định</a></li>
       <li><a href="#">Trợ giúp</a></li>
       <li><a href="#">Đăng ký quảng cáo</a></li>
       <li><a href="#">Liên hệ</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chăm sóc khách hàng</h2>
     <ul class="support-footer">
       <li><span class="hotline">HOTLINE</span> <span class="hotline-phone">08 7300 5757</span></li>
       <li><a href="#">Chính sách giao hàng</a></li>
       <li><a href="#">Chính sách đổi sản phẩm</a></li>
       <li><a href="#">Chính sách bảo mật</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chứng nhận</h2>
     <ul>
       <li><img src="/tours/public/frontend/images/bocongthuong.png"></li>
     </ul>
     <h2>Liên kết</h2>
     <ul class="connect">
       <li class="facebook"><a href="#"><span class="icon icon-facebook"></span></a></li>
       <li class="twitter"><a href="#"><span class="icon icon-twitter"></span></a></li>
       <li class="youtube"><a href="#"><span class="icon icon-youtube"></span></a></li>
       <li class="googleplus"><a href="#"><span class="icon icon-googleplus"></span></a></li>
       <li class="linkedin"><a href="#"><span class="icon icon-linkedin"></span></a></li>
       <li class="pinterest"><a href="#"><span class="icon icon-pinterest"></span></a></li>
     </ul>
   </div>
  </div>
  </div>

  <div class="coppyright">
  <div class="row">
    <div class="col-md-12">
       <p>Coppyright © 2015 Long.pham. All Rights Reserved</p>
     </div>
  </div>
  </div>
<script>
  jQuery(document).ready(function($){
    // menu fixed 
//    var topHeight = $(window).scrollTop();
    $(".popup-page.on").scroll(function(){
      var topHeight = $(".popup-page.on").scrollTop();
      var divWidth = $(".tab-travel").width();
      $(".tab-travel").css('width', divWidth);
      if(topHeight >= 600){
        $("ul.tab-travel").addClass('fixed');
      }else{
        $("ul.tab-travel").removeClass('fixed');
      }
    });
  
    // scroll div
    $(".tab-travel").on('click', 'li', function(){
      var id = $(this).attr('data-id');
//      h  = $('#'+id).offset().top;
//      console.log(h);
//      $('.popup-page').animate({scrollTop: $("#"+id).position().top}, 800, 'swing');
//      $('.popup-page').animate({ scrollTop: h}, 800, 'swing');
    });
    // show detail gallery
    $(".game-entertainment tr td").on('click','.history', function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/view-gallery';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".views-popup").addClass('view');
            $(".views-popup").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".views-popup .views-container").empty().append(data.html);
            // call royalSlider
            var slider = $('.royalSlider').royalSlider({
            fullscreen: {
              enabled: false,
              nativeFS: false
            },
            controlNavigation: 'thumbnails',
            autoScaleSlider: true, 
            autoScaleSliderWidth: 725,
            autoScaleSliderHeight: 478,
            loop: false,
            imageScaleMode: 'none',
            navigateByClick: true,
            numImagesToPreload:2,
            arrowsNav:true,
            arrowsNavAutoHide: true,
            arrowsNavHideOnTouch: true,
            keyboardNavEnabled: true,
            fadeinLoadedSlide: true,
            globalCaption: false,
            globalCaptionInside: false,
            imageScalePadding: 0,
            slidesSpacing: 0,
            thumbs: {
              appendSpan: false,
              firstMargin: false,
              paddingBottom: 4
            }
            }).data('royalSlider');

            $('.rsFullscreenBtn').click(function(e){
              slider.enterFullscreen();
              e.preventDefault();
            });

            slider.ev.on("rsEnterFullscreen", function() {
              // enter fullscreen mode 
              $(".popup-page").css('position', 'relative');
            });
            slider.ev.on('rsExitFullscreen', function(event) {
              // exit fullscreen mode
              $(".popup-page").removeAttr('style');
            });
            // view map popup
            $(".views-popup .views-container").addClass('open');
          }
        });
    });
    
    // comment
    $(".comment ul.list-comment > li").on('click', '.fs-comment', function(){
      var find = $(this);
      find.parents('.form-replies').find('.comment-form-replies').find('.form-control').focus().animate({scrollTop:308}, 'slow');
    });
  });
</script>

