<div class="search">
  <div class="page-search">
    <div class="search-item">
      <div class="search-list">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="list-search">
                <div class="row">
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">-- Quốc gia -- </option>
                      <option value="">Việt Nam</option>
                      <option value="">Thái Lan</option>
                      <option>Ấn Độ</option>
                      <option>Mỹ</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">-- Tỉnh/Thành Phố -- </option>
                      <option>Bình Phước</option>
                      <option>Hà Nội</option>
                      <option>Hải Dương</option>
                      <option>Bình Định</option>
                      <option>Quản Trị</option>
                      <option>Quảng Nam</option>
                      <option>Huế</option>
                      <option>Đà Nẵng</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                        <option value="">-- Quận/Huyện -- </option>
                        <option>Quận 1</option>
                        <option>Quận 2</option>
                        <option>Quận 3</option>
                        <option>Quận 4</option>
                        <option>Quận 5</option>
                      </select>
<!--                    <script>
                    jQuery(document).ready(function($){
                      var isClick = false;
                      $(".item-search-type ul>li").on('click', function(e){
                        $(".menu-search li").removeClass('selected');
                        if(isClick != true){
                          $(this).addClass('selected');
                          isClick = true;
                        }else{
                          $(this).removeClass('selected');
                          isClick = false;
                        }
                        e.stopPropagation();
                    });
                    $(document).click(function(e) {
                      isClick = false;
                      if (!$(e.target).is('.item, .item *')) {
                        $(".item-search-type li.item").removeClass('selected');
                      }
                    });
                  });
                    </script>-->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> Tour du lịch</h1>
    </div>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="list-cat">
        <div class="filter">
          <ul>
            <li><a href="#">Bán chạy <span class="icon icon-down-thin"></span></a></li>
            <li><a href="#">Mới nhất <span class="icon icon-up-thin"></span></a></li>
            <li><a href="#">Giá <span class="icon icon-up-thin"></span></a></li>
            <li><a href="#">Khuyến mãi <span class="icon icon-up-thin"></span></a></li>
          </ul>
        </div>
        <ul class="row list-item">
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li><li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>HOT</span></div>
                <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="abc">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a title="abc" href="<?php echo $this->url('tour/tour-category', array('controller' => 'category', 'action' => 'index', 'category' => 'tour-ha-noi-bai-dinh-kdl-trang-an-co-1-ngay-danh-cho-1-nguoi')); ?>">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          

        </ul>
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content">
    <div class="map-wp">
      <div style="width: 100%; height: 100%;" id="map"></div>
    </div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>-->