<div class="detail-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Khu du lịch Đầm Sen</h1>
      </div>
      <div class="col-md-12">
        <div class="slider">
          <div class="row">
            <div class="col-md-8">
              <div class="royalSlider rsDefault">
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
                 <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
               </div>
              <script>
                    jQuery(document).ready(function($){
                      // call royalSlider
                      var slider = $('.royalSlider').royalSlider({
                      fullscreen: {
                        enabled: true,
                        nativeFS: true
                      },
                      controlNavigation: 'thumbnails',
                      autoScaleSlider: true, 
                      autoScaleSliderWidth: 1024,
                      autoScaleSliderHeight: 614,
                      loop: false,
                      imageScaleMode: 'none',
                      navigateByClick: true,
                      numImagesToPreload:2,
                      arrowsNav:true,
                      arrowsNavAutoHide: true,
                      arrowsNavHideOnTouch: true,
                      keyboardNavEnabled: true,
                      fadeinLoadedSlide: true,
                      globalCaption: true,
                      globalCaptionInside: false,
                      imageScalePadding: 0,
                      slidesSpacing: 0,
                      thumbs: {
                        appendSpan: true,
                        firstMargin: true,
                        paddingBottom: 4
                      }
                      }).data('royalSlider');

                      $('.rsFullscreenBtn').click(function(e){
                        slider.enterFullscreen();
                        e.preventDefault();
                      });

                      slider.ev.on("rsEnterFullscreen", function() {
                        // enter fullscreen mode 
                        $(".popup-page").css('position', 'relative');
                      });
                      slider.ev.on('rsExitFullscreen', function(event) {
                        // exit fullscreen mode
                        $(".popup-page").removeAttr('style');
                      });
                    });
                    </script>
            </div>
            <div class="col-md-4">
              <div class="description">
                 <h2>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</h2>
                 <p class="expt">Tour Campuchia – Lào – Đông Bắc Thái Lan Đi Về Bằng Xe Dành Cho 01 Khách
      – Chuyến Hành Trình 4 Ngày 3 Đêm Cực Kỳ Thú Vị Và Đặc Sắc. Voucher 
      7.890.000 VNĐ, Còn 5.790.000 VNĐ, Giảm 27%.</p>
                 <div class="item">
                   <p class="cost">Giá gốc: 800,000<span>đ</span></p>
                   <p class="price-sale">1,800,000<span>đ</span> <var>-50%</var></p>
                 </div>
                 <div class="item">
                   <div class="quanlity">
                     Số lượng: <input type="number" name="quanlity">
                   </div>
                   <div class="payment">
                     <a href="#" class="pull-right">Mua ngay</a>
                   </div>
                 </div>
                 <div class="item">
                   <p class="count-user-payment"><span class="icon icon-user-profile"></span>102 người đã mua</p>
                   <p class="time">19 Ngày 04 : 36 : 09</p>
                 </div>
                 <div class="item">
                   <p>Giao hàng miễn phí tại TP.HCM</p>
                 </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-md-12">
        <div class="list-tours-related">
          <h2>Các điểm tham quan trong tour này</h2>
          <div class="swiper-container">
            <ul class="swiper-wrapper">
              <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>
             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>
             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>
             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>

             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>

             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>

             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>
             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>

             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>

             <li class="col-md-2 swiper-slide">
               <div class="item">
                 <div class="photo">
                   15 Ảnh
                 </div>
                 <p class="img"><a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a></p>
                  <p class="title"><a href="#">Khu du lịch thác Giang Điền</a></p>
               </div>
             </li>

            </ul>
          </div>
          <div class="swiper-btn button-prev"><span class="icon icon-left-chevron"></span></div>
          <div class="swiper-btn button-next"><span class="icon icon-right-chevron"></span></div>
       </div>
        
        <script>
          jQuery(document).ready(function($){
            // call swiper
            var swiper = new Swiper('.swiper-container', {
              nextButton: '.button-next',
              prevButton: '.button-prev',
              paginationClickable: true,
              slidesPerView: 5,
              spaceBetween: 5,
              breakpoints: {
                  1024: {
                      slidesPerView: 4,
                      spaceBetween: 40
                  },
                  768: {
                      slidesPerView: 3,
                      spaceBetween: 30
                  },
                  640: {
                      slidesPerView: 2,
                      spaceBetween: 20
                  },
                  320: {
                      slidesPerView: 1,
                      spaceBetween: 10
                  }
                }
              });
          });
        </script>
      </div>
      
      <div class="col-md-12">
        <div class="commitment">
          <div class="commitment-view">
            <div class="content">
              <div class="col-md-7">
               <h2>ĐIỂM NỔI BẬT</h2>
               <p>- Tour Campuchia – Lào – Đông Bắc Thái Lan trong 4N3Đ do Viet Kite Travel – đơn vị lữ hành giàu kinh nghiệm 
                 đứng ra tổ chức.</p><p>
      - Tham gia vào chuyến hành trình, bạn sẽ được đặt chân đến nhiều địa danh khác nhau: Strung Treng 
      (Campuchia), Pakse (Lào), Ubon Ratchathani (Thái Lan).</p><p>
      - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
      được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
      Phapheng – thác nước lớn nhất Đông Nam </p>
               <p>- Tour Campuchia – Lào – Đông Bắc Thái Lan trong 4N3Đ do Viet Kite Travel – đơn vị lữ hành giàu kinh nghiệm 
                 đứng ra tổ chức.</p><p>
      - Tham gia vào chuyến hành trình, bạn sẽ được đặt chân đến nhiều địa danh khác nhau: Strung Treng 
      (Campuchia), Pakse (Lào), Ubon Ratchathani (Thái Lan).</p><p>
      - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
      được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
      Phapheng – thác nước lớn nhất Đông Nam </p>
             </div>
             <div class="col-md-5">
               <h2>Cam ket</h2>
               <p>
      - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
      được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
      Phapheng – thác nước lớn nhất Đông Nam </p>
               <p>
      - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
      được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
      Phapheng – thác nước lớn nhất Đông Nam </p>
               <p>
      - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
      được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
      Phapheng – thác nước lớn nhất Đông Nam </p>
             </div>
            </div>
          </div>
          <div class="col-md-12 readmove">
            <a href="#"><span class="text">Xem thêm</span> <span class="icon icon-angle-down"></span></a>
          </div>
          <script>
            jQuery(document).ready(function($){
              $(".readmove a").on('click', function(){
                if($(this).hasClass('up')){
                   $(".commitment .commitment-view .content").removeClass('expanded');
                   $(".readmove a span.text").empty().append('Xem thêm');
                   $(this).removeClass('up');
                }else{
                   $(".commitment .commitment-view .content").addClass('expanded');
                   $(".readmove a span.text").empty().append('Thu gọn');
                   $(this).addClass('up');
                }

              });
            });
          </script>
        </div>
      </div>
      
      
      <div class="col-md-12">
        <div class="content-page-popup">
          <div class="row">
            <div class="col-md-9 about">
              <div class="tab-title">
                <ul>
                  <li class="active"><a href="#">Thông tin chi tiết</a></li>
                  <li><a href="javascript:void(0)" id="tab-comment">Bình luận</a></li>
                </ul>
              </div>
              <div class="detail">
                <h2>Giới thiệu</h2>
                <div class="description">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
       occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <div  class="payment-now">
                  <a href="#">Mua ngay</a>
                </div>
              </div>


              <div class="comment" id="detail-comment">
                <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
                <ul class="list-comment">
                  <li>
                    <div class="comment-item">
                      <div class="avartar">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                      </div>
                      <div class="comment-content">
                        <div class="comment-info">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          <div class="list-gallery">
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                          </div>
                          <div class="form-replies">
                            <a class="fs-comment">
                              Trả lời
                            </a>
                            <a class="fs-like">
                              Thích (10)
                            </a>
                            <a class="fs-share">
                              Chia sẻ
                            </a>
                          </div>
                        </div>
                        <div class="comment-replies">
                          <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                          <div class="comment-content">
                            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li>
                    <div class="comment-item">
                      <div class="avartar">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                      </div>
                      <div class="comment-content">
                        <div class="comment-info">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          <div class="list-gallery">
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                          </div>
                          <div class="form-replies">
                            <a class="fs-comment">
                              Trả lời
                            </a>
                            <a class="fs-like">
                              Thích (10)
                            </a>
                            <a class="fs-share">
                              Chia sẻ
                            </a>
                          </div>
                        </div>
                        <div class="comment-replies">
                          <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                          <div class="comment-content">
                            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li>
                    <div class="comment-item">
                      <div class="avartar">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                      </div>
                      <div class="comment-content">
                        <div class="comment-info">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          <div class="list-gallery">
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                          </div>
                          <div class="form-replies">
                            <a class="fs-comment">
                              Trả lời
                            </a>
                            <a class="fs-like">
                              Thích (10)
                            </a>
                            <a class="fs-share">
                              Chia sẻ
                            </a>
                          </div>
                        </div>
                        <div class="comment-replies">
                          <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                          <div class="comment-content">
                            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li>
                    <div class="comment-item">
                      <div class="avartar">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                      </div>
                      <div class="comment-content">
                        <div class="comment-info">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          <div class="list-gallery">
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                            <a href="#">
                              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                            </a>
                          </div>
                          <div class="form-replies">
                            <a class="fs-comment">
                              Trả lời
                            </a>
                            <a class="fs-like">
                              Thích (10)
                            </a>
                            <a class="fs-share">
                              Chia sẻ
                            </a>
                          </div>
                        </div>
                        <div class="comment-replies">
                          <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                          <div class="comment-content">
                            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                </ul>
                <div class="views-all">
                  <a>Xem thêm</a>
                </div>
              </div>

            </div>
            <div class="col-md-3">
              <div class="post-position">
                <h2>ĐỊA ĐIỂM SỬ DỤNG</h2>
                <h3>Vietkite Travel</h3>
                <p>512 Bùi Đình Túy, Phường 12, Quận Bình Thạnh</p>
                <p>Điện thoại: 0873003799</p>
                <div class="map-position"></div>
              </div>
              <div class="list-related">
                <ul class="row list-item">
                  <li class="col-md-12">
                    <div class="item">
                      <div class="img">
                        <div class="highlight"><span>HOT</span></div>
                        <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                        <div class="item-hover">
                          <div class="item-voucher">
                            Nhân voucher điện tử qua email/SMS
                          </div>
                          <div class="readmove">
                            <a href="#">Xem ngay</a>
                          </div>
                        </div>
                      </div>
                      <div class="item-content">
                        <div class="title">
                          <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                        </div>
                        <div class="price">
                          <p>
                            <span class="cost">350,000 <var>đ</var></span>
                            <span class="sale">-50%</span>
                          </p>
                        </div>
                        <div class="view-user">
                          <span class="price-sale">350,000</span>  <var>đ</var>
                          <div class="pull-right">
                            <span class="icon icon-user-profile"> 1124</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                  <li class="col-md-12">
                    <div class="item">
                      <div class="img">
                        <div class="highlight"><span>HOT</span></div>
                        <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                        <div class="item-hover">
                          <div class="item-voucher">
                            Nhân voucher điện tử qua email/SMS
                          </div>
                          <div class="readmove">
                            <a href="#">Xem ngay</a>
                          </div>
                        </div>
                      </div>
                      <div class="item-content">
                        <div class="title">
                          <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                        </div>
                        <div class="price">
                          <p>
                            <span class="cost">350,000 <var>đ</var></span>
                            <span class="sale">-50%</span>
                          </p>
                        </div>
                        <div class="view-user">
                          <span class="price-sale">350,000</span>  <var>đ</var>
                          <div class="pull-right">
                            <span class="icon icon-user-profile"> 1124</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li class="col-md-12">
                    <div class="item">
                      <div class="img">
                        <div class="highlight"><span>HOT</span></div>
                        <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                        <div class="item-hover">
                          <div class="item-voucher">
                            Nhân voucher điện tử qua email/SMS
                          </div>
                          <div class="readmove">
                            <a href="#">Xem ngay</a>
                          </div>
                        </div>
                      </div>
                      <div class="item-content">
                        <div class="title">
                          <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                        </div>
                        <div class="price">
                          <p>
                            <span class="cost">350,000 <var>đ</var></span>
                            <span class="sale">-50%</span>
                          </p>
                        </div>
                        <div class="view-user">
                          <span class="price-sale">350,000</span>  <var>đ</var>
                          <div class="pull-right">
                            <span class="icon icon-user-profile"> 1124</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li class="col-md-12">
                    <div class="item">
                      <div class="img">
                        <div class="highlight"><span>HOT</span></div>
                        <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                        <div class="item-hover">
                          <div class="item-voucher">
                            Nhân voucher điện tử qua email/SMS
                          </div>
                          <div class="readmove">
                            <a href="#">Xem ngay</a>
                          </div>
                        </div>
                      </div>
                      <div class="item-content">
                        <div class="title">
                          <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                        </div>
                        <div class="price">
                          <p>
                            <span class="cost">350,000 <var>đ</var></span>
                            <span class="sale">-50%</span>
                          </p>
                        </div>
                        <div class="view-user">
                          <span class="price-sale">350,000</span>  <var>đ</var>
                          <div class="pull-right">
                            <span class="icon icon-user-profile"> 1124</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

                  <li class="col-md-12">
                    <div class="item">
                      <div class="img">
                        <div class="highlight"><span>HOT</span></div>
                        <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                        <div class="item-hover">
                          <div class="item-voucher">
                            Nhân voucher điện tử qua email/SMS
                          </div>
                          <div class="readmove">
                            <a href="#">Xem ngay</a>
                          </div>
                        </div>
                      </div>
                      <div class="item-content">
                        <div class="title">
                          <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                        </div>
                        <div class="price">
                          <p>
                            <span class="cost">350,000 <var>đ</var></span>
                            <span class="sale">-50%</span>
                          </p>
                        </div>
                        <div class="view-user">
                          <span class="price-sale">350,000</span>  <var>đ</var>
                          <div class="pull-right">
                            <span class="icon icon-user-profile"> 1124</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>


                </ul>
              </div>

            </div>
          </div>
        </div>
      </div>
      
      
      
    </div>
  </div>
</div>


