<ul>
  <li>
    <a href="<?php echo $this->url('user/user-taste', array('controller' => 'taste', 'action' => 'index')) ?>"><span></span>Quản lý điểm ăn uống</a>
  </li>
  <li class="active">
    <a href="<?php echo $this->url('user/user-taste', array('controller' => 'taste', 'action' => 'index')) ?>"><span class="icon icon-menu"></span>Danh sách</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/user-taste-create', array('controller' => 'taste', 'action' => 'create')) ?>"><span class="icon icon-file-add"></span>Tạo nhóm thực đơn</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/user-taste-create', array('controller' => 'taste', 'action' => 'create')) ?>"><span class="icon icon-file-add"></span>Tạo thực đơn</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'taste', 'action' => 'order')) ?>"><span></span>Đơn hàng</a>
  </li>

  <li>
    <a href="#"><span class="icon icon-help-circled"></span>Trợ giúp</a>
  </li>
</ul>