<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>

  <li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="star">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
        <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
      </div>
      <div class="highlight"><span>HOT</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
      <div class="item-hover">
        <div class="item-voucher">
          Nhân voucher điện tử qua email/SMS
        </div>
        <div class="readmove">
          <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
      </div>
      <div class="price">
        <p>
          <span class="cost">350,000 <var>đ</var></span>
          <span class="sale">-50%</span>
        </p>
      </div>
      <div class="view-user">
        <span class="price-sale">350,000</span>  <var>đ</var>
        <div class="pull-right">
          <span class="icon icon-user-profile"> 1124</span>
        </div>
      </div>
    </div>
  </div>
  </li>