<div class="swiper-container-slider">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <a href="#"><img src="<?php echo $this->basePath('assets/demo/slider.png'); ?>" alt="The Last of us"></a>
    </div>
    <div class="swiper-slide">
      <a href="#"><img src="<?php echo $this->basePath('assets/demo/slider.png'); ?>" alt="The Last of us"></a>
    </div>
  </div>
  <!-- Add Arrows -->
  <div class="swiper-button-next"></div>
  <div class="swiper-button-prev"></div>
</div>



<script>
  var swiper = new Swiper('.swiper-container-slider', {
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        paginationClickable: true,
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: 4000,
        autoplayDisableOnInteraction: false,
        grabCursor: true,
        effect:'slide',
    });
//  jQuery(document).ready(function($) {
//    $("#owl-slider").owlCarousel({
//    autoPlay: 6000,
//    navigation : true,
//    slideSpeed : 300,
//    paginationSpeed : 400,
//    singleItem : true,
//    navigation : true,
//    paginationSpeed : 400,
//    pagination : false,
//    paginationNumbers: false,
//    singleItem : true,
//    navigationText : ["<i class='icon icon-left-chevron'></i>","<i class='icon icon-right-chevron'></i>"],
//    rewindNav : true,
//    stopOnHover : true
//
//    // "singleItem:true" is a shortcut for:
//    // items : 1, 
//    // itemsDesktop : false,
//    // itemsDesktopSmall : false,
//    // itemsTablet: false,
//    // itemsMobile : false
//
//    });
//  });
</script>