<ul>
  <li>
    <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>">
      <span></span>Quản lý tài khoản</a>
  </li>
  <li class="active">
    <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>">
      <span class="icon icon-menu"></span>Timeline</a>
  </li>
  <li>
    <a href="<?php echo $this->url('user/user-profile', array('controller' => 'user', 'action' => 'profile')) ?>">
      <span class="icon icon-file-add"></span>Thông tin tài khoản</a>
  </li>
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Đơn hàng của tôi</a>
  </li>
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Sản phẩm yêu thích</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Điểm tích lũy</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>E-Voucher</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Quản lý Tours</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Quản lý khách sạn</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Quản lý Blog</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
      <span></span>Quản lý điểm ăn uống</a>
  </li>

  <li>
    <a href="#"><span class="icon icon-help-circled"></span>Trợ giúp</a>
  </li>
</ul>