<div class="company">
  <div class="footer-item">
    <h2>CHĂM SÓC KHÁCH HÀNG</h2>
    <ul>
      <li><span class="hotline">HOTLINE</span> <span class="hotline-phone">08 7300 5757</span></li>
      <li><a href="#">Chính sách giao hàng</a></li>
      <li><a href="#">Chính sách đổi sản phẩm</a></li>
      <li><a href="#">Chính sách bảo mật</a></li>
    </ul>
  </div>
  <div class="footer-item">
    <h2>Chứng nhận</h2>
    <ul>
      <li><img src="/tours/public/frontend/images/bocongthuong.png"></li>
    </ul>
  </div>
  <div class="footer-item-address">
    <h2>CÔNG TY TNHH SMART CONNECTOR</h2>
    <p>294 Hòa bình, P. Hiệp Tân, Q. Tân Phú, TP.HCM</p>
    <p>ĐT: 08.73055707 - Fax: 08.38666237</p>
    <p>sales@abc.vn</p>
    <p>Mã số thuế: 0310955176 do Sở Kế hoạch đầu tư TP HCM cấp ngày 29/06/2011</p>
  </div>
</div>
<div class="footer-page">
  <div class="menu-footer">
    <ul>
      <li><a href="#">Giới thiệu</a></li>
      <li><a href="#">Quy định</a></li>
      <li><a href="#">Trợ giúp</a></li>
      <li><a href="#">Đăng ký quảng cáo</a></li>
      <li><a href="#">Liên hệ</a></li>
    </ul>
  </div>
  <div class="coppyright">
    <p>Coppyright © 2015 Long.pham. All Rights Reserved</p>
    <ul class="connect">
      <li class="facebook"><a href="#"><span class="icon icon-facebook"></span></a></li>
      <li class="twitter"><a href="#"><span class="icon icon-twitter"></span></a></li>
      <li class="youtube"><a href="#"><span class="icon icon-youtube"></span></a></li>
      <li class="googleplus"><a href="#"><span class="icon icon-googleplus"></span></a></li>
      <li class="linkedin"><a href="#"><span class="icon icon-linkedin"></span></a></li>
      <li class="pinterest"><a href="#"><span class="icon icon-pinterest"></span></a></li>
    </ul>
  </div>
</div>