<div class="container">
  <div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 forgot">
    <div class="login-row">
      <div class="form-login">
        <div class="row">
          <div class="col-md-12"><h1>Quên mật khẩu</h1></div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="email">Vui lòng gửi email. Chúng tôi sẽ gửi link khởi tạo mật khẩu mới qua email của bạn.</label>
              <div class="form-input">
                <input type="text" class="form-control" id="email" placeholder="Email">
                <span class="icon icon-man-people-streamline-user"></span>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">
                <button type="submit" class="btn btn-default  ">Gửi</button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</div>