<div class="container">
  <div class="row">
    <div class="col-md-7"></div>
    <div class="col-md-5">
      <div class="login-row">
        <div class="form-login">
          <div class="row">
            <div class="col-md-12"><h1>Đăng nhập</h1></div>
            <div class="col-md-12">
              <div class="form-group">
                <label for="email">Email</label>
                <div class="form-input">
                  <input type="text" class="form-control" id="email" placeholder="Email">
                  <span class="icon icon-man-people-streamline-user"></span>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <label for="password">Mật khẩu</label>
                <div class="form-input">
                  <input type="password" class="form-control" id="password" placeholder="******">
                  <span class="icon icon-lock"></span>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-6">
                  <label>
                    <input type="checkbox"> Ghi nhớ
                  </label>
                </div>
                <div class="col-md-6">
                  <a href="<?php echo $this->url('forgot', array('controller' => 'public', 'action' => 'forgot')) ?>" class="pull-right">Quên mật khẩu?</a>
                </div>
              </div>
            </div>

            <div class="col-md-12">
              <div class="row">
                <div class="col-md-6">
                  <button type="submit" class="btn btn-default  ">Đăng nhập</button>
                </div>
                <div class="col-md-6">
                  <p>Bạn chưa có tài khoản? <a href="<?php echo $this->url('register', array('controller' => 'public', 'action' => 'register')) ?>">Đăng ký</a> tại đây</p>

                </div>
              </div>
            </div>
          </div>

        </div>
        <div class="login-social-footer">
            <div class="login-social">
              <div class="row">
                <div class="col-md-6">
                  <a href="#" class="facebook"><span class="icon icon-facebook-1"></span>Tài khoản Facebook</a>
                </div>
                <div class="col-md-6">
                  <a href="#" class="google"><span class="icon icon-gplus"></span>Tài khoản Google</a>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>