<div class="row">
  <div class="col-md-7"></div>
  <div class="col-md-5">
    <div class="login-row">
      <div class="form-login">
        <div class="row">
          <div class="col-md-12"><h1>Tạo tài khoản</h1></div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="fullname">Họ và tên</label>
              <div class="form-input">
                <input type="text" class="form-control" id="fullname" placeholder="Họ và tên">
                <span class="icon icon-man-people-streamline-user"></span>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <label for="email">Email</label>
              <div class="form-input">
                <input type="text" class="form-control" id="email" placeholder="Email">
                <span class="icon icon-man-people-streamline-user"></span>
              </div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <label for="password">Mật khẩu</label>
              <div class="form-input">
                <input type="password" class="form-control" id="password" placeholder="******">
                <span class="icon icon-lock"></span>
              </div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="form-group">
              <label for="repassword">Nhập lại mật khẩu</label>
              <div class="form-input">
                <input type="password" class="form-control" id="repassword" placeholder="******">
                <span class="icon icon-lock"></span>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-12">
                <label>Ngày sinh</label>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <div class="form-input">
                    <select class="form-control">
                      <option value="">Ngày</option>
                    </select>
                  </div>
                </div>

              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <div class="form-input">
                    <select class="form-control">
                      <option value="">Tháng</option>
                    </select>
                  </div>
                </div>

              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <div class="form-input">
                    <select class="form-control">
                      <option value="">Năm</option>
                    </select>
                  </div>
                </div>

              </div>
            </div>
          </div>


          <div class="col-md-12">
            <div class="row">
              <div class="col-md-12">
                <label>Giới tính</label>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <div class="form-input">
                    <select class="form-control">
                      <option value="">Chọn</option>
                      <option value="">Nam</option>
                      <option value="">Nữ</option>
                    </select>
                  </div>
                </div>

              </div>

            </div>
          </div>


          <div class="col-md-12">
            <p class="regulation">Khi bạn nhấn Đăng ký, bạn đã đồng ý thực hiện mọi giao dịch mua bán theo <a href="#">điều kiện sử dụng và chính sách</a> của chúng tôi.</p>
          </div>
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">
                <button type="submit" class="btn btn-default  ">Đăng ký</button>
              </div>
              <div class="col-md-6">
                <p class="register"><a href="<?php echo $this->url('login', array('controller' => 'public', 'action' => 'login')) ?>">Bạn đã đăng ký?</a></p>

              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="login-social-footer">
          <div class="login-social">
            <div class="row">
              <div class="col-md-6">
                <a href="#" class="facebook"><span class="icon icon-facebook-1"></span>Tài khoản Facebook</a>
              </div>
              <div class="col-md-6">
                <a href="#" class="google"><span class="icon icon-gplus"></span>Tài khoản Google</a>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>