<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <ul>
                <li>
                  <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>"><span></span>Quản lý tours</a>
                </li>
                <li class="active">
                  <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>"><span class="icon icon-menu"></span>Danh sách tour</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('user/post', array('controller' => 'tours', 'action' => 'post')) ?>"><span class="icon icon-file-add"></span>Tạo tour</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>"><span></span>Đơn hàng</a>
                </li>
                
                <li>
                  <a href="#"><span class="icon icon-help-circled"></span>Trợ giúp</a>
                </li>
              </ul>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Danh sách bình luận</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <div class="list-tours">
                    <table class="list-table">
                      <thead>
                        <tr>
                          <th>STT</th>
                          <th>Tên</th>
                          <th>Ngày bình luận</th>
                          <th>Trang thái</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>1</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Trả lời"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>2</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>3</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>4</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>5</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>6</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>7</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>8</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>9</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>10</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>11</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>12</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>13</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>14</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>15</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>16</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>17</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>18</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>19</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        <tr>
                          <td>20</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>