<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuHotel(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Đăng khách sạn</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Đăng khách sạn</h2>
                  <div class="page">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Tên khách sạn</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Số tầng</label>
                          <select class="form-control">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                          </select>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Mô tả ngắn</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giá</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Điểm nổi bật</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Quy định và lưu ý đặt phòng</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giá trung bình</label>
                          <input type="text" class="form-control" placeholder="10.000đ - 35.000đ" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Điện thoại hotline</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Video</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ngày bắt đầu</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ngày kết thúc</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ảnh đại điện</label>
                          <input type="file">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1"> Gallery </label>
                          <input type="file">
                        </div>
                        
                      </div>
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Nội dung</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="utilities">
                          <h2>TIỆN NGHI KHÁCH SẠN</h2>
                          <ul>
                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Tắm hơp</p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Dịch vụ dọn Phòng</p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Cafe</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Gym</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Hồ bơi trong nhà</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Giặt ủi</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Dịch vụ phòng họp</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Dịch vụ phòng 24/24</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Nhà hàng</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Spa</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Wifi khu vực công cộng</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Thang máy</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Đưa đón sân bay</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Bàn làm việc</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Nhân viên vận chuyển</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Quán cafe</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Quầy bán Tour</p>
                              </div>
                            </li>


                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Lễ tân phục vụ 24 giờ</p>
                              </div>
                            </li>


                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Bãi đậu xe</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Bàn làm việc</p>
                              </div>
                            </li>

                            <li>
                              <div class="item">
                                <p><input type="checkbox"></p>
                                <p>Buffet sáng</p>
                              </div>
                            </li>
                          </ul>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <button type="submit" class="btn btn-primary">Lưu và tạo phòng</button>
                        </div>
                        
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>