<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuTaste(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Tên quán</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Tạo menu cho quán</h2>
                  <div class="page">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Tên món ăn</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Nhóm món ăn</label>
                          <select class="form-control">
                            <option>Chọn</option>
                            <option>Cháo</option>
                            <option>Trà - Cafe</option>
                          </select>
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giá</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Video</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1"> Ảnh đại diện </label>
                          <input type="file">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1"> Gallery </label>
                          <input type="file">
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giới thiệu món ăn</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Tạo món ăn</button>
                      </div>
                      <div class="col-md-12">
                        <div class="menu-order list-menu-create-taste">
                          <h2>Cháo</h2>
                          <ul>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                          </ul>
                          
                          <h2>Cháo</h2>
                          <ul>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                            <li>
                              <div class="item">
                                <img src="/tours/public/assets/taste.jpg">
                                <p>
                                  <span>Cháo ếch Singapore</span> 
                                  <var class="pull-right">150.000vnđ <a href="#" title="Sửa" class="icon icon-pencil"></a> <a href="#" class="icon icon-delete-garbage-streamline" title="Xóa"></a></var>
                                </p>
                              </div>
                            </li>
                          </ul>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>