<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuHotel(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Danh sách khách sạn</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <div class="list-tours">
                    <table class="list-table">
                      <thead>
                        <tr>
                          <th>STT</th>
                          <th>Tên</th>
                          <th>Ngày đăng</th>
                          <th>Trạng thái</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>1</td>
                          <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                          <td>20-08-2016:15:30:15</td>
                          <td>Đã đăng</td>
                          <td class="function">
                            <a href="#" title="Sửa"><span class="icon icon-pencil"></span></a>
                            <a href="#" title="Xóa"><span class="icon icon-delete-garbage-streamline"></span></a>
                            <a href="#" title="Làm mới"><span class="icon icon-refresh"></span></a>
                          </td>
                        </tr>
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>