<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>Công ty TNHH Smart Connector</h2>
        <ul>
          <li>294 Hòa bình, P. Hiệp Tân, Q. Tân Phú, TP.HCM</li>
          <li>ĐT: 08.73055707 - Fax: 08.38666237</li>
          <li><a href="#">sales@abc.vn</a></li>
          <li>Mã số thuế: 0310955176 do Sở Kế hoạch đầu tư TP HCM 
cấp ngày 29/06/2011</li>
        </ul>
      </div>
      <div class="col-md-3">
        <h2>Về chúng tôi</h2>
        <ul>
          <li><a href="#">Giới thiệu</a></li>
          <li><a href="#">Quy định</a></li>
          <li><a href="#">Trợ giúp</a></li>
          <li><a href="#">Đăng ký quảng cáo</a></li>
          <li><a href="#">Liên hệ</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h2>Chăm sóc khách hàng</h2>
        <ul class="support-footer">
          <li><span class="hotline">HOTLINE</span> <span class="hotline-phone">08 7300 5757</span></li>
          <li><a href="#">Chính sách giao hàng</a></li>
          <li><a href="#">Chính sách đổi sản phẩm</a></li>
          <li><a href="#">Chính sách bảo mật</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h2>Chứng nhận</h2>
        <ul>
          <li><img src="<?php echo $this->basePath('/frontend/images/bocongthuong.png'); ?>"></li>
        </ul>
        <h2>Liên kết</h2>
        <ul class="connect">
          <li class="facebook"><a href="#"><span class="icon icon-facebook"></span></a></li>
          <li class="twitter"><a href="#"><span class="icon icon-twitter"></span></a></li>
          <li class="youtube"><a href="#"><span class="icon icon-youtube"></span></a></li>
          <li class="googleplus"><a href="#"><span class="icon icon-googleplus"></span></a></li>
          <li class="linkedin"><a href="#"><span class="icon icon-linkedin"></span></a></li>
          <li class="pinterest"><a href="#"><span class="icon icon-pinterest"></span></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="coppyright">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p>Coppyright © 2015 Long.pham. All Rights Reserved</p>
      </div>
    </div>
  </div>
</div>