<div class="popup-content">
  <div class="popup-header">
   <h2><span class="icon icon-location"></span> Địa điểm ăn uống</h2>
   <div class="close-zoom pull-right">
     <div class="zoom"><a href="#"><span class="icon icon-full-screen-selector"></span> Xem rộng hơn</a></div>
     <div class="popup-close"><span class="icon icon-cancel-music"></span></div>
   </div>
  </div>
  <div class="popup-body">
    <div class="slider taste-detail">
      <div class="row">
        <div class="col-md-7">
            <div id="order-royalSlider" class="royalSlider rsDefault">
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
              <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
            </div>
          <!--<img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />-->
        </div>
        <div class="col-md-5">
          <div class="description">
             <h2>L'angfarm Buffet - Đặc Sản Đà Lạt</h2>
             <p class="expt">Sinh viên, Nhóm hội, Giới văn phòng</p>
             <div class="address">
               
             </div>
             <div class="item taste-description">
               <p><span class="icon icon-location-arrow"></span> 419/27 Cách Mạng Tháng 8, P. 13, Quận 10, TP. HCM</p>
               <p><span class="icon icon-clock-o"></span> <strong class="time-open">Đang mở cửa</strong> 08:00 AM - 10:30 PM</p>
               <p><span class="icon icon-tag"></span> 10.000đ - 35.000đ</p>
               <p><span class="icon icon-phone"></span> Hỗ trợ đặt hàng: <strong>09 6666 0127</strong></p>
             </div>
             <div class="item">
               <div class="quanlity">
                 Số lượng: <input type="number" name="quanlity">
               </div>
               <div class="payment">
                 <a href="#" class="pull-right">Mua ngay</a>
               </div>
             </div>
             <div class="item">
               <p class="count-user-payment"><span class="icon icon-user-profile"></span>102 người đã mua</p>
               <p class="time">19 Ngày 04 : 36 : 09</p>
             </div>
             <div class="item">
               <p>Giao hàng miễn phí tại TP.HCM</p>
             </div>
          </div>
        </div>
      </div>
   </div>

    <div class="commitment">
      <div class="commitment-view">
        <div class="content">
          <div class="col-md-7">
           <h2>Giới thiệu</h2>
           <p>- Tour Campuchia – Lào – Đông Bắc Thái Lan trong 4N3Đ do Viet Kite Travel – đơn vị lữ hành giàu kinh nghiệm 
             đứng ra tổ chức.</p><p>
  - Tham gia vào chuyến hành trình, bạn sẽ được đặt chân đến nhiều địa danh khác nhau: Strung Treng 
  (Campuchia), Pakse (Lào), Ubon Ratchathani (Thái Lan).</p><p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
           <p>- Tour Campuchia – Lào – Đông Bắc Thái Lan trong 4N3Đ do Viet Kite Travel – đơn vị lữ hành giàu kinh nghiệm 
             đứng ra tổ chức.</p><p>
  - Tham gia vào chuyến hành trình, bạn sẽ được đặt chân đến nhiều địa danh khác nhau: Strung Treng 
  (Campuchia), Pakse (Lào), Ubon Ratchathani (Thái Lan).</p><p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
         </div>
         <div class="col-md-5">
           <h2 class="map-title">Địa điểm sử dụng</h2>
           <div id="map-current">
             
           </div>
         </div>
        </div>
      </div>
      <div class="col-md-12 readmove">
        <a href="#"><span class="text">Xem thêm</span> <span class="icon icon-angle-down"></span></a>
      </div>
      <script>
        jQuery(document).ready(function($){
          $(".readmove a").on('click', function(){
            if($(this).hasClass('up')){
               $(".commitment .commitment-view .content").removeClass('expanded');
               $(".readmove a span.text").empty().append('Xem thêm');
               $(this).removeClass('up');
            }else{
               $(".commitment .commitment-view .content").addClass('expanded');
               $(".readmove a span.text").empty().append('Thu gọn');
               $(this).addClass('up');
            }

          });
        });
      </script>
    </div>

   <div class="content-page-popup">
     <div class="row">
       <div class="col-md-9 about">
         <div class="tab-title">
           <ul>
             <li class="active"><a href="javascript:void(0)" id="tab-comment">Hình ảnh / Video</a></li>
             <li><a href="#">Thực đơn</a></li>
             <li><a href="javascript:void(0)" id="tab-comment">Bình luận (542)</a></li>
           </ul>
         </div>
         <div class="detail">
           <div class="gallery">
             <ul class="row">
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
               <li class="col-md-2"><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>"></li>
             </ul>
           </div>
           <div class="menu-order">
             <h2>Cháo</h2>
             <ul>
               <li>
                 <div class="item">
                   <img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                   <p>
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var>
                   </p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
             </ul>
             
             
             <h2>Trà - Cafe</h2>
             <ul>
               <li>
                 <div class="item">
                   <img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                   <p>
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var>
                   </p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
               <li>
                 <div class="item">
                   <p><img src="<?php echo $this->basePath('/assets/taste.jpg') ?>">
                     <span>Cháo ếch Singapore</span> 
                     <var class="pull-right">150.000vnđ</var></p>
                 </div>
               </li>
             </ul>
             
             
           </div>
           <div  class="payment-now">
             <a href="#">Menu tại quán</a>
           </div>
         </div>

         <div class="comment" id="detail-comment">
           <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
           <ul class="list-comment">
             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

           </ul>
           <div class="views-all">
             <a>Xem thêm</a>
           </div>
         </div>

       </div>
       <div class="col-md-3">
         <div class="list-related">
           <h2>Quán cùng loại</h2>
           <ul class="row list-item">
             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>
             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>


           </ul>
         </div>

       </div>
     </div>
   </div>
  </div>
  </div>

  <div class="poup-footer">
  <div class="row">
   <div class="col-md-4">
     <h2>Công ty TNHH Smart Connector</h2>
     <ul>
       <li>294 Hòa bình, P. Hiệp Tân, Q. Tân Phú, TP.HCM</li>
       <li>ĐT: 08.73055707 - Fax: 08.38666237</li>
       <li><a href="#">sales@abc.vn</a></li>
       <li>Mã số thuế: 0310955176 do Sở Kế hoạch đầu tư TP HCM 
  cấp ngày 29/06/2011</li>
     </ul>
   </div>
   <div class="col-md-2">
     <h2>Về chúng tôi</h2>
     <ul>
       <li><a href="#">Giới thiệu</a></li>
       <li><a href="#">Quy định</a></li>
       <li><a href="#">Trợ giúp</a></li>
       <li><a href="#">Đăng ký quảng cáo</a></li>
       <li><a href="#">Liên hệ</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chăm sóc khách hàng</h2>
     <ul class="support-footer">
       <li><span class="hotline">HOTLINE</span> <span class="hotline-phone">08 7300 5757</span></li>
       <li><a href="#">Chính sách giao hàng</a></li>
       <li><a href="#">Chính sách đổi sản phẩm</a></li>
       <li><a href="#">Chính sách bảo mật</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chứng nhận</h2>
     <ul>
       <li><img src="/tours/public/frontend/images/bocongthuong.png"></li>
     </ul>
     <h2>Liên kết</h2>
     <ul class="connect">
       <li class="facebook"><a href="#"><span class="icon icon-facebook"></span></a></li>
       <li class="twitter"><a href="#"><span class="icon icon-twitter"></span></a></li>
       <li class="youtube"><a href="#"><span class="icon icon-youtube"></span></a></li>
       <li class="googleplus"><a href="#"><span class="icon icon-googleplus"></span></a></li>
       <li class="linkedin"><a href="#"><span class="icon icon-linkedin"></span></a></li>
       <li class="pinterest"><a href="#"><span class="icon icon-pinterest"></span></a></li>
     </ul>
   </div>
  </div>
  </div>

  <div class="coppyright">
  <div class="row">
    <div class="col-md-12">
       <p>Coppyright © 2015 Long.pham. All Rights Reserved</p>
     </div>
  </div>
  </div>