<div class="search">
  <div class="page-search">
    <div class="search-item">
      <div class="search-list">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="list-search">
                <div class="row">
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">-- Quốc gia -- </option>
                      <option value="">Việt Nam</option>
                      <option value="">Thái Lan</option>
                      <option>Ấn Độ</option>
                      <option>Mỹ</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker">
                      <option value="">-- Tỉnh/Thành Phố -- </option>
                      <option>Bình Phước</option>
                      <option>Hà Nội</option>
                      <option>Hải Dương</option>
                      <option>Bình Định</option>
                      <option>Quản Trị</option>
                      <option>Quảng Nam</option>
                      <option>Huế</option>
                      <option>Đà Nẵng</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">-- Loại -- </option>
                      <option value="">Trà sữa</option>
                      <option value="">Quán ăn</option>
                      <option>Quán nhậu</option>
                      <option>Tiệm bánh</option>
                      <option>Nhà hàng</option>
                      <option>Ăn vặt/vỉa hè</option>
                      <option>Ăn chay</option>
                      <option>Cafe</option>
                      <option>Kem</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> Điểm ăn uống</h1>
    </div>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="list-cat">
        <div class="filter">
          <ul>
            <li><a href="#">Mới khai trương <span class="icon icon-down-thin"></span></a></li>
            <li><a href="#">Nổi bật <span class="icon icon-up-thin"></span></a></li>
            <li><a href="#">Giá <span class="icon icon-up-thin"></span></a></li>
            <li><a href="#">Khuyến mãi <span class="icon icon-up-thin"></span></a></li>
          </ul>
        </div>
        <ul class="row list-item">
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>Mới</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
                </div>
                <div class="address">
                  771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
                </div>

                <div class="view-user">
                  <span class="sale">-50%</span>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>Mới</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
                </div>
                <div class="address">
                  771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
                </div>

                <div class="view-user">
                  <span class="sale">-50%</span>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>Mới</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
                </div>
                <div class="address">
                  771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
                </div>

                <div class="view-user">
                  <span class="sale">-50%</span>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>Mới</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
                </div>
                <div class="address">
                  771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
                </div>

                <div class="view-user">
                  <span class="sale">-50%</span>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>Mới</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
                </div>
                <div class="address">
                  771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
                </div>

                <div class="view-user">
                  <span class="sale">-50%</span>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="highlight"><span>Mới</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
                </div>
                <div class="address">
                  771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
                </div>

                <div class="view-user">
                  <span class="sale">-50%</span>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>

        </ul>
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content">
    <div style="width: 100%; height: 100%;" id="map"></div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
<div class="views-popup">
  <div class="views-container">
    
  </div>
</div>
     
<div class="popup-page">
  <div class="popup-container tour">
    
  </div>
</div>
     
<script>
  jQuery(document).ready(function($){
    $(".list-cat .list-item li").on('click','a',function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/taste/detail';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".popup-page").addClass('on');
            $(".popup-page").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".popup-container").empty().append(data.html);
            // call map api
            var pyrmont = {lat: -33.867, lng: 151.195};

              map = new google.maps.Map(document.getElementById('map-current'), {
                center: pyrmont,
                zoom: 15
              });

              infowindow = new google.maps.InfoWindow();
              var service = new google.maps.places.PlacesService(map);
              service.nearbySearch({
                location: pyrmont,
                radius: 500,
                type: ['store']
              }, callback); 


            

            

            // call royalSlider
//            var slider = $('.royalSlider').royalSlider({
//            fullscreen: {
//              enabled: true,
//              nativeFS: true
//            },
//            controlNavigation: 'thumbnails',
//            autoScaleSlider: true, 
//            autoScaleSliderWidth: 1024,
//            autoScaleSliderHeight: 614,
//            loop: false,
//            imageScaleMode: 'none',
//            navigateByClick: true,
//            numImagesToPreload:2,
//            arrowsNav:true,
//            arrowsNavAutoHide: true,
//            arrowsNavHideOnTouch: true,
//            keyboardNavEnabled: true,
//            fadeinLoadedSlide: true,
//            globalCaption: true,
//            globalCaptionInside: false,
//            imageScalePadding: 0,
//            slidesSpacing: 0,
//            thumbs: {
//              appendSpan: true,
//              firstMargin: true,
//              paddingBottom: 4
//            }
//            }).data('royalSlider');
//
//            $('.rsFullscreenBtn').click(function(e){
//              slider.enterFullscreen();
//              e.preventDefault();
//            });
//
//            slider.ev.on("rsEnterFullscreen", function() {
//              // enter fullscreen mode 
//              $(".popup-page").css('position', 'relative');
//            });
//            slider.ev.on('rsExitFullscreen', function(event) {
//              // exit fullscreen mode
//              $(".popup-page").removeAttr('style');
//            });
            //hotel room hover
            $(".list-hotel-room ul > li").hover(
              function () {
                $(this).addClass('active');
              },
              function () {
                $(this).removeClass('active');
              }
            );
    
            // view room
//            $(".list-hotel-room ul li").on('click','.view-room-hotel', function(){
//              var current = $("#current-map").val();
//              var id = 'abc';
//              var url = 'http://localhost/tours/public/hotel/room';
//              $.ajax({
//                  url : url,
//                  type : 'POST',
//                  dataType : "json",
//                  data: {id: id},
//                  beforeSend: function(){
//                    $(".views-popup").addClass('view');
//                    $(".views-popup").append('<div class="loading"></div>');
//                  },
//                  success : function (data){
//                    $( ".loading" ).remove();
//                    $(".views-popup .views-container").empty().append(data.html);
//                    // call royalSlider
//                    var slider = $('.royalSlider').royalSlider({
//                    fullscreen: {
//                      enabled: true,
//                      nativeFS: true
//                    },
//                    controlNavigation: 'thumbnails',
//                    autoScaleSlider: true, 
//                    autoScaleSliderWidth: 1024,
//                    autoScaleSliderHeight: 614,
//                    loop: false,
//                    imageScaleMode: 'none',
//                    navigateByClick: true,
//                    numImagesToPreload:2,
//                    arrowsNav:true,
//                    arrowsNavAutoHide: true,
//                    arrowsNavHideOnTouch: true,
//                    keyboardNavEnabled: true,
//                    fadeinLoadedSlide: true,
//                    globalCaption: true,
//                    globalCaptionInside: false,
//                    imageScalePadding: 0,
//                    slidesSpacing: 0,
//                    thumbs: {
//                      appendSpan: true,
//                      firstMargin: true,
//                      paddingBottom: 4
//                    }
//                    }).data('royalSlider');
//
//                    $('.rsFullscreenBtn').click(function(e){
//                      slider.enterFullscreen();
//                      e.preventDefault();
//                    });
//
//                    slider.ev.on("rsEnterFullscreen", function() {
//                      // enter fullscreen mode 
//                      $(".popup-page").css('position', 'relative');
//                    });
//                    slider.ev.on('rsExitFullscreen', function(event) {
//                      // exit fullscreen mode
//                      $(".popup-page").removeAttr('style');
//                    });
//                    // view map popup
//                    $(".views-popup .views-container").addClass('open');
//                  }
//                });
//            });
            
            // close room
            $(".views-popup").on('click','.views-close' ,function(){
              $(".views-popup .views-container").removeClass('open');
              setTimeout(function () {
               $(".views-popup").removeClass('view');
               $(".views-popup .views-container").empty();
              }, 350);
            });
          }
        });
    });
    // close popup
    $(".popup-page").on('click','.popup-close' ,function(){
      $(".popup-page").removeClass('on');
      $(".popup-page .popup-container").empty();
    });
    
   
  });
</script>