<div class="views-header">
  <div class="row">
    <div class="col-md-10">
      <h2><span class="icon icon-location"></span> Khách sạn Hoàng Mai - Phòng 005</h2>
    </div>
    <div class="col-md-2">
      <div class="views-close pull-right">
        <span class="icon icon-cancel-music"></span>
      </div>
    </div>
  </div>
</div>
<div class="views-content room-detail">
  <div class="popup-body views-content-wp">
    <div class="slider">
      <div id="order-royalSlider" class="royalSlider rsDefault">
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
      </div>
    </div>
    
    <div class="utilities">
      <h2>TIỆN NGHI KHÁCH SẠN</h2>
      <ul>
        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Tắm hơp</p>
          </div>
        </li>
        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Dịch vụ dọn Phòng</p>
          </div>
        </li>
        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Cafe</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Gym</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Hồ bơi trong nhà</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Giặt ủi</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Dịch vụ phòng họp</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Dịch vụ phòng 24/24</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Nhà hàng</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Spa</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Wifi khu vực công cộng</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Thang máy</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Đưa đón sân bay</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Bàn làm việc</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Nhân viên vận chuyển</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Quán cafe</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Quầy bán Tour</p>
          </div>
        </li>


        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Lễ tân phục vụ 24 giờ</p>
          </div>
        </li>


        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Bãi đậu xe</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Bàn làm việc</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Buffet sáng</p>
          </div>
        </li>
      </ul>
    </div>
   
    <div class="utilities">
      <h2>Giá phòng</h2>
      <div class="row">
        <div class="col-md-6">
          <p><strong>Diện tích:</strong> 40m2</p>
          <p><strong>Ở tố đa: </strong> 2 người lớn, 1 trẻ em</p>
        </div>
        <div class="col-md-6">
          <div class="price">
            <p class="cost">Giá gốc: 400,000vnđ</p>
            <p class="price-sale">300.000vnđ</p>
            <p class="sale">-50%</p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="utilities">
      <h2>Đặt phòng</h2>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-5">
              <label for="start_date">Ngày nhận phòng</label>
              <div class="booking-hotel">
                <input type="text" class="form-control" id="start_date">
                <span class="icon icon-calendar"></span>
              </div>
            </div>
            <div class="col-md-5">
              <label for="end_date">Ngày trả phòng</label>
              <div class="booking-hotel">
                <input type="text" class="form-control" id="end_date">
                <span class="icon icon-calendar"></span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <a href="#" class="booking-now">Chọn Phòng này</a>
        </div>
      </div>
    </div>
    
</div>