<div id="search">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="search-home">
          <div class="list-tab">
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a href="#travel" aria-controls="travel" role="tab" data-toggle="tab">Tìm địa điểm phượt</a></li>
              <li role="presentation"><a href="#tour" aria-controls="tour" role="tab" data-toggle="tab">Tìm tour du lịch</a></li>
              <li role="presentation"><a href="#hotel" aria-controls="hotel" role="tab" data-toggle="tab">Tìm khách sạn</a></li>
              <li role="presentation"><a href="#food" aria-controls="food" role="tab" data-toggle="tab">Tìm điểm ăn uống</a></li>
            </ul>
          </div>
          <div class="panel-tab">
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="travel">
                <div class="row">
                  <div class="col-md-12">
                    <h2>Bạn muốn đi đâu?</h2>
                  </div>
                  <div class="col-md-12">
                    <div class="form">
                      <input type="text" class="form-control">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <select class="form-control">
                      <option> -- Quận/Huyện --</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <select class="form-control">
                      <option> -- Phường/Xã --</option>
                    </select>
                  </div>
                </div>
                
                
              </div>
              <div role="tabpanel" class="tab-pane" id="tour">
                
              </div>
              <div role="tabpanel" class="tab-pane" id="hotel">
                
              </div>
              <div role="tabpanel" class="tab-pane" id="food">
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>