<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuProfile(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Đổi mật khẩu</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2>Đổi mật khẩu</h2>
                  <div class="view-order">
                    <div class="row">
                      <div class="col-md-7">
                        <div class="user-profile">
                          <div class="form-group">
                            <label for="email">Mật khẩu hiện tại</label>
                            <div class="form-input">
                              <input type="password" class="form-control" id="email" placeholder="Mật khẩu hiện tại">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <label for="email">Mật khẩu mới</label>
                            <div class="form-input">
                              <input type="password" class="form-control" id="fullname" placeholder="******">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <label for="email">Nhập lại mật khẩu mới</label>
                            <div class="form-input">
                              <input type="password" class="form-control" id="phone" placeholder="******">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          
                          
                          <div class="form-group">
                            <div class="form-input">
                              <button type="submit" class="btn btn-default  ">Đổi mật khẩu</button>
                            </div>
                          </div>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>