<div class="user">
  <div class="timeline">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="about">
            <h2>Giới thiệu</h2>
            <div class="instroduction">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla dolorem corporis neque reprehenderit dolorum alias placeat, perferendis eveniet totam repellendus maiores nisi facilis fuga voluptas. Illum nobis, aliquid consequuntur nesciunt!
              </p>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla dolorem corporis neque reprehenderit dolorum alias placeat, perferendis eveniet totam repellendus maiores nisi facilis fuga voluptas. Illum nobis, aliquid consequuntur nesciunt!
              </p>
            </div>
            <ul>
              <li><strong>Ngày tham gia:</strong> 12/08/2016</li>
              <li><strong>Địa chỉ: </strong>40 Bãi sậy .P 13, Quận 5, TP. Hồ Chí Minh</li>
              <li><strong>Điện thoại: </strong>0966660127</li>
              <li><strong>Fax: </strong>0966660127</li>
              <li><strong>Email: </strong>vanlong200880@gmail.com</li>
              <li><strong>Website: </strong>http://www.unimedia.vn</li>
              <li><a href="#">Xem bản đồ</a></li>
            </ul>
          </div>
          
          <div class="photos">
            <h2>Photos</h2>
            <ul class="row list-album-profile">
              <li class="col-md-6">
                <div class="item">
                  <div class="img">
                    <img src="/tours/public/assets/demo/deal.jpg">
                  </div>
                  <div class="album-title">
                    <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                    <p class="total-photos">3 photos</p>
                  </div>
                </div>
              </li>
              <li class="col-md-6">
                <div class="item">
                  <div class="img">
                    <img src="/tours/public/assets/demo/deal.jpg">
                  </div>
                  <div class="album-title">
                    <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                    <p class="total-photos">3 photos</p>
                  </div>
                </div>
              </li>
              <li class="col-md-6">
                <div class="item">
                  <div class="img">
                    <img src="/tours/public/assets/demo/deal.jpg">
                  </div>
                  <div class="album-title">
                    <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                    <p class="total-photos">3 photos</p>
                  </div>
                </div>
              </li>
              <li class="col-md-6">
                <div class="item">
                  <div class="img">
                    <img src="/tours/public/assets/demo/deal.jpg">
                  </div>
                  <div class="album-title">
                    <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                    <p class="total-photos">3 photos</p>
                  </div>
                </div>
              </li>
              <li class="col-md-6">
                <div class="item">
                  <div class="img">
                    <img src="/tours/public/assets/demo/deal.jpg">
                  </div>
                  <div class="album-title">
                    <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                    <p class="total-photos">3 photos</p>
                  </div>
                </div>
              </li>
              <li class="col-md-6">
                <div class="item">
                  <div class="img">
                    <img src="/tours/public/assets/demo/deal.jpg">
                  </div>
                  <div class="album-title">
                    <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                    <p class="total-photos">3 photos</p>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          
          <div class="blog">
            <h2>Blog</h2>
            <ul>
              <li>
                <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                <p class="title"><a href="#"><strong>Du lịch Tiền Giang ngày hè</strong></a></p>
                <p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</p>
              </li>
              <li>
                <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                <p class="title"><a href="#"><strong>Du lịch Tiền Giang ngày hè</strong></a></p>
                <p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</p>
              </li>
              <li>
                <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                <p class="title"><a href="#"><strong>Du lịch Tiền Giang ngày hè</strong></a></p>
                <p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua.</p>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-8">
          <div class="content">
            <h2>Khuyến mãi mới nhất</h2>
            <div class="timeline-block">
              <ul class="row list-item">
                <li class="col-md-4">
                  <div class="item">
                    <div class="img">
                      <div class="highlight"><span>HOT</span></div>
                      <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                      <div class="item-hover">
                        <div class="item-voucher">
                          Nhân voucher điện tử qua email/SMS
                        </div>
                        <div class="readmove">
                          <a href="#">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                    <div class="item-content">
                      <div class="title">
                        <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                      </div>
                      <div class="price">
                        <p>
                          <span class="cost">350,000 <var>đ</var></span>
                          <span class="sale">-50%</span>
                        </p>
                      </div>
                      <div class="view-user">
                        <span class="price-sale">350,000</span>  <var>đ</var>
                        <div class="pull-right">
                          <span class="icon icon-user-profile"> 1124</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="col-md-4">
                  <div class="item">
                    <div class="img">
                      <div class="highlight"><span>HOT</span></div>
                      <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                      <div class="item-hover">
                        <div class="item-voucher">
                          Nhân voucher điện tử qua email/SMS
                        </div>
                        <div class="readmove">
                          <a href="#">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                    <div class="item-content">
                      <div class="title">
                        <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                      </div>
                      <div class="price">
                        <p>
                          <span class="cost">350,000 <var>đ</var></span>
                          <span class="sale">-50%</span>
                        </p>
                      </div>
                      <div class="view-user">
                        <span class="price-sale">350,000</span>  <var>đ</var>
                        <div class="pull-right">
                          <span class="icon icon-user-profile"> 1124</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="col-md-4">
                  <div class="item">
                    <div class="img">
                      <div class="highlight"><span>HOT</span></div>
                      <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                      <div class="item-hover">
                        <div class="item-voucher">
                          Nhân voucher điện tử qua email/SMS
                        </div>
                        <div class="readmove">
                          <a href="#">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                    <div class="item-content">
                      <div class="title">
                        <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                      </div>
                      <div class="price">
                        <p>
                          <span class="cost">350,000 <var>đ</var></span>
                          <span class="sale">-50%</span>
                        </p>
                      </div>
                      <div class="view-user">
                        <span class="price-sale">350,000</span>  <var>đ</var>
                        <div class="pull-right">
                          <span class="icon icon-user-profile"> 1124</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="col-md-4">
                  <div class="item">
                    <div class="img">
                      <div class="highlight"><span>HOT</span></div>
                      <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                      <div class="item-hover">
                        <div class="item-voucher">
                          Nhân voucher điện tử qua email/SMS
                        </div>
                        <div class="readmove">
                          <a href="#">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                    <div class="item-content">
                      <div class="title">
                        <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                      </div>
                      <div class="price">
                        <p>
                          <span class="cost">350,000 <var>đ</var></span>
                          <span class="sale">-50%</span>
                        </p>
                      </div>
                      <div class="view-user">
                        <span class="price-sale">350,000</span>  <var>đ</var>
                        <div class="pull-right">
                          <span class="icon icon-user-profile"> 1124</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="col-md-4">
                  <div class="item">
                    <div class="img">
                      <div class="highlight"><span>HOT</span></div>
                      <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                      <div class="item-hover">
                        <div class="item-voucher">
                          Nhân voucher điện tử qua email/SMS
                        </div>
                        <div class="readmove">
                          <a href="#">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                    <div class="item-content">
                      <div class="title">
                        <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                      </div>
                      <div class="price">
                        <p>
                          <span class="cost">350,000 <var>đ</var></span>
                          <span class="sale">-50%</span>
                        </p>
                      </div>
                      <div class="view-user">
                        <span class="price-sale">350,000</span>  <var>đ</var>
                        <div class="pull-right">
                          <span class="icon icon-user-profile"> 1124</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="col-md-4">
                  <div class="item">
                    <div class="img">
                      <div class="highlight"><span>HOT</span></div>
                      <a href="#"><img src="/tours/public/assets/demo/deal.jpg"></a>
                      <div class="item-hover">
                        <div class="item-voucher">
                          Nhân voucher điện tử qua email/SMS
                        </div>
                        <div class="readmove">
                          <a href="#">Xem ngay</a>
                        </div>
                      </div>
                    </div>
                    <div class="item-content">
                      <div class="title">
                        <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                      </div>
                      <div class="price">
                        <p>
                          <span class="cost">350,000 <var>đ</var></span>
                          <span class="sale">-50%</span>
                        </p>
                      </div>
                      <div class="view-user">
                        <span class="price-sale">350,000</span>  <var>đ</var>
                        <div class="pull-right">
                          <span class="icon icon-user-profile"> 1124</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          
          
          
          
          <div class="content">
            <h2><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành</a> </h2>
            <div class="timeline-block-item">
              <p><img src="<?php echo $this->basePath('/assets/bug.png') ?>"></p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="comment" id="detail-comment">
              <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
              <ul class="list-comment">
                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

              </ul>
              <div class="views-all">
                <a>Xem thêm</a>
              </div>
            </div>
          </div>
          
          
          <div class="content">
            <h2><a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành</a> </h2>
            <div class="timeline-block-item">
              <p><img src="<?php echo $this->basePath('/assets/bug.png') ?>"></p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="comment" id="detail-comment">
              <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
              <ul class="list-comment">
                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

                <li>
                  <div class="comment-item">
                    <div class="avartar">
                       <img src="/tours/public/assets/demo/photo.jpg">
                    </div>
                    <div class="comment-content">
                      <div class="comment-info">
                        <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        <div class="list-gallery">
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                          <a href="#">
                            <img src="/tours/public/assets/demo/photo.jpg">
                          </a>
                        </div>
                        <div class="form-replies">
                          <a class="fs-comment">
                            Trả lời
                          </a>
                          <a class="fs-like">
                            Thích (10)
                          </a>
                          <a class="fs-share">
                            Chia sẻ
                          </a>
                        </div>
                      </div>
                      <div class="comment-replies">
                        <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                        <div class="comment-content">
                          <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>

              </ul>
              <div class="views-all">
                <a>Xem thêm</a>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>