<div class="user">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="banner-profile">
          <img src="<?php echo $this->basePath('/assets/demo/slider.png'); ?>">
          <div class="menu-profile-top">
            <ul class="pull-right">
              <li>
                <a href="#">Timeline</a>
              </li>
              <li>
                <a href="#">Thông tin tài khoản</a>
              </li>
              <li>
                <a href="#">Photos</a>
              </li>
              <li>
                <a href="#">Quản lý</a>
                <ul>
                  <li>
                    <a href="#">E-Voucher</a>
                  </li>
                  <li>
                    <a href="#">Đăng tin</a>
                  </li>
                  <li>
                    <a href="#">Khách sạn</a>
                  </li>
                  <li>
                    <a href="#">Tours</a>
                  </li>
                  <li>
                    <a href="#">Điểm ăn uống</a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="#">Điểm tích lũy</a>
              </li>
              <li>
                <a href="#">Đơn hàng</a>
              </li>
              <li>
                <a href="#">Cài đặt</a>
              </li>
            </ul>
          </div>
          <div class="profile-pic">
            <img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>">
          </div>
        </div>
      </div>
      <div class="col-md-4">
        
      </div>
    </div>
  </div>
</div>