<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuProfile(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Đơn hàng của tôi</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <div class="list-tours">
                    <table class="list-table">
                      <thead>
                        <tr>
                          <th>Mã đơn hàng</th>
                          <th>Ngày mua</th>
                          <th>Sản phẩm</th>
                          <th>Tổng tiền</th>
                          <th>Trạng thái</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        <tr>
                          <td class="order-id"><a href="<?php echo $this->url('user/user-order-view', array('orderId' => '1231313')) ?>">1231315</a></td>
                          <td>20-08-2016</td>
                          <td>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</td>
                          <td>10,500,000 vnđ</td>
                          <td>Đã thanh toán</td>
                        </tr>
                        
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>