<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <ul>
                <li>
                  <a href="#"><span></span>Quản lý</a>
                </li>
                <li>
                  <a href="#"><span></span>Đăng tin</a>
                </li>
                
                <li>
                  <a href="#"><span></span>E-Voucher</a>
                </li>
                <li>
                  <a href="#"><span></span>Tours</a>
                </li>
                <li>
                  <a href="#"><span></span>Điểm ăn uống</a>
                </li>
                <li>
                  <a href="#"><span></span>Khách sạn</a>
                </li>
                
              </ul>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Tour</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Đăng tour</h2>
                  <div class="page">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Tiêu đề</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Mô tả ngắn</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giá</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giảm giá</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ngày bắt đầu</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ngày kết thúc</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ảnh đại điện</label>
                          <input type="file">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1"> Gallery </label>
                          <input type="file">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Địa chỉ</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Điện thoại Hotline</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Điểm nổi bật</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Cam kết</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Nội dung</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="post-list-tour">
                          <h2>Các địa điểm đi trong tour này</h2>
                          <div class="row">
                            <div class="col-md-3">
                              tìm
                            </div>
                            <div class="col-md-3">
                              <select class="form-control">
                                <option>Quốc Gia</option>
                              </select>
                            </div>
                            <div class="col-md-3">
                              <select class="form-control">
                                <option>Tỉnh/Thành Phố</option>
                              </select>
                            </div>
                            <div class="col-md-3">
                              <select class="form-control">
                                <option>Quận/Huyện</option>
                              </select>
                            </div>
                          </div>
                          <ul class="row">
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                              <li class="col-md-2">
                                <div class="item">
                                  <div class="img">
                                    <div class="item-checked">
                                      <input type="checkbox" name="">
                                    </div>
                                    <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                                  </div>
                                  <div class="album-title">
                                    <p>Khu du lịch bọ cạp vàng</p>
                                  </div>
                                </div>
                              </li>
                            </ul>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Đăng</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>