<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <ul>
                <li>
                  <a href="#"><span></span>Quản lý</a>
                </li>
                <li>
                  <a href="#"><span></span>Đăng tin</a>
                </li>
                
                <li>
                  <a href="#"><span></span>E-Voucher</a>
                </li>
                <li>
                  <a href="#"><span></span>Tours</a>
                </li>
                <li>
                  <a href="#"><span></span>Điểm ăn uống</a>
                </li>
                <li>
                  <a href="#"><span></span>Khách sạn</a>
                </li>
                
              </ul>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Home</li>
                  <li>Facebook</li>
                  <li class="active">Bot Like</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Du lịch</h2>
                  <div class="page">
                    fgdfgdfgd
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>