<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuProfile(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Thông tin tài khoản</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2>Thông tin tài khoản</h2>
                  <div class="view-order">
                    <div class="row">
                      <div class="col-md-7">
                        <div class="user-profile">
                          <div class="form-group">
                            <label for="email">Email</label>
                            <div class="form-input">
                              <input type="text" class="form-control" id="email" placeholder="Email">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <label for="email">Họ và tên</label>
                            <div class="form-input">
                              <input type="text" class="form-control" id="fullname" placeholder="Họ và tên">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <label for="email">Điện thoại</label>
                            <div class="form-input">
                              <input type="text" class="form-control" id="phone" placeholder="Điện thoại">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <label for="email">Địa chỉ</label>
                            <div class="form-input">
                              <input type="text" class="form-control" id="phone" placeholder="Địa chỉ">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="email">Ngày sinh</label>
                            <div class="form-input">
                              <input type="text" class="form-control" id="phone" placeholder="Ngày sinh">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="email">Giới tính</label>
                            <div class="form-input">
                              <input type="text" class="form-control" id="phone" placeholder="Địa chỉ">
                              <span class="icon icon-man-people-streamline-user"></span>
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <label for="email">Giới thiệu</label>
                            <div class="form-input">
                              <textarea class="form-control"></textarea>
                              
                            </div>
                          </div>
                          
                          <div class="form-group">
                            <div class="form-input">
                              <button type="submit" class="btn btn-default  ">Cập nhật</button>
                            </div>
                          </div>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>