<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuProfile(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Đơn hàng của tôi</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2>Đơn hàng #74727223 - Đã hủy - Ngày đặt hàng: 2016-01-21 09:23:15</h2>
                  <div class="view-order">
                    <div class="row">
                      <div class="col-md-12">
                        <ul>
                          <li><h3>Địa chỉ người nhận</h3></li>
                          <li>Phạm Văn Long</li>
                          <li>14, Phường 10, Quận 11, Hồ Chí Minh, Việt Nam</li>
                          <li>ĐT: 0986456248</li>
                        </ul>
                      </div>
                      <div class="col-md-6">
                        <ul>
                          <li><h3>Phương thức vận chuyển</h3></li>
                          <li>Vận chuyển Tiết Kiệm (dự kiến giao hàng vào Thứ hai, 25/01/2016 - Thứ ba, 26/01/2016)</li>
                          <li>Miễn phí vận chuyển</li>
                        </ul>
                      </div>
                      <div class="col-md-6">
                        <ul>
                          <li><h3>Phương thức thanh toán</h3></li>
                          <li>Thẻ ATM đăng ký Internet Banking (Miễn phí thanh toán)</li>
                          <li><span>Giao dịch đang chờ xử lý ở ngân hàng</span></li>
                        </ul>
                      </div>
                      
                      <div class="col-md-12">
                        <h3>Sản phẩm đã mua</h3>
                        <table class="table-order-detail">
                          <thead>
                            <tr>
                              <th class="sku">SKU</th>
                              <th>Tên sản phẩm</th>
                              <th>Giá</th>
                              <th>Số lượng</th>
                              <th>Giảm giá</th>
                              <th>Tổng cộng</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>6003565753972</td>
                              <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                              <td>10.400.000 ₫</td>
                              <td>1</td>
                              <td>5%</td>
                              <td>10.400.000 ₫</td>
                            </tr>
                            <tr>
                              <td>6003565753972</td>
                              <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                              <td>10.400.000 ₫</td>
                              <td>1</td>
                              <td>5%</td>
                              <td>10.400.000 ₫</td>
                            </tr>
                            <tr>
                              <td>6003565753972</td>
                              <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                              <td>10.400.000 ₫</td>
                              <td>1</td>
                              <td>5%</td>
                              <td>10.400.000 ₫</td>
                            </tr>
                            <tr>
                              <td>6003565753972</td>
                              <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                              <td>10.400.000 ₫</td>
                              <td>1</td>
                              <td>5%</td>
                              <td>10.400.000 ₫</td>
                            </tr>
                            
                          </tbody>
                          <tfoot>
                            <tr>
                              <td colspan="5" class="summary"><strong>Tổng chưa giảm</strong></td>
                              <td class="summary-price"><strong>10.915.000 ₫</strong></td>
                            </tr>
                            <tr>
                              <td colspan="5" class="summary"><strong>Giảm giá</strong></td>
                              <td class="summary-price"><strong>-515.000 ₫</strong></td>
                            </tr>
                            <tr>
                              <td colspan="5" class="summary"><strong>Chi phí vận chuyển</strong></td>
                              <td class="summary-price"><strong>0 ₫</strong></td>
                            </tr>
                            <tr>
                              <td colspan="5" class="summary"><strong>Tổng cộng</strong></td>
                              <td class="summary-price"><strong>10.400.000 ₫</strong></td>
                            </tr>
                          </tfoot>
                        </table>
                      </div>
                      
                      <div class="col-md-12">
                        <a href="#" class="back pull-left">Trở về danh sách đơn hàng</a>
                        <a href="#" class="print pull-right">In đơn hàng</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>