<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('frontend/css/login.css'))
            ->prependStylesheet($this->basePath('frontend/css/fonts.css'))
                        ->prependStylesheet($this->basePath('frontend/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('frontend/js/bootstrap.min.js'))
            ->prependFile($this->basePath('frontend/js/jquery.min.js'))
            ->prependFile($this->basePath('frontend/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('frontend/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
      <div class="header">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <header class="menu-header">
                <div class="row">
                  <div class="col-md-2">
                    <a class="logo" href="<?php echo $this->url('home'); ?>">
                      <img src="<?php echo $this->basePath('/assets/logo.png'); ?>">
                    </a>
                  </div>
                  <div class="col-md-10">
                    <ul id="menu-top" class="pull-left">
                      <li>
                        <a href="<?php echo $this->url('travel'); ?>">Địa điểm phượt</a>
                      </li>
                      <li>
                        <a href="<?php echo $this->url('tour'); ?>">Tìm tours</a>
                      </li>
                      <li>
                        <a href="<?php echo $this->url('hotel'); ?>">Khách sạn</a>
                      </li>
                      <li>
                        <a href="<?php echo $this->url('taste'); ?>">Điểm ăn uống</a>
                      </li>
                      <li>
                        <a href="<?php echo $this->url('diary'); ?>">Nhật ký</a>
                      </li>
                      <li>
                        <a href="<?php echo $this->url('video'); ?>">Video</a>
                      </li>
                    </ul>
                    <ul class="pull-right">
                      <li class="login">
                        <a href="<?php echo $this->url('register'); ?>">Đăng ký</a>/
                        <a href="<?php echo $this->url('login'); ?>">Đăng nhập</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </header>
            </div>
          </div>
        </div>
        
      </div>
      
      <div class="body">
          <?php echo $this->content; ?>
      </div>
      <?php $this->footer(); ?>
      <?php echo $this->inlineScript(); ?>
    </body>
</html>
