<div class="search-item">
  <div class="search-list">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="list-search">
            <div class="row">
              <div class="col-md-3">
                <input type="text" class="form-control" name="tasteKeyword" id="tasteKeyword" placeholder="Từ khóa">
              </div>
              <div class="col-md-2">
                <select class="form-control selectpicker" data-live-search="true">
                  <option value="">Quốc Gia</option>
                  <option value="">Việt Nam</option>
                  <option value="">Thái Lan</option>
                  <option>Ấn Độ</option>
                  <option>Mỹ</option>
                </select>
              </div>
              <div class="col-md-2">
                <select class="form-control selectpicker">
                  <option value="">Tỉnh/Thành Phố</option>
                  <option>Bình Phước</option>
                  <option>Hà Nội</option>
                  <option>Hải Dương</option>
                  <option>Bình Định</option>
                  <option>Quản Trị</option>
                  <option>Quảng Nam</option>
                  <option>Huế</option>
                  <option>Đà Nẵng</option>
                </select>
              </div>
              <div class="col-md-2">
                <select class="form-control selectpicker">
                  <option value="">Quận/Huyện</option>
                  <option>Quận 1</option>
                </select>
              </div>
              <div class="col-md-1">
                <button class="button-search pull-right" id="tour-search-button">Tìm</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>