<ul>
  <li>
    <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>"><span></span>Quản lý tours</a>
  </li>
  <li class="active">
    <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>"><span class="icon icon-menu"></span>Danh sách tour</a>
  </li>
  <li>
    <a href="<?php echo $this->url('user/post', array('controller' => 'tours', 'action' => 'post')) ?>"><span class="icon icon-file-add"></span>Tạo tour</a>
  </li>
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>"><span></span>Đơn hàng</a>
  </li>

  <li>
    <a href="#"><span class="icon icon-help-circled"></span>Trợ giúp</a>
  </li>
</ul>