<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headTitle('Điểm đi chơi')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta(); ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('frontend/css/travel.css'))
            ->prependStylesheet($this->basePath('frontend/css/fonts.css'))
            ->prependStylesheet($this->basePath('frontend/libs/royalSlider/skins/default/rs-default.css'))
            ->prependStylesheet($this->basePath('frontend/libs/royalSlider/royalslider.css'))
            ->prependStylesheet($this->basePath('frontend/libs/Swiper/dist/css/swiper.min.css'))
            ->prependStylesheet($this->basePath('libs/bootstrapSelect/css/bootstrap-select.min.css'))
            ->prependStylesheet($this->basePath('frontend/css/bootstrap.min.css')) ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('libs/bootstrapSelect/js/bootstrap-select.min.js'))
            ->prependFile($this->basePath('frontend/libs/royalSlider/jquery.royalslider.min.js'))
            ->prependFile($this->basePath('frontend/js/bootstrap.min.js'))
            ->prependFile($this->basePath('frontend/js/jquery.min.js'))
            ->prependFile($this->basePath('frontend/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('frontend/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <script src="http://content.jwplatform.com/libraries/uxA8ETX2.js"></script>
    </head>
    <body>
      <div class="wrapper">
        <?php $this->headerCategory(); ?>
        <?php echo $this->searchCategory(); ?>
        <div id="container">
          <div  class="view">
            <div id="view-data" class="view-data">
              <?php echo $this->content; ?>
            </div>
            <?php //echo $this->content; ?>
            <div class="view-loading">
              <div class="loading"></div>
            </div>
          </div>
          <div class="map-content">
            <div style="width: 100%; height: 100%;" id="map"></div>
            <div class="shoppingcart">
              <?php $this->cart() ?>
            </div>
          </div>
        </div>
        <script>
              var map;
              var infowindow;

              function initMap() {
                var pyrmont = {lat: 16.1724728, lng: 107.182617};

                map = new google.maps.Map(document.getElementById('map'), {
                  center: pyrmont,
                  zoom: 6
                });

                infowindow = new google.maps.InfoWindow();
                var service = new google.maps.places.PlacesService(map);
                service.nearbySearch({
                  location: pyrmont,
                  radius: 500,
                  type: ['store']
                }, callback);
              }

              function callback(results, status) {
                if (status === google.maps.places.PlacesServiceStatus.OK) {
                  for (var i = 0; i < results.length; i++) {
                    createMarker(results[i]);
                  }
                }
              }

              function createMarker(place) {
                var placeLoc = place.geometry.location;
                var marker = new google.maps.Marker({
                  map: map,
                  position: place.geometry.location
                });

                google.maps.event.addListener(marker, 'click', function() {
                  infowindow.setContent(place.name);
                  infowindow.open(map, this);
                });
              }


            </script>
             <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
            <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>-->
        <script>
          jQuery(document).ready(function($){
            $("#view-data").on('click','.province-container ul.list-travel li .item a',function(){
              var id = 'abc';
              var url = 'http://localhost/tours/public/travel-view';
              $.ajax({
                  url : url,
                  type : 'POST',
                  dataType : "json",
                  data: {id: id},
                  beforeSend: function(){
                    $(".popup-page").addClass('on');
                    $(".popup-page").append('<div class="loading"></div>');
                  },
                  success : function (data){
                    $( ".loading" ).remove();
                    $(".popup-container").empty().append(data.html);
                    $("#page-comment").empty().append(data.htmlComment);

                    // call royalSlider
                    var slider = $('.royalSlider').royalSlider({
                    fullscreen: {
                      enabled: true,
                      nativeFS: true
                    },
                    controlNavigation: 'thumbnails',
                    autoScaleSlider: true, 
                    autoScaleSliderWidth: 725,
                    autoScaleSliderHeight: 478,
                    loop: false,
                    imageScaleMode: 'none',
                    navigateByClick: true,
                    numImagesToPreload:2,
                    arrowsNav:true,
                    arrowsNavAutoHide: true,
                    arrowsNavHideOnTouch: true,
                    keyboardNavEnabled: true,
                    fadeinLoadedSlide: true,
                    globalCaption: false,
                    globalCaptionInside: false,
                    imageScalePadding: 0,
                    slidesSpacing: 0,
                    thumbs: {
                      appendSpan: false,
                      firstMargin: false,
                      paddingBottom: 4
                    }
                    }).data('royalSlider');

                    $('.rsFullscreenBtn').click(function(e){
                      slider.enterFullscreen();
                      e.preventDefault();
                    });

                    slider.ev.on("rsEnterFullscreen", function() {
                      // enter fullscreen mode 
                      $(".popup-page").css('position', 'relative');
                    });
                    slider.ev.on('rsExitFullscreen', function(event) {
                      // exit fullscreen mode
                      $(".popup-page").removeAttr('style');
                    });
                  }
                });
            });
            // close popup
            $(".popup-page").on('click','.popup-close' ,function(){
              $(".popup-page").removeClass('on');
              $(".popup-page .popup-container").empty();
            });

            // view map
            $(".list-province-item ul > li").on('click','.strict-views', function(){
              var current = $("#current-map").val();
              var id = 'abc';
              var url = 'http://localhost/tours/public/view-map';
              $.ajax({
                  url : url,
                  type : 'POST',
                  dataType : "json",
                  data: {id: id},
                  beforeSend: function(){
                    $(".views-popup").addClass('view');
                    $(".views-popup").append('<div class="loading"></div>');
                  },
                  success : function (data){
                    $( ".loading" ).remove();
                    $(".views-popup .views-container").empty().append(data.html);
                    var pyrmont = {lat: -33.867, lng: 151.195};
                    // view google map
                    map = new google.maps.Map(document.getElementById('view-map'), {
                      center: pyrmont,
                      zoom: 15
                    });

                    infowindow = new google.maps.InfoWindow();
                    var service = new google.maps.places.PlacesService(map);
                    service.nearbySearch({
                      location: pyrmont,
                      radius: 500,
                      type: ['store']
                    }, callback);
                    // view map popup
                    $(".views-popup .views-container").addClass('open');
                  }
                });
            });


            // show detail gallery
            $(".game-entertainment tr td").on('click','.history', function(){
              alert('a');
              var id = 'abc';
              var url = 'http://localhost/tours/public/view-map';
              $.ajax({
                  url : url,
                  type : 'POST',
                  dataType : "json",
                  data: {id: id},
                  beforeSend: function(){
                    $(".views-popup").addClass('view');
                    $(".views-popup").append('<div class="loading"></div>');
                  },
                  success : function (data){
                    $( ".loading" ).remove();
                    $(".views-popup .views-container").empty().append(data.html);
                    var pyrmont = {lat: -33.867, lng: 151.195};
                    // view google map
                    map = new google.maps.Map(document.getElementById('view-map'), {
                      center: pyrmont,
                      zoom: 15
                    });

                    infowindow = new google.maps.InfoWindow();
                    var service = new google.maps.places.PlacesService(map);
                    service.nearbySearch({
                      location: pyrmont,
                      radius: 500,
                      type: ['store']
                    }, callback);
                    // view map popup
                    $(".views-popup .views-container").addClass('open');
                  }
                });
            });

            // view map popup close
            $(".views-popup").on('click','.views-close' ,function(){
              $(".views-popup .views-container").removeClass('open');
              setTimeout(function () {
               $(".views-popup").removeClass('view');
               $(".views-popup .views-container").empty();
              }, 350);
            });
          });
        </script>




        <div class="views-popup">
          <div class="views-container">

          </div>
        </div>

        <div class="popup-page">
          <div class="popup-container">

          </div>
        </div>

        <div class="video-play">

        </div>

        
        <?php echo $this->inlineScript(); ?>
      </div>
      <!-- Scripts -->
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('assets/js/common.js')); ?>
    </body>
</html>

