<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('frontend/css/main.css'))
            ->prependStylesheet($this->basePath('assets/Datepicker/css/jquery-ui.css'))
            ->prependStylesheet($this->basePath('frontend/css/fonts.css'))
//            ->prependStylesheet($this->basePath('frontend/libs/carousel/owl.theme.css'))
            ->prependStylesheet($this->basePath('frontend/libs/Swiper/dist/css/swiper.min.css'))
//            ->prependStylesheet($this->basePath('frontend/libs/carousel/owl.carousel.css'))
//                        ->prependStylesheet($this->basePath('frontend/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('frontend/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
//            ->prependFile($this->basePath('/frontend/js/common.js'))
            ->prependFile($this->basePath('assets/Datepicker/js/jquery-ui.js'))
            ->prependFile($this->basePath('frontend/libs/Swiper/dist/js/swiper.min.js'))
//            ->prependFile($this->basePath('frontend/libs/carousel/owl.carousel.min.js'))
            ->prependFile($this->basePath('frontend/js/bootstrap.min.js'))
            ->prependFile($this->basePath('frontend/js/jquery.min.js'))
            ->prependFile($this->basePath('frontend/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('frontend/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
      <?php $this->header(); ?>
      <?php $this->slider(); ?>
      <?php $this->search(); ?>
      <?php $this->userPost(); ?>
      <?php $this->album(); ?>
      
      <?php echo $this->content; ?>
      <?php $this->news(); ?>
      <?php $this->about(); ?>
      <?php $this->cart(); ?>
      <?php $this->footer(); ?>
      <?php //echo $this->inlineScript(); ?>
      <?php
        echo $this->inlineScript()
            ->prependFile($this->basePath('/frontend/js/common.js'))
            ->prependFile($this->basePath('frontend/js/search.js'));
    ?>
    </body>
</html>
