<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('frontend/css/cart.css'))
            ->prependStylesheet($this->basePath('frontend/css/fonts.css'))
//            ->prependStylesheet($this->basePath('frontend/libs/carousel/owl.theme.css'))
            ->prependStylesheet($this->basePath('frontend/libs/royalSlider/skins/default/rs-default.css'))
            ->prependStylesheet($this->basePath('frontend/libs/royalSlider/royalslider.css'))
            ->prependStylesheet($this->basePath('frontend/libs/Swiper/dist/css/swiper.min.css'))
//            ->prependStylesheet($this->basePath('frontend/libs/carousel/owl.carousel.css'))
                        ->prependStylesheet($this->basePath('frontend/libs/bootstrapSelect/css/bootstrap-select.min.css'))
                        ->prependStylesheet($this->basePath('frontend/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            
            ->prependFile($this->basePath('frontend/libs/royalSlider/jquery.royalslider.min.js'))
            ->prependFile($this->basePath('frontend/libs/bootstrapSelect/js/bootstrap-select.min.js'))
//            ->prependFile($this->basePath('frontend/libs/carousel/owl.carousel.min.js'))
            ->prependFile($this->basePath('frontend/js/bootstrap.min.js'))
            ->prependFile($this->basePath('frontend/js/jquery.min.js'))
            ->prependFile($this->basePath('frontend/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('frontend/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
      <div class="wrapper cart-page">
        <?php $this->header(); ?>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript(); ?>
        <?php $this->about(); ?>
        <?php $this->footer(); ?>
      </div>
    </body>
</html>
