<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <ul class="sidebar-menu">
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Danh mục</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Danh sách</a></li>
        </ul>
      </li>
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-files-o"></i>
          <span>Khu vực</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'nation', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Quốc Gia</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'province', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Tỉnh / Thành Phố</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'district', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Quận / Huyện</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'ward', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Phường / Xã</a></li>
        </ul>
      </li>
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Thành viên</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Danh sách user</a></li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Phân quyền</a></li>
        </ul>
      </li>
      
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Điểm du lịch</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'travel', 'action' => 'add')); ?>"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'travel', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Danh sách</a></li>
        </ul>
      </li>
      
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Tour</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'tour', 'action' => 'add')); ?>"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'tour', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Danh sách</a></li>
        </ul>
      </li>
      
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Điểm ăn uống</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'taste', 'action' => 'add')); ?>"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'taste', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Danh sách</a></li>
        </ul>
      </li>
      
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Video</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'video', 'action' => 'add')); ?>"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'video', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Danh sách</a></li>
        </ul>
      </li>
      
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-th"></i> <span>Trải nghiệm</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'diary', 'action' => 'add')); ?>"><i class="fa fa-circle-o"></i> Thêm mới</a></li>
          <li><a href="<?php echo $this->url('backend/category', array('controller' => 'diary', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Danh sách</a></li>
        </ul>
      </li>

      <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>