<div class="user">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="banner-profile">
          <img src="<?php echo $this->basePath('/assets/demo/slider.png'); ?>">
          <div class="menu-profile-top">
            <ul class="pull-right">
              <li>
                <a href="<?php echo $this->url('user') ?>">Timeline</a>
              </li>
              <li>
                <a href="<?php echo $this->url('user/user-profile') ?>">Thông tin tài khoản</a>
              </li>
              <li>
                <a href="<?php echo $this->url('user/user-photos') ?>">Photos</a>
              </li>
              <li>
                <a href="#">Quản lý</a>
                <ul>
                  <li>
                    <a href="#">E-Voucher</a>
                  </li>
                  <li>
                    <a href="#">Viết Blog</a>
                  </li>
                  <li>
                    <a href="#">Khách sạn</a>
                  </li>
                  <li>
                    <a href="<?php echo $this->url('user/list-tours') ?>">Tours</a>
                  </li>
                  <li>
                    <a href="#">Điểm ăn uống</a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="#">Điểm tích lũy</a>
              </li>
              <li>
                <a href="<?php echo $this->url('user/user-order') ?>">Đơn hàng</a>
              </li>
              <li>
                
                <a href="<?php echo $this->url('user/user-mail') ?>">Hộp thư <span class="mail-box">2 thư mới</span></a>
              </li>
            </ul>
          </div>
          <div class="profile-pic">
            <img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>">
          </div>
        </div>
      </div>
      <div class="col-md-4">
        
      </div>
    </div>
  </div>
</div>