<div class="home-about">
  <div class="container">
    <div class="row">
      <div class="col-md-12 about-title">
        <h2>Mục tiêu hoạt động của chúng tôi</h2>
        <p>Uy tín - chất lượng - đảm bảo cho người tiêu dùng</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="item">
          <div class="about-item">
            <img src="<?php echo $this->basePath('/assets/demo/about.jpg'); ?>">
          </div>
          <div class="about-img">
            <img src="<?php echo $this->basePath('/assets/demo/about.jpg'); ?>">
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-12 subscribe">
        <p>Cập nhật thông tin khuyến mãi nhanh nhất
Hưởng quyền lợi giảm giá riêng biệt</p>
        <div class="email-subscribe">
          <input type="text" class="subscribe-input" name="subscribe">
          <button value="Gửi" class="subscribe-btn">Gửi</button>
        </div>
      </div>
    </div>
  </div>
</div>