<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <header class="menu-header">
          <div class="row">
            <div class="col-md-2">
              <a class="logo" href="<?php echo $this->url('home'); ?>">
                <img src="<?php echo $this->basePath('/assets/logo.png'); ?>">
              </a>
            </div>
            <div class="col-md-10">
              <ul id="menu-top" class="pull-left">
                <li>
                  <a href="<?php echo $this->url('travel'); ?>">Địa điểm phượt</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('tour'); ?>">Tìm tours</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('hotel'); ?>">Khách sạn</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('taste'); ?>">Điểm ăn uống</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('diary'); ?>">Nhật ký</a>
                </li>
                <li>
                  <a href="<?php echo $this->url('video'); ?>">Video</a>
                </li>
              </ul>
              <ul class="pull-right">
                <li class="login">
                  <a href="<?php echo $this->url('register'); ?>">Đăng ký</a>/
                  <a href="<?php echo $this->url('login'); ?>">Đăng nhập</a>
                </li>
              </ul>
            </div>
          </div>
        </header>
      </div>
    </div>
  </div>

</div>