<header id="header">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="logo">
          
        </div>
        <ul id="menu-top" class="pull-right">
          <li>
            <a href="#">Địa điểm phượt</a>
          </li>
          <li>
            <a href="#">Tìm tours</a>
          </li>
          <li>
            <a href="#">Khách sạn</a>
          </li>
          <li>
            <a href="#">Điểm ăn uống</a>
          </li>
          <li>
            <a href="#">Nhật ký</a>
          </li>
          <li>
            <a href="#">Tin tức</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3">
        <u id="login" class="pull-right">
          <li>
            <a href="#">Đăng ký </a> /
            <a href="#">Đăng nhập </a>
          </li>
        </u>
      </div>
    </div>
  </div>
</header>