<header id="header">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="logo">
          
        </div>
        <ul id="menu-top" class="pull-right">
          <li>
            <a href="<?php echo $this->url('tour', array('controller' => 'tour', 'action' => 'index')); ?>">Địa điểm phượt</a>
          </li>
          <li>
            <a href="<?php echo $this->url('travel', array('controller' => 'index', 'action' => 'index')); ?>">Tìm tours</a>
          </li>
          <li>
            <a href="<?php echo $this->url('hotel', array('controller' => 'hotel', 'action' => 'index')); ?>">Khách sạn</a>
          </li>
          <li>
            <a href="<?php echo $this->url('taste', array('controller' => 'taste', 'action' => 'index')); ?>">Điểm ăn uống</a>
          </li>
          <li>
            <a href="<?php echo $this->url('diary', array('controller' => 'diary', 'action' => 'index')); ?>">Nhật ký</a>
          </li>
          <li>
            <a href="<?php echo $this->url('news', array('controller' => 'news', 'action' => 'index')); ?>">Tin tức</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3">
        <u id="login" class="pull-right">
          <li>
            <a href="#">Đăng ký </a> /
            <a href="#">Đăng nhập </a>
          </li>
        </u>
      </div>
    </div>
  </div>
</header>