<ul>
  <li>
    <a href="<?php echo $this->url('user/user-hotel', array('controller' => 'hotel', 'action' => 'index')) ?>"><span></span>Quản lý khách sạn</a>
  </li>
  <li class="active">
    <a href="<?php echo $this->url('user/user-hotel', array('controller' => 'hotel', 'action' => 'index')) ?>"><span class="icon icon-menu"></span>Tất cả</a>
  </li>
  
  
  <li>
    <a href="<?php echo $this->url('user/user-hotel-create', array('controller' => 'hotel', 'action' => 'create')) ?>"><span class="icon icon-file-add"></span>Đăng</a>
  </li>
  
  <li>
    <a href="<?php echo $this->url('user/tours-order', array('controller' => 'hotel', 'action' => 'order')) ?>"><span></span>Đơn hàng</a>
  </li>

  <li>
    <a href="#"><span class="icon icon-help-circled"></span>Trợ giúp</a>
  </li>
</ul>