<ul>
  <li>
    <a href="#"><span class="icon icon-user-1"></span>Khách lẻ</a>
  </li>
  <li>
    <a href="#"><span class="icon icon-user-1"></span>Lễ tân</a>
    <span class="show"><var class="icon icon-angle-down"></var></span>
    <ul>
      <li>
        <a href="<?php echo $this->url('user/post', array('controller' => 'tours', 'action' => 'post')) ?>">
          <span class="icon icon-plus"></span>
          Danh sách đặt phòng</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/post', array('controller' => 'tours', 'action' => 'post')) ?>">
          <span class="icon icon-bars"></span>
           Danh sách khách sẽ đến</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-cart-plus"></span>
          Danh sách khách sẽ đi</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-calendar"></span>
          Danh sách trả phòng</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-calendar"></span>
          Danh sách khách</a>
      </li>
      
    </ul>
  </li>
  <li>
    <a href="#"><span class="icon icon-user-1"></span>Buồng phòng</a>
    <span class="show"><var class="icon icon-angle-down"></var></span>
  </li>
  <li>
    <a href="#"><span class="icon icon-user-1"></span>Báo cáo</a>
    <span class="show"><var class="icon icon-angle-down"></var></span>
  </li>
  <li>
    <a href="<?php echo $this->url('user/list-tours', array('controller' => 'tours', 'action' => 'index')) ?>">
      <span class="icon icon-menu"></span>
      Cấu hình</a>
    <span class="show"><var class="icon icon-angle-down"></var></span>
    <ul>
      <li>
        <a href="<?php echo $this->url('user/post', array('controller' => 'tours', 'action' => 'post')) ?>">
          <span class="icon icon-plus"></span>
          Thông tin chung</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/post', array('controller' => 'tours', 'action' => 'post')) ?>">
          <span class="icon icon-bars"></span>
           Loại phòng</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-cart-plus"></span>
          Danh sách phòng</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-calendar"></span>
          Dịch vụ mở rông</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-calendar"></span>
          Nhân viên</a>
      </li>
      <li>
        <a href="<?php echo $this->url('user/tours-order', array('controller' => 'tours', 'action' => 'order')) ?>">
          <span class="icon icon-calendar"></span>
          Cài đặt hệ thống</a>
      </li>
    </ul>
  </li>
 
  <li>
    <a href="#"><span class="icon icon-user-1"></span>Thành viên</a>
  </li>
  <li>
    <a href="#"><span class="icon icon-email-mail-streamline"></span>Email marketing</a>
  </li>
   <li>
    <a href="#"><span class="icon icon-question"></span>Trợ giúp</a>
  </li>
</ul>