<div class="header">
  <div class="logo">
  
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <?php $this->menu(); ?>
      </div>
      <div class="col-md-3">
        <u id="login" class="pull-right">
          <li>
            <a href="<?php //echo $this->url('register', array('controller' => 'public', 'action' => 'register')); ?>">Đăng ký </a> /
            <a href="<?php //echo $this->url('login', array('controller' => 'public', 'action' => 'login')); ?>">Đăng nhập </a>
          </li>
        </u>
      </div>
    </div>
  </div>
</div>