<div class="header">
  <div class="logo">
  
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <ul id="menu-top">
          <li>
            <a href="<?php echo $this->url('travel', array('controller' => 'tour', 'action' => 'index')); ?>">Địa điểm phượt</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <ul class="row">
                        <div class="col-md-8">
                          <div class="row">
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/da-ngoai.jpg'); ?>">
                                <span>Dã ngoại</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/nghi-duong.jpg'); ?>">
                                <span>Nghỉ dưỡng</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/kham-pha.jpg'); ?>">
                                <span>Khám phá</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/leo-nui.jpg'); ?>">
                                <span>Leo núi</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/tham-quan.jpg'); ?>">
                                <span>Tham quan</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/tro-choi.jpg'); ?>">
                                <span>Giải trí - trò chơi</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/cong-vien.jpg'); ?>">
                                <span>Công viên</span></a></li>
                            <li class="col-md-3"><a href="#">
                                <img src="<?php echo $this->basePath('/defaults/trung-tam-thuong-mai.jpg'); ?>">
                                <span>Trung tâm thương mại</span></a></li>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="row">
                                <li class="col-md-12 four"><a href="#">
                                    <img src="<?php echo $this->basePath('/assets/28851_original.jpg'); ?>">
                              </a></li>
                          </div>
                        </div>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('tour', array('controller' => 'travel', 'action' => 'index')); ?>">Tìm tours</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <h2>Tour trong nước</h2>
                      <ul class="row">
                            <li class="col-md-2"><a href="#">
                              <img src="<?php echo $this->basePath('/defaults/da-lat.jpg'); ?>">
                                <span>Đà Lạt</span>
                          </a></li>
                          <li class="col-md-2"><a href="#">
                              <img src="<?php echo $this->basePath('/defaults/nha-trang.jpg'); ?>">
                              <span>Nha Trang</span></a></li>
                          <li class="col-md-2"><a href="#">
                              <img src="<?php echo $this->basePath('/defaults/phan-thiet.jpg'); ?>">
                              <span>Phan Thiết</span></a></li>
                          <li class="col-md-2"><a href="#">
                              <img src="<?php echo $this->basePath('/defaults/hue.jpg'); ?>">
                              <span>Huế</span></a></li>
                          <li class="col-md-2"><a href="#">
                              <img src="<?php echo $this->basePath('/defaults/da-nang.jpg'); ?>">
                              <span>Đà Nẵng</span></a></li>
                          <li class="col-md-2"><a href="#">
                              <img src="<?php echo $this->basePath('/defaults/binh-duong.jpg'); ?>">
                              <span>Bình Dương</span></a></li>
                          
                      </ul>
                      <h2>Tour nước ngoài</h2>
                      <ul class="row">
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/thai-lan.jpg'); ?>">
                            <span>Thái Lan</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/lao.jpg'); ?>">
                            <span>Lào</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/singapore.jpg'); ?>">
                            <span>Singapore</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/my.jpg'); ?>">
                            <span>Mỹ</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/uc.jpg'); ?>">
                            <span>Úc</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/nhat-ban.jpg'); ?>">
                            <span>Nhật  Bản</span></a></li>
                        
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('hotel', array('controller' => 'hotel', 'action' => 'index')); ?>">Khách sạn</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <ul class="row">
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/sang-trong.jpg'); ?>">
                            <span>Khách sạn cao cấp</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/tam-trung.jpg'); ?>">
                            <span>Khách sạn tầm trung</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/gia-re.jpg'); ?>">
                            <span>Khách sạn giá rẻ</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/nha-nghi.jpg'); ?>">
                            <span>Nhà nghỉ</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/phong-tro.jpg'); ?>">
                            <span>Phòng trọ</span></a></li>
                        <li class="col-md-2"><a href="#">
                            <img src="<?php echo $this->basePath('/defaults/resort.jpg'); ?>">
                            <span>Resort</span></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('taste', array('controller' => 'taste', 'action' => 'index')); ?>">Điểm ăn uống</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <ul class="row">
                        <div class="col-md-8">
                          <div class="row item-taste">
                            <a class="col-md-3" href="#"><span></span> Sang trọng</a>
                            <a class="col-md-3" href="#"><span></span> Buffet</a>
                            <a class="col-md-3" href="#"><span></span> Nhà hàng</a>
                            <a class="col-md-3" href="#"><span></span> Ăn vặt/vỉa hè</a>
                            <a class="col-md-3" href="#"><span></span> Ăn chay</a>
                            <a class="col-md-3" href="#"><span></span> Café/Dessert</a>
                            <a class="col-md-3" href="#"><span></span> Quán ăn</a>
                            <a class="col-md-3" href="#"><span></span> Bar/Pub</a>
                            <a class="col-md-3" href="#"><span></span> Quán nhậu</a>
                            <a class="col-md-3" href="#"><span></span> Beer club</a>
                            <a class="col-md-3" href="#"><span></span> Tiệm bánh</a>
                            <a class="col-md-3" href="#"><span></span> Tiệc tận nơi</a>
                            <a class="col-md-3" href="#"><span></span> Shop Online</a>
                            <a class="col-md-3" href="#"><span></span> Giao cơm văn phòng</a>
                            <a class="col-md-3" href="#"><span></span> Khu Ẩm Thực</a>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="row">
                            <li class="col-md-12 four"><a href="#">Nhà Hàng</a></li>
                          </div>
                        </div>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('video', array('controller' => 'video', 'action' => 'index')); ?>">Video</a>
          </li>
          <li>
            <a href="<?php echo $this->url('diary', array('controller' => 'diary', 'action' => 'index')); ?>">Trải nghiệm</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3">
        <u id="login" class="pull-right">
          <li>
            <a href="<?php echo $this->url('register', array('controller' => 'public', 'action' => 'register')); ?>">Đăng ký </a> /
            <a href="<?php echo $this->url('login', array('controller' => 'public', 'action' => 'login')); ?>">Đăng nhập </a>
          </li>
        </u>
      </div>
    </div>
  </div>
</div>