<div class="header">
  <div class="logo">
  
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
        <ul id="menu-top">
          <li>
            <a href="<?php echo $this->url('travel', array('controller' => 'tour', 'action' => 'index')); ?>">Địa điểm phượt</a>
          </li>
          <li>
            <a href="<?php echo $this->url('tour', array('controller' => 'travel', 'action' => 'index')); ?>">Tìm tours</a>
          </li>
          <li>
            <a href="<?php echo $this->url('hotel', array('controller' => 'hotel', 'action' => 'index')); ?>">Khách sạn</a>
          </li>
          <li>
            <a href="<?php echo $this->url('taste', array('controller' => 'taste', 'action' => 'index')); ?>">Điểm ăn uống</a>
          </li>
          <li>
            <a href="<?php echo $this->url('video', array('controller' => 'video', 'action' => 'index')); ?>">Video</a>
          </li>
          <li>
            <a href="<?php echo $this->url('diary', array('controller' => 'diary', 'action' => 'index')); ?>">Nhật ký</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3">
        <u id="login" class="pull-right">
          <li>
            <a href="<?php echo $this->url('register', array('controller' => 'public', 'action' => 'register')); ?>">Đăng ký </a> /
            <a href="<?php echo $this->url('login', array('controller' => 'public', 'action' => 'login')); ?>">Đăng nhập </a>
          </li>
        </u>
      </div>
    </div>
  </div>
</div>