<div class="user-post">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="title"><a href="#"><span class="icon icon-video-camera"></span> VIDEO hot</a></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <div class="photo-big">
          <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
          <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
          <div class="album-title">
            <div class="name">
              <a href="#">Thành phố Đà Lạt</a>
            </div>
            <div class="author">
              <p><span class="icon icon-user-profile"></span> Pham Long - <span class="icon icon-calendar"></span> 16/03/3016</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <ul class="row">
          <li class="col-md-6">
            <div class="photo-item">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
              <p class="position-name">
                <a href="#">Thành phố Đà Lạt</a>
              </p>
            </div>
          </li>
          <li class="col-md-6">
            <div class="photo-item">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
              <p class="position-name">
                <a href="#">Thành phố Đà Lạt</a>
              </p>
            </div>
          </li>
          <li class="col-md-6">
            <div class="photo-item">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
              <p class="position-name">
                <a href="#">Thành phố Đà Lạt</a>
              </p>
            </div>
          </li>
          <li class="col-md-6">
            <div class="photo-item">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
              <p class="position-name">
                <a href="#">Thành phố Đà Lạt</a>
              </p>
            </div>
          </li>
          <li class="col-md-6">
            <div class="photo-item">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
              <p class="position-name">
                <a href="#">Thành phố Đà Lạt</a>
              </p>
            </div>
          </li>
          <li class="col-md-6">
            <div class="photo-item">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
              <p class="position-name">
                <a href="#">Thành phố Đà Lạt</a>
              </p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>