<div class="home-news video-list">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3><a href="#"><span>Ẩm thực</span></a></h3>
      </div>
    </div>
    <ul class="row">
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>

      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
      <li class="col-md-3">
        <div class="item-news">
          <div class="img">
            <a href="#">
              <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
            </a>
            <div class="position-news">
              <span>September 13th, 2015</span>
              <span class="pull-right">1,521 <var class="icon icon-heart"></var></span>
            </div>
          </div>
          <div class="content-item-news">
            <h2><a href="#">Kinh nghiệm đi phượt Đồng Cao</a></h2>
          </div>
          <div class="rating">
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
            <span class="icon icon-star"></span>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>