<div class="cart">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="steps">
          <div class="step step1 active"><a><span>Đơn hàng</span></a></div>
          <div class="step step2 active"><a><span>Thông Tin Giao Hàng</span></a></div>
          <div class="step step3 active complate"><a><span>Đặt hàng</span></a> <span class="done">Hoàn tất</span></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="cart-content">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <table class="cart-order">
          <thead>
            <tr>
              <th>Sản phẩm</th>
              <th>Đơn giá</th>
              <th>Số lượng</th>
              <th>Thành tiền</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <div class="view-cart-item">
                  <div class="image">
                    <span class="sale">-15%</span>
                    <img class="img-responsive" src="https://vcdn.tikicdn.com/cache/200x280/media/catalog/product/c/a/canon700d.u2388.d20160525.t095150.jpg">
                  </div>
                  <div class="name">
                    <p>Hệ Thống Bánh Trung Thu Nổi Tiếng Yến Sào Khánh Hòa - 08 Chi Nhánh</p>
                  </div>
                </div>
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
                <p class="off">11.900.000 ₫</p>
              </td>
              <td>
                <input type="number" class="quanlity">
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
              </td>
            </tr>
            
            <tr>
              <td>
                <div class="view-cart-item">
                  <div class="image">
                    <span class="sale">-15%</span>
                    <img class="img-responsive" src="https://vcdn.tikicdn.com/cache/200x280/media/catalog/product/c/a/canon700d.u2388.d20160525.t095150.jpg">
                  </div>
                  <div class="name">
                    <p>Hệ Thống Bánh Trung Thu Nổi Tiếng Yến Sào Khánh Hòa - 08 Chi Nhánh</p>
                  </div>
                </div>
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
                <p class="off">11.900.000 ₫</p>
              </td>
              <td>
                <input type="number" class="quanlity">
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
              </td>
            </tr>
            
          </tbody>
        </table>
      </div>
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-12">
            <div class="summary">
              <p class="total">Tổng cộng: <span>10.046.000 ₫</span></p>
              <p class="total2">Thành tiền: <span>10.046.000 ₫ </span></p>
              <p class="text-right">
                <i>(Đã bao gồm VAT)</i>
              </p>
            </div>
          </div>
          <div class="col-md-12">
            <div class="coupon">
              <h4>Mã giảm giá / Quà tặng</h4>
              <div class="input-group">
                <input id="coupon" placeholder="Nhập ở đây..." type="text" class="form-control" value="">
                <span class="input-group-btn">
                    <button class="btn btn-default btn-coupon" type="button">Đồng ý</button>
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <button type="button" class="btn btn-default btn-checkout form-control" onclick="">
                                    ĐẶT HÀNG
                                </button>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</div>