<div class="cart">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="steps">
          <div class="step step1 active"><a><span>Đơn hàng</span></a></div>
          <div class="step step2 active"><a><span>Thông Tin Giao Hàng</span></a></div>
          <div class="step step3 active complate"><a><span>Đặt hàng</span></a> <span class="done">Hoàn tất</span></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="cart-content">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <table class="cart-order">
          <thead>
            <tr>
              <th>Sản phẩm</th>
              <th>Đơn giá</th>
              <th>Số lượng</th>
              <th>Thành tiền</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <div class="view-cart-item">
                  <div class="image">
                    <span class="sale">-15%</span>
                    <img class="img-responsive" src="https://vcdn.tikicdn.com/cache/200x280/media/catalog/product/c/a/canon700d.u2388.d20160525.t095150.jpg">
                  </div>
                  <div class="name">
                    <p>Hệ Thống Bánh Trung Thu Nổi Tiếng Yến Sào Khánh Hòa - 08 Chi Nhánh</p>
                  </div>
                </div>
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
                <p class="off">11.900.000 ₫</p>
              </td>
              <td>
                <input type="number" class="quanlity">
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
              </td>
            </tr>
            
            <tr>
              <td>
                <div class="view-cart-item">
                  <div class="image">
                    <span class="sale">-15%</span>
                    <img class="img-responsive" src="https://vcdn.tikicdn.com/cache/200x280/media/catalog/product/c/a/canon700d.u2388.d20160525.t095150.jpg">
                  </div>
                  <div class="name">
                    <p>Hệ Thống Bánh Trung Thu Nổi Tiếng Yến Sào Khánh Hòa - 08 Chi Nhánh</p>
                  </div>
                </div>
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
                <p class="off">11.900.000 ₫</p>
              </td>
              <td>
                <input type="number" class="quanlity">
              </td>
              <td class="price">
                <p><strong>9.990.000 ₫</strong></p>
              </td>
            </tr>
            
          </tbody>
        </table>
        <div class="row">
          <div class="col-md-12">
            <div class="item-cart-hotel">
              <div class="row">
                <div class="col-md-2">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>" width="100">
                </div>
                <div class="col-md-10">
                  <div class="title">
                    <h2>Kim Hoa Resort Phú Quốc </h2>
                    <p>4 Đường Nguyễn Phúc Nguyễn, Hội An, Quảng Nam</p>
                  </div>
                  <div class="cart-list-room">
                    <h2>Các phòng đã đặt:</h2>
                    <ul class="row">
                      <li class="col-md-6">
                        <div class="item">
                          <h3>Phong 006 <span class="remove-room">x</span></h3>
                          <div class="item-room">
                            <p><strong>Loại phong:</strong> 
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                            </p>
                            <p><strong>Diện tích phòng:</strong> 15m2</p>
                            <p><strong>Ở tối đa:</strong>2 người lớn, 1 trẻ em</p>
                          </div>
                          <div class="description">
                            <p><strong>Nhận phòng: </strong>14:00, Thứ hai, ngày 05/09/2016</p>
                            <p><strong>Trả phòng:</strong> 11:30, Thứ ba, ngày 06/09/2016</p>
                            <p><strong>Số đêm: </strong>1</p>
                          </div>
                          <div class="hotel-price">
                            <p class="cost">9.990.000 ₫</p>
                            <p class="sale">9.990.000 ₫</p>
                            <p class="view-sale">-10%</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-6">
                        <div class="item">
                          <h3>Phong 006 <span class="remove-room">x</span></h3>
                          <div class="item-room">
                            <p><strong>Loại phong:</strong> 
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                            </p>
                            <p><strong>Diện tích phòng:</strong> 15m2</p>
                            <p><strong>Ở tối đa:</strong>2 người lớn, 1 trẻ em</p>
                          </div>
                          <div class="description">
                            <p><strong>Nhận phòng: </strong>14:00, Thứ hai, ngày 05/09/2016</p>
                            <p><strong>Trả phòng:</strong> 11:30, Thứ ba, ngày 06/09/2016</p>
                            <p><strong>Số đêm: </strong>1</p>
                          </div>
                          <div class="hotel-price">
                            <p class="cost">9.990.000 ₫</p>
                            <p class="sale">9.990.000 ₫</p>
                            <p class="view-sale">-10%</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-6">
                        <div class="item">
                          <h3>Phong 006 <span class="remove-room">x</span></h3>
                          <div class="item-room">
                            <p><strong>Loại phong:</strong> 
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                            </p>
                            <p><strong>Diện tích phòng:</strong> 15m2</p>
                            <p><strong>Ở tối đa:</strong>2 người lớn, 1 trẻ em</p>
                          </div>
                          <div class="description">
                            <p><strong>Nhận phòng: </strong>14:00, Thứ hai, ngày 05/09/2016</p>
                            <p><strong>Trả phòng:</strong> 11:30, Thứ ba, ngày 06/09/2016</p>
                            <p><strong>Số đêm: </strong>1</p>
                          </div>
                          <div class="hotel-price">
                            <p class="cost">9.990.000 ₫</p>
                            <p class="sale">9.990.000 ₫</p>
                            <p class="view-sale">-10%</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-6">
                        <div class="item">
                          <h3>Phong 006 <span class="remove-room">x</span></h3>
                          <div class="item-room">
                            <p><strong>Loại phong:</strong> 
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                              <img src="<?php echo $this->basePath('/assets/star.png') ?>">
                            </p>
                            <p><strong>Diện tích phòng:</strong> 15m2</p>
                            <p><strong>Ở tối đa:</strong>2 người lớn, 1 trẻ em</p>
                          </div>
                          <div class="description">
                            <p><strong>Nhận phòng: </strong>14:00, Thứ hai, ngày 05/09/2016</p>
                            <p><strong>Trả phòng:</strong> 11:30, Thứ ba, ngày 06/09/2016</p>
                            <p><strong>Số đêm: </strong>1</p>
                          </div>
                          <div class="hotel-price">
                            <p class="cost">9.990.000 ₫</p>
                            <p class="sale">9.990.000 ₫</p>
                            <p class="view-sale">-10%</p>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                  
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="row">
          <div class="col-md-12">
            <div class="summary">
              <p class="total">Tổng cộng: <span>10.046.000 ₫</span></p>
              <p class="total2">Thành tiền: <span>10.046.000 ₫ </span></p>
              <p class="text-right">
                <i>(Đã bao gồm VAT)</i>
              </p>
            </div>
          </div>
          <div class="col-md-12">
            <div class="coupon">
              <h4>Mã giảm giá / Quà tặng</h4>
              <div class="input-group">
                <input id="coupon" placeholder="Nhập ở đây..." type="text" class="form-control" value="">
                <span class="input-group-btn">
                    <button class="btn btn-default btn-coupon" type="button">Đồng ý</button>
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <button type="button" class="btn btn-default btn-checkout form-control" onclick="">
                                    ĐẶT HÀNG
                                </button>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</div>