<div class="user album">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
<!--            <div class="sidebar-left">
              <ul>
                <li>
                  <a href="#"><span></span>Quản lý</a>
                </li>
                <li>
                  <a href="#"><span></span>Đăng tin</a>
                </li>
                
                <li>
                  <a href="#"><span></span>E-Voucher</a>
                </li>
                <li>
                  <a href="#"><span></span>Tours</a>
                </li>
                <li>
                  <a href="#"><span></span>Điểm ăn uống</a>
                </li>
                <li>
                  <a href="#"><span></span>Khách sạn</a>
                </li>
                
              </ul>
            </div>-->
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li>Profile</li>
                  <li class="active">Album</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Album</h2>
                  <div class="page">
                    <ul class="row list-album-profile">
                      <li class="col-md-2">
                        <div class="item upload">
                          
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                      <li class="col-md-2">
                        <div class="item">
                          <div class="img">
                            <img src="<?php echo $this->basePath('/assets/demo/deal.jpg') ?>">
                          </div>
                          <div class="album-title">
                            <p><a href="#">Du lịch Tiền Giang ngày hè</a></p>
                            <p class="total-photos">3 photos</p>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>