<div class="search">
  <div class="page-search">
    <div class="search-item">
      <div class="search-list">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="list-search">
                <div class="row">
                  <div class="col-md-3">
                    <input type="text" class="form-control" name="tasteKeyword" id="tasteKeyword">
                  </div>
                  <div class="col-md-2">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">Quốc Gia</option>
                      <option value="">Việt Nam</option>
                      <option value="">Thái Lan</option>
                      <option>Ấn Độ</option>
                      <option>Mỹ</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker">
                      <option value="">Tỉnh/Thành Phố</option>
                      <option>Bình Phước</option>
                      <option>Hà Nội</option>
                      <option>Hải Dương</option>
                      <option>Bình Định</option>
                      <option>Quản Trị</option>
                      <option>Quảng Nam</option>
                      <option>Huế</option>
                      <option>Đà Nẵng</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker">
                      <option value="">Quận/Huyện</option>
                      <option>Quận 1</option>
                    </select>
                  </div>
                  <div class="col-md-1">
                    <button class="button-search pull-right" id="tour-search-button">Tìm</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> Danh sách Tỉnh / Thành Phố</h1>
    </div>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="province-container">
        <ul>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li><li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="<?php echo $this->url('travel/travel-province', array('controller' => 'category', 'action' => 'index', 'category' => 'ho-chi-minh')); ?>" title="Ho chi minh">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          
          
          
          
          
          
        </ul>
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content">
    <div style="width: 100%; height: 100%;" id="map"></div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>-->
