<div class="popup-content">
  <div class="popup-header">
   <h2><span class="icon icon-location"></span> <?php echo $dataPost->name; ?></h2>
   <div class="close-zoom pull-right">
     <div class="zoom"><a href="<?php //echo $this->url('tour-page-detail', array('slug' => 'chi-tiet-tour', 'id' => 1231231)) ?>"><span class="icon icon-full-screen-selector"></span> Xem rộng hơn</a></div>
     <div class="popup-close"><span class="icon icon-cancel-music"></span></div>
   </div>
  </div>
  <div class="popup-body">
    <div class="slider">
      <div class="row">
        <div class="col-md-8">
          <?php if($gallery): ?>
          <div class="royalSlider rsDefault">
             <?php foreach ($gallery as $value): ?>
              <img class="rsImg" src="<?php echo SERVER_IMAGE.'/'. $value['name']; ?>" data-rsTmb="<?php echo SERVER_IMAGE.'/100x80/'. $value['name']; ?>" alt="image description" />
              <?php endforeach; ?>
           </div>
          <?php endif; ?>
        </div>
        <div class="col-md-4">
          <div class="description">
             <h2><?php echo $dataPost->name; ?></h2>
             <p class="expt">
               <?php echo $dataPost->excerpt; ?>
             </p>
             <div class="item">
               <p class="cost">Giá gốc: 800,000<span>đ</span></p>
               <p class="price-sale">1,800,000<span>đ</span> <var>-50%</var></p>
             </div>
             <div class="item">
               <div class="quanlity">
                 Số lượng: <input type="number" name="quanlity">
               </div>
               <div class="payment">
                 <a href="#" class="pull-right">Mua ngay</a>
               </div>
             </div>
             <div class="item">
               <p class="count-user-payment"><span class="icon icon-user-profile"></span>102 người đã mua</p>
               <p class="time">19 Ngày 04 : 36 : 09</p>
             </div>
             <div class="item">
               <p>Giao hàng miễn phí tại TP.HCM</p>
             </div>
          </div>
        </div>
      </div>
   </div>
    <?php if($listTour): ?>
    <div class="list-tours-related">
       <h2>Các điểm tham quan trong tour này</h2>
       <div class="swiper-container">
         <ul class="swiper-wrapper">
           <?php foreach ($listTour as $value): ?>
           <li class="col-md-2 swiper-slide">
            <div class="item">
              <div class="photo">
                15 Ảnh
              </div>
              <p class="img">
                <a href="<?php //echo $this->url(); ?>">
                  <img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>">
                </a>
              </p>
               <p class="title">
                 <a href="#"><?php echo $value['name']; ?></a>
               </p>
            </div>
          </li>
          <?php endforeach; ?>
         </ul>
       </div>
       <div class="swiper-btn button-prev"><span class="icon icon-left-chevron"></span></div>
       <div class="swiper-btn button-next"><span class="icon icon-right-chevron"></span></div>
    </div>
    <?php endif; ?>
    <div class="commitment">
      <div class="commitment-view">
        <div class="content">
          <?php if($dataPost->excerpt_des): ?>
          <div class="col-md-7">
           <h2>ĐIỂM NỔI BẬT</h2>
           <?php echo $dataPost->excerpt_des; ?>
           
         </div>
          <?php endif; ?>
          <?php if($dataPost->commitment): ?>
         <div class="col-md-5">
           <h2>Cam kết</h2>
           <?php echo $dataPost->commitment; ?>
         </div>
          <?php endif; ?>
        </div>
      </div>
      <div class="col-md-12 readmove">
        <a href="#"><span class="text">Xem thêm</span> <span class="icon icon-angle-down"></span></a>
      </div>
      <script>
        jQuery(document).ready(function($){
          $(".readmove a").on('click', function(){
            if($(this).hasClass('up')){
               $(".commitment .commitment-view .content").removeClass('expanded');
               $(".readmove a span.text").empty().append('Xem thêm');
               $(this).removeClass('up');
            }else{
               $(".commitment .commitment-view .content").addClass('expanded');
               $(".readmove a span.text").empty().append('Thu gọn');
               $(this).addClass('up');
            }

          });
        });
      </script>
    </div>

   <div class="content-page-popup">
     <div class="row">
       <div class="col-md-8 about">
         <div class="tab-title">
           <ul>
             <li class="active"><a href="#">Thông tin chi tiết</a></li>
             <li><a href="javascript:void(0)" id="tab-comment">Bình luận</a></li>
           </ul>
         </div>
         <div class="detail">
           <div class="description">
             <?php echo $dataPost->content; ?>
           </div>
           <div  class="payment-now">
             <a href="#">Mua ngay</a>
           </div>
         </div>


         <div id="page-comment">
           
         </div>

       </div>
       <div class="col-md-4">
         <div class="post-position">
           <h2>ĐỊA ĐIỂM SỬ DỤNG</h2>
           <h3>Vietkite Travel</h3>
           <p>512 Bùi Đình Túy, Phường 12, Quận Bình Thạnh</p>
           <p>Điện thoại: 0873003799</p>
           <div class="map-position"></div>
         </div>
         <?php if($dataPostRelated): ?>
         <div class="list-related">
           <ul class="row list-item">
             <?php foreach ($dataPostRelated as $value): ?>
             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       E-Voucher
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#"><?php echo $value['name']; ?></a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>
             <?php endforeach; ?>
           </ul>
         </div>
         <?php endif; ?>
       </div>
     </div>
   </div>
  </div>
  </div>

  <div class="poup-footer">
  <div class="row">
   <div class="col-md-4">
     <h2>Công ty TNHH Smart Connector</h2>
     <ul>
       <li>294 Hòa bình, P. Hiệp Tân, Q. Tân Phú, TP.HCM</li>
       <li>ĐT: 08.73055707 - Fax: 08.38666237</li>
       <li><a href="#">sales@abc.vn</a></li>
       <li>Mã số thuế: 0310955176 do Sở Kế hoạch đầu tư TP HCM 
  cấp ngày 29/06/2011</li>
     </ul>
   </div>
   <div class="col-md-2">
     <h2>Về chúng tôi</h2>
     <ul>
       <li><a href="#">Giới thiệu</a></li>
       <li><a href="#">Quy định</a></li>
       <li><a href="#">Trợ giúp</a></li>
       <li><a href="#">Đăng ký quảng cáo</a></li>
       <li><a href="#">Liên hệ</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chăm sóc khách hàng</h2>
     <ul class="support-footer">
       <li><span class="hotline">HOTLINE</span> <span class="hotline-phone">08 7300 5757</span></li>
       <li><a href="#">Chính sách giao hàng</a></li>
       <li><a href="#">Chính sách đổi sản phẩm</a></li>
       <li><a href="#">Chính sách bảo mật</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chứng nhận</h2>
     <ul>
       <li><img src="/tours/public/frontend/images/bocongthuong.png"></li>
     </ul>
     <h2>Liên kết</h2>
     <ul class="connect">
       <li class="facebook"><a href="#"><span class="icon icon-facebook"></span></a></li>
       <li class="twitter"><a href="#"><span class="icon icon-twitter"></span></a></li>
       <li class="youtube"><a href="#"><span class="icon icon-youtube"></span></a></li>
       <li class="googleplus"><a href="#"><span class="icon icon-googleplus"></span></a></li>
       <li class="linkedin"><a href="#"><span class="icon icon-linkedin"></span></a></li>
       <li class="pinterest"><a href="#"><span class="icon icon-pinterest"></span></a></li>
     </ul>
   </div>
  </div>
  </div>

  <div class="coppyright">
  <div class="row">
    <div class="col-md-12">
       <p>Coppyright © 2015 Long.pham. All Rights Reserved</p>
     </div>
  </div>
  </div>