<?php $this->meta(
        $category->name . ' ' .$regionExists->name
        ); ?>  
<div class="list-container-view">
  <?php $this->searchAdvance(); ?>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> <?php echo ($category) ? $category->name: ''; ?> <?php echo ($regionExists) ? $regionExists->type .' '. $regionExists->name: ''; ?></h1>
    </div>
  </div>
  <div class="province-container">
    <div class="province">
      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
    </div>
    <div class="list-province-item">
      <ul class="row load-post list-item">
        
      </ul>
    </div>
    
<!--    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="paging">
            <?php
//            echo $this->paginationControl($paginator, 'Sliding', 'paginationAjax', array(
//                $this->route,
//                'category' => $category->slug,
//                'province' => $province,
//                'district' => $district,
//                'nation' => $nation,
//                'page' => $page
//            ));
            ?>
        </div>
      </div>
    </div>-->
  </div>
  <div class="footer-travel">
    <?php $this->footerTravel(); ?>
  </div>
</div>

<!--<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="list-cat">
        <ul class="row list-item">
          
        </ul>
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content">
    <div class="map-wp">
      <div style="width: 100%; height: 100%;" id="map"></div>
    </div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>
     
 detail tour 
<div class="popup-page views-popup">
  <div class="popup-container tour">

  </div>
</div>
<script>
  jQuery(document).ready(function($){
    $(".list-container-view ul >li a").on('click', function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/tour-detail';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".popup-page").addClass('on');
            $(".popup-page").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".popup-container").empty().append(data.html);
            $("#page-comment").empty().append(data.htmlComment);
            $("body").append(data.htmlCommentFormOutput);
            // call royalSlider
            var slider = $('.royalSlider').royalSlider({
            fullscreen: {
              enabled: true,
              nativeFS: true
            },
            controlNavigation: 'thumbnails',
            autoScaleSlider: true, 
            autoScaleSliderWidth: 782,
            autoScaleSliderHeight: 478,
            loop: false,
            imageScaleMode: 'none',
            navigateByClick: true,
            numImagesToPreload:2,
            arrowsNav:true,
            arrowsNavAutoHide: true,
            arrowsNavHideOnTouch: true,
            keyboardNavEnabled: true,
            fadeinLoadedSlide: true,
            globalCaption: false,
            globalCaptionInside: false,
            imageScalePadding: 0,
            slidesSpacing: 0,
            thumbs: {
              appendSpan: true,
              firstMargin: true,
              paddingBottom: 4
            }
          }).data('royalSlider');

          $('.rsFullscreenBtn').click(function(e){
            slider.enterFullscreen();
            e.preventDefault();
          });

          slider.ev.on("rsEnterFullscreen", function() {
            // enter fullscreen mode 
            $(".popup-page").css('position', 'relative');
          });
          slider.ev.on('rsExitFullscreen', function(event) {
            // exit fullscreen mode
            $(".popup-page").removeAttr('style');
          });
          
          // call swiper
          var swiper = new Swiper('.swiper-container', {
            nextButton: '.button-next',
            prevButton: '.button-prev',
            paginationClickable: true,
            slidesPerView: 5,
            spaceBetween: 5,
            breakpoints: {
                1024: {
                    slidesPerView: 4,
                    spaceBetween: 40
                },
                768: {
                    slidesPerView: 3,
                    spaceBetween: 30
                },
                640: {
                    slidesPerView: 2,
                    spaceBetween: 20
                },
                320: {
                    slidesPerView: 1,
                    spaceBetween: 10
                }
              }
            });
          }
        });
    });
    
    // get tour detail
    $(".popup-page").on('click','.list-tours-related ul > li', function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/tour-view';
      $.ajax({
        url : url,
        type : 'POST',
        dataType : "json",
        data: {id: id},
        beforeSend: function(){
          $(".views-popup").addClass('view');
          $(".views-popup").append('<div class="loading"></div>');
        },
        success : function (data){
          $( ".loading" ).remove();
          $(".views-popup .views-container").addClass('open');
          $(".views-container").empty().append(data.html);
          var slider = $('.royalSlider').royalSlider({
            fullscreen: {
              enabled: true,
              nativeFS: true
            },
            controlNavigation: 'thumbnails',
            autoScaleSlider: true, 
            autoScaleSliderWidth: 782,
            autoScaleSliderHeight: 478,
            loop: false,
            imageScaleMode: 'none',
            navigateByClick: true,
            numImagesToPreload:2,
            arrowsNav:true,
            arrowsNavAutoHide: true,
            arrowsNavHideOnTouch: true,
            keyboardNavEnabled: true,
            fadeinLoadedSlide: true,
            globalCaption: true,
            globalCaptionInside: false,
            imageScalePadding: 0,
            slidesSpacing: 0,
            thumbs: {
              appendSpan: true,
              firstMargin: true,
              paddingBottom: 4
            }
          }).data('royalSlider');
          $('.rsFullscreenBtn').click(function(e){
            slider.enterFullscreen();
            e.preventDefault();
          });
        }
      });
      
      

//    $(".views-popup").addClass('view');
//    $(".views-popup").css('display', 'block');
//    $(".views-popup .views-container").addClass('open');
    });
    // close detail
    $(".views-popup").on('click','.popup-close' ,function(){
      $(".views-popup").removeClass('on');
      $(".views-popup .popup-container").empty();
    });
    
    // close popup detail related
    $(".views-popup").on('click','.views-close' ,function(){
      $(".views-popup .views-container").removeClass('open');
      setTimeout(function () {
       $(".views-popup").removeClass('view');
       $(".views-popup .views-container").empty();
      }, 350);
    });
  });
</script>

 view detail related 
<div class="views-popup">
  <div class="views-container">
    
  </div>
</div>-->