<div class="views-header">
  <div class="row">
    <div class="col-md-10">
      <h2><span class="icon icon-location"></span> Khu du lịch đầm sen</h2>
    </div>
    <div class="col-md-2">
      <div class="views-close pull-right">
        <span class="icon icon-cancel-music"></span>
      </div>
    </div>
  </div>
</div>
<div class="views-content">
  <div class="views-content-wp">
    <div class="views-slider">
      <div class="royalSlider rsDefault">
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
        <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
      </div>
    </div>

    <h2>Giới thiệu</h2>
    <div class="description">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
    <div class="list-catelog">
      <h2>Bảng giá vé trọn gói (combo)</h2>
      <table class="game-entertainment">
        <thead>
          <tr>
            <th class="no">STT</th>
            <th class="name">Tên dịch vụ</th>
            <th class="price">Mô tả</th>
            <th class="price">Giá vé</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Vé trọn giói</td>
            <td>Bao gồm vé vào cồng và tất cả trò chơi.</td>
            <td>500.000đ/1 người</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Combo 20 trò chơi</td>
            <td>Tàu lượn siêu tốc, ...</td>
            <td>150.000đ/1 người</td>
          </tr>                   
        </tbody>
      </table>
    </div>

    <div class="list-catelog">
      <h2>Bảng giá trò chơi</h2>
      <table class="game-entertainment">
        <thead>
          <tr>
            <th class="no">STT</th>
            <th class="name">Tên dịch vụ</th>
            <th class="price">Giá người lớn</th>
            <th class="price">Giá trẻ em</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td colspan="4" class="colspan">Trò chơi cảm giác mạnh</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>5</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>                       
        </tbody>
        <tbody>
          <tr>
            <td colspan="4" class="colspan">Trò chơi giải trí - khám phá</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>
          <tr>
            <td>5</td>
            <td>Trượt tuyết</td>
            <td>150.000đ/1 người</td>
            <td>150.000đ/1 người</td>
          </tr>                       
        </tbody>
      </table>
    </div>

    <div class="list-catelog">
      <h2>Bảng giá vào cổng và phương tiện</h2>
      <table>
        <thead>
          <tr>
            <th class="no">STT</th>
            <th class="name">Tên dịch vụ</th>
            <th colspan="2">Giá vé</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td rowspan="2">1</td>
            <td rowspan="2">Vé vào cổng</td>
            <td>Người lớn</td>
            <td>90.000 đ</td>
          </tr>
          <tr>
            <td>Trẻ em</td>
            <td>50.000 đ</td>
          </tr>
          <tr>
            <td rowspan="3">2</td>
            <td rowspan="3">Vé giữ xe</td>
            <td>Xe số</td>
            <td>5.000 đ</td>
          </tr>
          <tr>
            <td>Xe tay ga</td>
            <td>10.000 đ</td>
          </tr>
          <tr>
            <td>Xe đạp</td>
            <td>2.000 đ</td>
          </tr>
          <tr>
            <td rowspan="2">&nbsp;3</td>
            <td rowspan="2">&nbsp;Xe lửa</td>
            <td>Người lớn</td>
            <td>90.000 đ</td>
          </tr>
          <tr>
            <td>Trẻ em</td>
            <td>70.000 đ</td>
          </tr>
          <tr>
            <td rowspan="2">4</td>
            <td rowspan="2">Vé giữ ô tô</td>
            <td>Dưới 10 chỗ</td>
            <td>20.000 đ</td>
          </tr>
          <tr>
            <td>Trên 10 chỗ</td>
            <td>40.000 đ</td>
          </tr>
          <tr>
            <td rowspan="2">5</td>
            <td rowspan="2">Taxi du lịch</td>
            <td>Dưới 10 chỗ</td>
            <td>200.000 đ</td>
          </tr>
          <tr>
            <td>Trên 10 chỗ</td>
            <td>400.000 đ</td>
          </tr>
          <tr>
            <td>6</td>
            <td>Vé võng</td>
            <td></td>
            <td>200.000 đ</td>
          </tr>
          <tr>
            <td>7</td>
            <td>Vé xe đẩy</td>
            <td></td>
            <td>200.000 đ</td>
          </tr>
          <tr>
            <td>8</td>
            <td>Vé giữ hành lý</td>
            <td></td>
            <td>200.000 đ</td>
          </tr>
          <tr>
            <td>9</td>
            <td>Vé xe lăn</td>
            <td></td>
            <td>200.000 đ</td>
          </tr>
          <tr>
            <td>10</td>
            <td>Vé nhà rông</td>
            <td></td>
            <td>200.000 đ</td>
          </tr>
        </tbody>
      </table>
    </div>



    <div class="comment">
      <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
      <ul class="list-comment">
        <li>
          <div class="comment-item">
            <div class="avartar">
               <img src="/tours/public/assets/demo/photo.jpg">
            </div>
            <div class="comment-content">
              <div class="comment-info">
                <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                <div class="list-gallery">
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                </div>
                <div class="form-replies">
                  <a class="fs-comment">
                    Trả lời
                  </a>
                  <a class="fs-like">
                    Thích (10)
                  </a>
                  <a class="fs-share">
                    Chia sẻ
                  </a>
                </div>
              </div>
              <div class="comment-replies">
                <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                <div class="comment-content">
                  <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                </div>
              </div>
            </div>
          </div>
        </li>

        <li>
          <div class="comment-item">
            <div class="avartar">
               <img src="/tours/public/assets/demo/photo.jpg">
            </div>
            <div class="comment-content">
              <div class="comment-info">
                <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                <div class="list-gallery">
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                </div>
                <div class="form-replies">
                  <a class="fs-comment">
                    Trả lời
                  </a>
                  <a class="fs-like">
                    Thích (10)
                  </a>
                  <a class="fs-share">
                    Chia sẻ
                  </a>
                </div>
              </div>
              <div class="comment-replies">
                <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                <div class="comment-content">
                  <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                </div>
              </div>
            </div>
          </div>
        </li>

        <li>
          <div class="comment-item">
            <div class="avartar">
               <img src="/tours/public/assets/demo/photo.jpg">
            </div>
            <div class="comment-content">
              <div class="comment-info">
                <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                <div class="list-gallery">
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                </div>
                <div class="form-replies">
                  <a class="fs-comment">
                    Trả lời
                  </a>
                  <a class="fs-like">
                    Thích (10)
                  </a>
                  <a class="fs-share">
                    Chia sẻ
                  </a>
                </div>
              </div>
              <div class="comment-replies">
                <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                <div class="comment-content">
                  <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                </div>
              </div>
            </div>
          </div>
        </li>

        <li>
          <div class="comment-item">
            <div class="avartar">
               <img src="/tours/public/assets/demo/photo.jpg">
            </div>
            <div class="comment-content">
              <div class="comment-info">
                <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                <div class="list-gallery">
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                  <a href="#">
                    <img src="/tours/public/assets/demo/photo.jpg">
                  </a>
                </div>
                <div class="form-replies">
                  <a class="fs-comment">
                    Trả lời
                  </a>
                  <a class="fs-like">
                    Thích (10)
                  </a>
                  <a class="fs-share">
                    Chia sẻ
                  </a>
                </div>
              </div>
              <div class="comment-replies">
                <div class="avartar"><img src="/tours/public/assets/demo/photo.jpg"></div>
                <div class="comment-content">
                  <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                </div>
              </div>
            </div>
          </div>
        </li>

      </ul>
      <div class="views-all">
        <a>Xem thêm</a>
      </div>
    </div>
  </div>


</div>