<div class="my-travel">
  <div id="map">
    
  </div>
  <div class="data">
      <div class="close-tab">
        <var class="icon icon-caret-left"></var>
      </div>
    <div class="title">
      <span class="avatar">
        
      </span>
      <div>
        <h1>Dấu chân du lịch</h1>
      </div>
    </div>
    
    <div class="create-share">
      <div class="item">
        <a href="#">
          <p><var class="icon icon-plus"></var></p>
          <p>Tạo mới</p>
        </a>
      </div>
      <div class="item">
        <a href="#">
          <p><var class="icon icon-star"></var></p>
          <p>Lưu</p>
        </a>
      </div>
      <div class="item">
        <a href="#"><p><var class="icon icon-share"></var></p>
        <p>Chia sẻ</p></a>
      </div>
    </div>
    
    <div class="list-my-travel">
      <ul>
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
        <li>
          <div class="item">
            <div class="date">20/12/2017</div>
            <div class="mytitle">
              Party company Phan Thiết
            </div>
            <div class="content">
              <ul>
                <?php for($i= 1; $i <=9; $i++) :?>
                <li>
                  <a href="#">
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
                <?php endfor; ?>
                <li>
                  <a href="#">
                    <div class="add">
                      <var class="icon icon-plus"></var>
                    </div>
                    <img src="<?php echo $this->basePath('/assets/demo/319604-khaisilk-thats-cafe-huong-vi-den-tu-my.jpg'); ?>">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
