<div class="views-cart">
  <div class="views-cart-item shopping-cart">
    <span class="num"><i>1</i></span>
    <a href="#">
      <var class="icon icon-cart-plus"></var>
    </a>
    
  </div>
  <div class="views-cart-item  call">
    
    <a href="#">
      <span class="img"><var class="icon icon-phone"></var></span>
      <span class="des">09 6666 0127</span>
    </a>
  </div>
  <div class="views-cart-item  help">
    <a href="#">
      <span class="img"><var class="icon icon-help-circled"></var></span>
      <span class="des">Trợ giúp</span>
    </a>
    
  </div>
  <div class="views-cart-item  language">
    <a href="#">
      <span class="img"><img src="<?php echo $this->basePath('/images/vi.png') ?>"/></span>
      <span class="des">Tiếng việt</span>
    </a>
<!--    <var class="icon icon-help-circled"></var>-->
  </div>
</div>