<div class="views-cart">
  <div class="views-cart-item shopping-cart">
    <span class="num"><i>1</i></span>
    <var class="icon icon-cart-plus"></var>
  </div>
  <div class="views-cart-item  call">
    <var class="icon icon-phone"></var>
  </div>
  <div class="views-cart-item  help">
    <var class="icon icon-help-circled"></var>
  </div>
  <div class="views-cart-item  language">
    <var class="icon icon-help-circled"></var>
  </div>
</div>