<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>
<li class="col-md-6">
  <div class="item">
    <div class="img">
      <div class="usr-order">
        <span class="icon icon-user-profile"> 1.5k người đã mua</span>
      </div>
      <div class="highlight"><span>Mới</span></div>
      <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></a>
      <div class="item-hover">
        <div class="item-voucher">
          ss
        </div>
        <div class="readmove">
          <a href="javascript:void(0);">Xem ngay</a>
        </div>
      </div>
    </div>
    <div class="item-content">
      <div class="title">
        <a href="javascript:void(0);">L'angfarm Buffet - Đặc Sản Đà Lạt</a>
      </div>
      <div class="address">
        771 Trần Hưng Đạo, P. 11, Quận 5, TP. HCM
      </div>

      <div class="view-user">
        <ul class="items-review">
          <li class="user-post-avatar">a</li>
          <li class="user-post">
            <a href="#"><b>Pham Van Long</b></a>
            <a href="#">Chổ này mới bán thôi mà thấy ngon sạch chiều xuống khách mua về nhìu Còn ...</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</li>