<header id="header">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="logo">
          
        </div>
        <ul id="menu-top">
          <li>
            <a href="<?php echo $this->url('travel', array('controller' => 'travel', 'action' => 'index')); ?>">Địa điểm đi chơi</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <h2>Địa điểm mới</h2>
                      <ul class="row">
                        <li class="col-md-2"><a href="#">Đà Lạt</a></li>
                        <li class="col-md-2"><a href="#">Nha Trang</a></li>
                        <li class="col-md-2"><a href="#">Phan Thiết</a></li>
                        <li class="col-md-2"><a href="#">Huế</a></li>
                        <li class="col-md-2"><a href="#">Đà Nẵng</a></li>
                        <li class="col-md-2"><a href="#">Bình Dương</a></li>
                        <li class="col-md-2"><a href="#">Hà Nội</a></li>
                        <li class="col-md-2"><a href="#">Hồ Chí Minh</a></li>
                        <li class="col-md-2"><a href="#">Vũng Tàu</a></li>
                        <li class="col-md-2"><a href="#">Phú Yên</a></li>
                        <li class="col-md-2"><a href="#">Bình Định</a></li>
                        <li class="col-md-2"><a href="#">Cần Thơ</a></li>
                        <li class="col-md-2"><a href="#">Bến Tre</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('tour', array('controller' => 'tour', 'action' => 'index')); ?>">Tìm tours du lịch</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <h2>Tour trong nước</h2>
                      <ul class="row">
                        <li class="col-md-2"><a href="#">Đà Lạt</a></li>
                        <li class="col-md-2"><a href="#">Nha Trang</a></li>
                        <li class="col-md-2"><a href="#">Phan Thiết</a></li>
                        <li class="col-md-2"><a href="#">Huế</a></li>
                        <li class="col-md-2"><a href="#">Đà Nẵng</a></li>
                        <li class="col-md-2"><a href="#">Bình Dương</a></li>
                        <li class="col-md-2"><a href="#">Hà Nội</a></li>
                        <li class="col-md-2"><a href="#">Hồ Chí Minh</a></li>
                        <li class="col-md-2"><a href="#">Vũng Tàu</a></li>
                        <li class="col-md-2"><a href="#">Phú Yên</a></li>
                        <li class="col-md-2"><a href="#">Bình Định</a></li>
                        <li class="col-md-2"><a href="#">Cần Thơ</a></li>
                        <li class="col-md-2"><a href="#">Bến Tre</a></li>
                      </ul>
                      <h2>Tour nước ngoài</h2>
                      <ul class="row">
                        <li class="col-md-2"><a href="#">Thái Lan</a></li>
                        <li class="col-md-2"><a href="#">Lào</a></li>
                        <li class="col-md-2"><a href="#">Singapore</a></li>
                        <li class="col-md-2"><a href="#">Mỹ</a></li>
                        <li class="col-md-2"><a href="#">Úc</a></li>
                        <li class="col-md-2"><a href="#">Dài Loan</a></li>
                        <li class="col-md-2"><a href="#">Trung Quốc</a></li>
                        <li class="col-md-2"><a href="#">Nhật Bản</a></li>
                        <li class="col-md-2"><a href="#">Hàn Quốc</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('hotel', array('controller' => 'hotel', 'action' => 'index')); ?>">Khách sạn</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <h2>Địa điểm mới</h2>
                      <ul class="row">
                        <li class="col-md-2"><a href="#">Đà Lạt</a></li>
                        <li class="col-md-2"><a href="#">Nha Trang</a></li>
                        <li class="col-md-2"><a href="#">Phan Thiết</a></li>
                        <li class="col-md-2"><a href="#">Huế</a></li>
                        <li class="col-md-2"><a href="#">Đà Nẵng</a></li>
                        <li class="col-md-2"><a href="#">Bình Dương</a></li>
                        <li class="col-md-2"><a href="#">Hà Nội</a></li>
                        <li class="col-md-2"><a href="#">Hồ Chí Minh</a></li>
                        <li class="col-md-2"><a href="#">Vũng Tàu</a></li>
                        <li class="col-md-2"><a href="#">Phú Yên</a></li>
                        <li class="col-md-2"><a href="#">Bình Định</a></li>
                        <li class="col-md-2"><a href="#">Cần Thơ</a></li>
                        <li class="col-md-2"><a href="#">Bến Tre</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php echo $this->url('taste', array('controller' => 'taste', 'action' => 'index')); ?>">Điểm ăn uống</a>
            <div class="item-menu-level">
              <div class="container">
                <div class="row">
                  <div class="col-md-12">
                    <div class="item-level">
                      <h2>Địa điểm ăn uống</h2>
                      <ul class="row">
                        <li class="col-md-2"><a href="#">Nhà Hàng</a></li>
                        <li class="col-md-2"><a href="#">Quán Ăn Vẻ Hè</a></li>
                        <li class="col-md-2"><a href="#">Quán Nhậu</a></li>
                        <li class="col-md-2"><a href="#">Ăn Vặt</a></li>
                        <li class="col-md-2"><a href="#">Sang Trọng</a></li>
                        <li class="col-md-2"><a href="#">Trà Sữa</a></li>
                        <li class="col-md-2"><a href="#">Kem</a></li>
                        <li class="col-md-2"><a href="#">Tiện Bánh</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <a href="<?php // echo $this->url('video', array('controller' => 'video', 'action' => 'index')); ?>">Video</a>
          </li>
          <li>
            <a href="<?php echo $this->url('diary', array('controller' => 'diary', 'action' => 'index')); ?>">Nhật ký</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3">
        <u id="login" class="pull-right">
          <li>
            <a href="<?php echo $this->url('register', array('controller' => 'public', 'action' => 'register')); ?>">Đăng ký </a> /
            <a href="<?php echo $this->url('login', array('controller' => 'public', 'action' => 'login')); ?>">Đăng nhập </a>
          </li>
        </u>
      </div>
    </div>
  </div>
</header>