<div class="header">
  <div class="container-fluid">
    <div class="col-md-12">
      <ul id="menu-top" class="pull-right">
        <li>
          <a href="#">Địa điểm phượt</a>
        </li>
        <li>
          <a href="#">Tìm tours</a>
        </li>
        <li>
          <a href="#">Khách sạn</a>
        </li>
        <li>
          <a href="#">Điểm ăn uống</a>
        </li>
        <li>
          <a href="#">Nhật ký</a>
        </li>
        <li>
          <a href="#">Tin tức</a>
        </li>
      </ul>
    </div>
  </div>
</div>