<div class="content-header">
    <div class="user-breadcrumb">
      <ol class="breadcrumb">
        <li>Trang chủ</li>
        <li class="active">Tạo điểm du lịch</li>
      </ol>
    </div>
</div>
  <div class="post">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a href="<?php echo $this->url('user/travel', array('action' => 'edit', 'id' => '1')); ?>">Tổng quan</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'gallery', 'id' => '1')); ?>">Thư viện ảnh</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainment', 'id' => '1')); ?>">Tạo trò chơi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainmentPromotion', 'id' => '1')); ?>" >Tạo bảng giá khuyến mãi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainmentGallery', 'id' => '1')); ?>">Ảnh trò chơi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'video', 'id' => '1')); ?>">Video</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'support', 'id' => '1')); ?>">Thông tin hỗ trợ</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'service', 'id' => '1')); ?>">Gói dịch vụ</a></li>
            </ul>
            
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="default">
                <div class="row">
                  <div class="col-md-6">
                      <div class="body-tab">
                        <fieldset>
                          <legend>
                            <span>Thông tin chung</span>
                          </legend>
                          <div class="form-group">
                            <label for="category-name">Tiêu đề</label>
                            <input type="text" class="form-control" id="category-name" placeholder="Tên chuyên mục">
                          </div>

                          <div class="form-group">
                            <label for="permark-link">Permark Link</label>
                            <input type="text" class="form-control" id="permark-link" placeholder="Permark Link">
                          </div>

                          <div class="form-group">
                            <label>Danh mục </label>
                            <select class="form-control selectpicker">
                              <option selected="selected">Alabama</option>
                              <option>Alaska</option>
                              <option>California</option>
                              <option>Delaware</option>
                              <option>Tennessee</option>
                              <option>Texas</option>
                              <option>Washington</option>
                            </select>
                          </div>

                          <div class="form-group">
                            <label for="category-name">Mô tả</label>
                            <textarea class="form-control" rows="10"></textarea>
                          </div>


                          <div class="form-group">
                            <label class="" for="image">Hình ảnh</label>
                            <div class="view-upload-image">
                              <a href="#" id="thumb-image" data-toggle="image" class="img-thumbnail">
                                <img src="http://shopmazavn.chiliweb.org/image/cache/no_image-100x100.png" alt="" title="" data-placeholder="">
                              </a>
                            </div>
                            <input type="hidden" id="image" name="image">
                          </div>

                          
                        </fieldset>


 

                    <fieldset>
                      <legend>
                        <span>Địa chỉ</span>
                      </legend>
                      <div class="form-group">
                        <label for="menu-order">Số nhà</label>
                        <input type="text"  value="" class="form-control" id="menu-order">
                      </div>
                      <div class="form-group">
                        <label for="menu-order">Tên đường</label>
                        <input type="text"  value="" class="form-control" id="menu-order">
                      </div>
                      <div class="form-group">
                        <label>Quốc gia</label>
                        <select class="form-control selectpicker">
                          <option selected="selected">-- Chọn -- </option>
                          <option>Alaska</option>
                          <option>California</option>
                          <option>Delaware</option>
                          <option>Tennessee</option>
                          <option>Texas</option>
                          <option>Washington</option>
                        </select>
                      </div>

                      <div class="form-group">
                        <label>Tỉnh / Thành Phố</label>
                        <select class="form-control selectpicker">
                          <option selected="selected">-- Chọn -- </option>
                          <option>Alaska</option>
                          <option>California</option>
                          <option>Delaware</option>
                          <option>Tennessee</option>
                          <option>Texas</option>
                          <option>Washington</option>
                        </select>
                      </div>

                      <div class="form-group">
                        <label>Quận / Huyện</label>
                        <select class="form-control selectpicker">
                          <option selected="selected">-- Chọn -- </option>
                          <option>Alaska</option>
                          <option>California</option>
                          <option>Delaware</option>
                          <option>Tennessee</option>
                          <option>Texas</option>
                          <option>Washington</option>
                        </select>
                      </div>

                      <div class="form-group">
                        <label>Phường / Xã</label>
                        <select class="form-control selectpicker">
                          <option selected="selected">-- Chọn -- </option>
                          <option>Alaska</option>
                          <option>California</option>
                          <option>Delaware</option>
                          <option>Tennessee</option>
                          <option>Texas</option>
                          <option>Washington</option>
                        </select>
                      </div>
                    </fieldset>
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="body-tab">

                        <fieldset>
                      <legend>
                        <span>Hỗ trợ SEO</span>
                      </legend>
                      <div class="form-group">
                        <label for="meta-tag-title">Meta Tag Title</label>
                        <input type="text" class="form-control" id="meta-tag-title" placeholder="Meta Tag Title">
                      </div>

                      <div class="form-group">
                        <label for="meta-tag-title">Meta Tag Description</label>
                        <textarea class="form-control" rows="5" placeholder="Meta Tag Description:"></textarea>
                      </div>

                      <div class="form-group">
                        <label for="meta-tag-title">Meta Tag Keywords</label>
                        <textarea class="form-control" rows="5" placeholder="Meta Tag Keywords:"></textarea>
                      </div>
                    </fieldset>

                    <fieldset>
                      <legend>
                        <span>Hiển thị</span>
                      </legend>
                      <div class="row">
                        <div class="col-md-12">
                          <div class="row">
                            <div class="col-md-6">
                              <div class="form-group">
                                <label for="menu-order">Thứ tự</label>
                                <input type="number" min="0" value="0" class="form-control" id="menu-order">
                              </div>
                              <div class="form-group">
                                <label>Trạng thái</label>
                                <select class="form-control">
                                  <option>Bật</option>
                                  <option>Tắt</option>
                                </select>
                              </div>

                              <div class="form-group">
                                <label for="menu-order">Giờ mở cửa</label>
                                <input type="time" value="" class="form-control" id="menu-order">
                              </div>

                              <div class="form-group">
                                <label for="menu-order">Giờ đóng cửa</label>
                                <input type="time" value="" class="form-control" id="menu-order">
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label>
                                      <input type="checkbox"> Hiện trên menu
                                    </label>
                                  </div>
                                  <div class="form-group">
                                    <label>
                                      <input type="checkbox"> Hot
                                    </label>
                                  </div>
                                  <div class="form-group">
                                    <label>
                                      <input type="checkbox"> New
                                    </label>
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label>
                                      <input type="checkbox"> Sticky
                                    </label>
                                  </div>

                                  <div class="form-group">
                                    <label>
                                      <input type="checkbox"> Promotion
                                    </label>
                                  </div>

                                  <div class="form-group">
                                    <label>
                                      <input type="checkbox"> Highlight
                                    </label>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </fieldset>

                      </div>
                  </div>
                  
                  <div class="col-md-12">
                    <div class="body-tab">
                      <fieldset>
                        <legend>
                          <span>Nội dung</span>
                        </legend>
                        <div class="form-group">
                          
                          <textarea class="form-control" rows="5" placeholder="Nội dung"></textarea>
                        </div>
                      </fieldset>
                    </div>
                  </div>
                  
                  <div class="col-md-12">
                    <div class="body-tab">
                      <button type="submit" class="btn btn-default">Reset</button>
                        <button type="submit" class="btn btn-info">Đi tiếp</button>
                    </div>
                  </div>
                </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>