<div class="content-header">
    <div class="user-breadcrumb">
      <ol class="breadcrumb">
        <li>Trang chủ</li>
        <li class="active">Tạo điểm du lịch</li>
      </ol>
    </div>
</div>
  <div class="post">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'edit', 'id' => '1')); ?>">Tổng quan</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'gallery', 'id' => '1')); ?>">Thư viện ảnh</a></li>
              <li role="presentation" class="active"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainment', 'id' => '1')); ?>">Tạo trò chơi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainmentPromotion', 'id' => '1')); ?>" >Tạo bảng giá khuyến mãi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainmentGallery', 'id' => '1')); ?>">Ảnh trò chơi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'video', 'id' => '1')); ?>">Video</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'support', 'id' => '1')); ?>">Thông tin hỗ trợ</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'service', 'id' => '1')); ?>">Gói dịch vụ</a></li>
            </ul>
            
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="entertaiment">
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-6">
                        <fieldset>
                          <legend>
                            <span>Thông tin chung</span>
                          </legend>
                          <div class="form-group">
                            <label>
                              <input type="radio" checked="" name="entertaiment"> Trò chơi
                            </label>
                          </div>
                          <div class="form-group">
                            <label>
                              <input type="radio" name="entertaiment"> Điểm tham quan
                            </label>
                          </div>
                          <div class="form-group">
                            <label for="category-name">Tên trò chơi</label>
                            <input type="text" class="form-control" id="category-name" placeholder="Tên chuyên mục">
                          </div>

                          <div class="form-group">
                            <label>Nhóm trò chơi </label>
                            <select class="form-control selectpicker">
                              <option selected="selected">Trò chơi cảm giác mạnh</option>
                              <option>Trò chơi giải trí - khám phá</option>
                            </select>
                          </div>
                          
                          <div class="form-group">
                            <label for="category-name">Mô tả</label>
                            <textarea class="form-control" rows="10"></textarea>
                          </div>
                          
                          <div class="form-group">
                            <label for="category-name">Lịch sử</label>
                            <textarea class="form-control" rows="10"></textarea>
                          </div>
                          
                          <div class="form-group">
                            <label>
                              <input type="checkbox"> Vé trọn gói (combo)
                            </label>
                          </div>
                        </fieldset>
                      </div>
                      <div class="col-md-6">
                        <fieldset>
                          <legend>
                            <span>Giá mặc định</span>
                          </legend>
                          <div class="form-group">
                            <label for="category-name">Người lớn</label>
                            <input type="text" class="form-control" id="category-name" placeholder="Tên chuyên mục">
                          </div>

                          <div class="form-group">
                            <label for="category-name">Trẻ em</label>
                            <input type="text" class="form-control" id="category-name" placeholder="Tên chuyên mục">
                          </div>
                        </fieldset>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
              

              
          </div>
        </div>
      </div>
    </div>
  </div>