<div class="content-header">
    <div class="user-breadcrumb">
      <ol class="breadcrumb">
        <li>Trang chủ</li>
        <li class="active">Tạo điểm du lịch</li>
      </ol>
    </div>
</div>
  <div class="post">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'edit', 'id' => '1')); ?>">Tổng quan</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'gallery', 'id' => '1')); ?>">Thư viện ảnh</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainment', 'id' => '1')); ?>">Tạo trò chơi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainmentPromotion', 'id' => '1')); ?>" >Tạo bảng giá khuyến mãi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'entertainmentGallery', 'id' => '1')); ?>">Ảnh trò chơi</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'video', 'id' => '1')); ?>">Video</a></li>
              <li role="presentation"><a href="<?php echo $this->url('user/travel', array('action' => 'support', 'id' => '1')); ?>">Thông tin hỗ trợ</a></li>
              <li role="presentation" class="active"><a href="<?php echo $this->url('user/travel', array('action' => 'service', 'id' => '1')); ?>">Gói dịch vụ</a></li>
            </ul>
            
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="service-price">
                  <div class="box-body">
                    <div class="add-muilti-gallery">
                      <a href="#" class="btn btn-info pull-right"><i class="fa fa-plus-circle" aria-hidden="true"></i> Lưu</a>
                    </div>
                    <ul>
                      <li>
                        <div class="item-service">
                          Miễn phí
                        </div>
                      </li>
                      <li>
                        <div class="item-service">
                          Miễn phí
                        </div>
                      </li>
                      <li>
                        <div class="item-service">
                          Miễn phí
                        </div>
                      </li>
                      <li>
                        <div class="item-service">
                          Miễn phí
                        </div>
                      </li>
                      
                    </ul>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>