<div class="breadcrumb-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
          <li><a href="#"><var class="icon icon-home"></var> Trang chủ</a></li>
          <li class="active">Du lịch</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      
      <div class="popup-content">
        <div class="popup-header">
          <h1 id="full-title" data-id="<?php echo $dataPost->id; ?>"><?php echo $dataPost->name; ?></h1>
        </div>
        <div class="popup-body">
          <div class="row">
            <div class="col-md-8">
              <?php if ($gallery): ?>
              <div class="row">
                <div class="col-md-12">
                  <div class="slider">
                    <div class="royalSlider rsDefault">
                      <?php foreach ($gallery as $value): ?>
                        <img class="rsImg" src="<?php echo SERVER_IMAGE . '/' . $value['name']; ?>" data-rsTmb="<?php echo SERVER_IMAGE . '/100x80/' . $value['name']; ?>" alt="image description" />
                      <?php endforeach; ?>
                    </div>
                  </div>
                </div>
              </div>
              <?php endif; ?>
              <div class="row">
                <div class="col-md-12">
                <div class="content-page-popup">
                  <div class="row">
                    <div class="col-md-12 about">
                      <ul class="tab-travel">
                        <li data-id="about" class="active"><h2>Giới thiệu</h2></li>
                        <li data-id="table-price"><h2>Bảng giá</h2></li>
                        <li data-id="history"><h2>Lịch sử</h2></li>
                        <li data-id="video"><h2>Video</h2></li>
                        <li data-id="rating"><h2>Đánh giá</h2></li>
                        <li data-id="comment"><h2 data-toggle="modal" data-target="#modal-comment"> Bình luận</h2></li>
                      </ul>
                      <div class="content">
                        <div class="description">
                          <?php echo $dataPost->about; ?>
                        </div>
                        <?php //echo '<pre>'; var_dump($dataEntertainment);  ?>
                        <?php if ($dataEntertainment): ?>
                          <?php
                          foreach ($dataEntertainment as $value):
//                    var_dump($value['type'] );
                            ?>
                            <?php if ((int) $value['type'] == 1): ?>
                              <?php if ($value['dataChild']): ?>
                                <div id="table-price" class="list-catelog">
                                  <h2 class="title"><?php echo $value['name']; ?> 12</h2>
                                  <table class="game-entertainment">
                                    <thead>
                                      <tr>
                                        <th class="no">STT</th>
                                        <th class="name">Tên dịch vụ</th>
                                        <th class="price">Mô tả</th>
                                        <th>Giá vé người lớn</th>
                                        <th>Giá vé trẻ em</th>
                                      </tr>
                                    </thead>

                                    <tbody>
                                      <?php foreach ($value['dataChild'] as $k => $child): ?>
                                        <tr>
                                          <td><?php echo $k + 1; ?></td>
                                          <td><?php echo $child['name']; ?></td>
                                          <td><?php echo $child['description']; ?></td>
                                          <td><?php echo number_format($child['price_adult'], 0, '.', '.') ?>đ /1 người</td>
                                          <td><?php echo number_format($child['price_child'], 0, '.', '.') ?>đ /1 người</td>
                                        </tr>
                                      <?php endforeach; ?>
                                    </tbody>

                                  </table>
                                </div>
                              <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($value['type'] == 2): ?>
                              <?php if ($value['child'] != ''): ?>
                                <div class="list-catelog">
                                  <h2 class="title"><?php echo $value['name']; ?></h2>
                                  <table class="game-entertainment">
                                    <thead>
                                      <tr>
                                        <th class="no">STT</th>
                                        <th class="name">Tên dịch vụ</th>
                                        <th class="price">Giá người lớn</th>
                                        <th class="price">Giá trẻ em</th>
                                        <th class="price"></th>
                                      </tr>
                                    </thead>
                                    <?php foreach ($value['child'] as $v): ?>
                                      <?php if ($v['dataChild']): ?>
                                        <tbody>
                                          <tr>
                                            <td colspan="5" class="colspan"><?php echo $v['name']; ?></td>
                                          </tr>

                                          <?php foreach ($v['dataChild'] as $i => $r): ?>
                                            <tr>
                                              <td><?php echo $i + 1; ?></td>
                                              <td><?php echo $r['name']; ?></td>
                                              <td><?php echo number_format($r['price_adult'], 0, '.', '.'); ?>đ /1 người</td>
                                              <td><?php echo number_format($r['price_child'], 0, '.', '.'); ?>đ /1 người</td>
                                              <td>
                                                <?php
                                                $entertainmentImage = Category\Util\EntertainmentGallery::getListEntertainmentGallery(array('entertainment_id' => $r['id']));
                                                if ($entertainmentImage):
                                                  ?>
                                                  <a data-id="<?php echo $r['id']; ?>" class="history" href="javascript:void(0);">
                                                    <div class="view-gallery">Xem album ảnh</div>
                                                    <i class="icon icon-photo"></i></a>
                                                <?php endif; ?>
                                              </td>
                                            </tr>
                                          <?php endforeach; ?>
                                        </tbody>
                                      <?php endif; ?>
                                    <?php endforeach; ?>
                                  </table>
                                </div>
                              <?php endif; ?>
                            <?php endif; ?>
                          <?php endforeach; ?>
                        <?php endif; ?>
                        <?php if ($dataVehicle): ?>
                          <div class="list-catelog">
                            <h2 class="title">Bảng giá phương tiện</h2>
                            <table>
                              <thead>
                                <tr>
                                  <th class="no">STT</th>
                                  <th class="name">Tên dịch vụ</th>
                                  <th style="width: 20%;">Giá vé</th>
                                </tr>
                              </thead>
                              <tbody>
                                <?php foreach ($dataVehicle as $k => $value): ?>
                                  <tr>
                                    <td><?php echo $k + 1; ?></td>
                                    <td><?php echo $value['name']; ?></td>
                                    <td class="price"><?php echo number_format($value['price'], 0, '.', '.'); ?> đ</td>
                                  </tr>
                                <?php endforeach; ?>
                              </tbody>
                            </table>
                          </div>
                        <?php endif; ?>
                      </div>
                      <div id="load-video">

                      </div>

                      <div id="page-comment">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="list-related">
                <div class="map-content">
                  <h2>Địa điểm khác gần Đầm sen</h2>
                  <div class="related-item">
                    <div class="map-related" id="map-related"></div>
                    <div class="list-icon-support">
                      <ul>
                        <li class="current"><span></span> Địa điểm hiện tại</li>
                        <li class="tours"><span></span> Địa du lịch</li>
                        <li class="hotel"><span></span> Khách sạn</li>
                        <li class="taste"><span></span> Địa điểm ăn uống</li>
                        <li class="park"><span></span> Công viên - giải trí</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <?php if ($dataPostContact): ?>
                  <div class="support">
                    <h2>Liên hệ đặt trực tuyến</h2>
                    <ul>
                      <?php foreach ($dataPostContact as $cotnact): ?>
                        <li>
                          <div class="item">
                            <div class="icon">

                            </div>
                            <div class="content-support">
                              <p class="name"><?php echo $cotnact['name']; ?></p>
                              <p><a href="#"><?php echo $cotnact['email']; ?></a></p>
                              <p class="hotline">Hotline: <?php echo $cotnact['hotline']; ?></p>
                            </div>
                          </div>
                        </li>
                      <?php endforeach; ?>
                    </ul>
                  </div>
                <?php endif; ?>
              </div>
              <?php if ($dataPostRelated): ?>
                <div class="list-related list-province-item">
                  <h2 class="title"><span>Địa điểm khác</span></h2>
                  <ul class="list-travel">
                    <?php
                    foreach ($dataPostRelated as $key => $value):
                      $listTotal = \Category\Util\UtilEntertainment::getTotalEntertainmentByPost(array('post_id' => $value['id']));
                      ?>
                      <li>
                        <div class="item">
                          <div class="row">
                            <div class="col-md-12">
                              <div class="item-img">
                                <a href="<?php echo $this->url('detail', array('slug' => $value['post_slug'], 'id' => $value['id'])) ?>" title="<?php echo $value['name'] ?>">
                                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                                  <div class="overlay_border"></div>
                                </a>
                              </div>
                            </div>
                            <div class="col-md-12">
                              <div class="item-des">
                                <h2><a href="<?php echo $this->url('detail', array('slug' => $value['post_slug'], 'id' => $value['id'])) ?>" title="<?php echo $value['name']; ?>"><?php echo $value['name']; ?></a></h2>
                                <p class="address">
                                  <?php echo $value['address']; ?>, 
                                  <?php echo $value['ward_type']; ?>  <?php echo $value['ward_name']; ?>, 
                                  <?php echo $value['district_type']; ?> <?php echo $value['district_name']; ?>,
                                  <?php echo $value['province_type']; ?> <?php echo $value['province_name']; ?>, 
                                  <?php echo $value['nation_type']; ?> <?php echo $value['nation_name']; ?>
                                </p>
                                <p class="hour-open">
                                  <span class="time">
                                    <var class="icon icon-clock-o"> </var> Thời gian hoạt động:</span>
                                  <var>08:00 AM - 20:00 PM - thứ 2 đến thứ 7. Chủ nhật và các ngày lễ nghỉ.</var>
                                </p>

                                <div class="fs-game">

                                  <?php if ($listTotal): ?>
                                    <ul class="list-game">
                                      <?php foreach ($listTotal as $val): ?>
                                        <?php if ($val['type'] == 1): ?>
                                          <li><span class="game icon icon-technology"></span> <?php echo $val['count']; ?> trò chơi</li>
                                        <?php endif; ?>

                                        <?php if ($val['type'] == 2): ?>
                                          <li><span class="tours icon icon-photographer"></span> <?php echo $val['count']; ?> điểm tham quan</li>
                                        <?php endif; ?>
                                      <?php endforeach; ?>
                                    </ul>
                                  <?php endif; ?>

                                  <a class="views" href="<?php echo $this->url('detail', array('slug' => $value['post_slug'], 'id' => $value['id'])) ?>" title="Xem ngay">Xem ngay</a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </li>
                    <?php endforeach; ?>
                  </ul>
                </div>
              <?php endif; ?>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>





