<div class="list-container-view">
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> <?php echo ($category) ? $category->name: ''; ?> <?php echo ($regionExists) ? $regionExists->type .' '. $regionExists->name: ''; ?></h1>
    </div>
  </div>
  <div class="province-container">
    <div class="province">
      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
    </div>
    <?php if($paginator): ?>
    <div class="list-province-item">
      <ul class="list-travel">
        <?php foreach ($paginator as $value): ?>
        <li>
          <div class="item">
            <div class="row">
              <div class="col-md-5">
                <div class="item-img">
                  <a href="javascript:void(0);" title="dam sen">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    <div class="overlay_border"></div>
                  </a>
                </div>
                <p class="strict-views"><span class="icon icon-person"></span> Bấm xem đường đi</p>
              </div>
              <div class="col-md-7">
                <h2><a href="javascript:void(0);" title="dam sen"><?php echo $value->name; ?></a></h2>
                <p class="address">Tầng 24 - 25, Tower, 76A Lê Lai, Quận 1, TP. HCM</p>
                <p class="hour-open"><span>Giờ mở cửa:</span> 08:00 AM - 20:00 PM</p>
                <div class="fs-game">
                  <ul class="list-game">
                    <li><span class="game icon icon-technology"></span> 150 trò chơi</li>
                    <li><span class="restaurant icon icon-cutlery"></span> 150 nhà hàng</li>
                    <li><span class="tours icon icon-photographer"></span> 15 điểm tham quan</li>
                  </ul>
                  <a class="views" href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                </div>
              </div>
            </div>
          </div>
        </li>
        <?php endforeach; ?>
      </ul>
    </div>
    
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <?php var_dump($page); ?>
        <div class="paging">
            <?php
            echo $this->paginationControl($paginator, 'Sliding', 'paginationAjax', array(
                $this->route,
                'category' => $category->slug,
            ));
            ?>
        </div>
      </div>
    </div>
    <?php endif; ?>
  </div>
  <div class="footer-travel">
    <?php $this->footerTravel(); ?>
  </div>
</div>