<?php $this->meta(
        $category->name . ' ' .$regionExists->name
        ); ?>  
<div class="list-container-view">
  <?php $this->searchAdvance(); ?>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> <?php echo ($category) ? $category->name: ''; ?> <?php echo ($regionExists) ? $regionExists->type .' '. $regionExists->name: ''; ?></h1>
    </div>
  </div>
  <div class="province-container">
    <div class="province">
      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
    </div>
    <div class="list-province-item">
      <ul class="list-travel">
        
      </ul>
    </div>
    
<!--    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="paging">
            <?php
//            echo $this->paginationControl($paginator, 'Sliding', 'paginationAjax', array(
//                $this->route,
//                'category' => $category->slug,
//                'province' => $province,
//                'district' => $district,
//                'nation' => $nation,
//                'page' => $page
//            ));
            ?>
        </div>
      </div>
    </div>-->
  </div>
  <div class="footer-travel">
    <?php $this->footerTravel(); ?>
  </div>
</div>
