<?php 
if($paginator->getTotalItemCount() > 0): ?>
        <?php foreach ($paginator as $key => $value): 
          $listTotal = \Category\Util\UtilEntertainment::getTotalEntertainmentByPost(array('post_id' => $value->id));
          ?>
<li data-id="<?php echo $key; ?>" class="post" id="key-map-<?php echo $key; ?>">
          <div class="item">
            <div class="row">
              <div class="col-md-5">
                <div class="item-img">
                  <a href="javascript:void(0);" data-id="<?php echo $value->id; ?>" title="<?php echo $value->name; ?>">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    <div class="overlay_border"></div>
                  </a>
                </div>
              </div>
              <div class="col-md-7">
                <h2><a href="javascript:void(0);" data-id="<?php echo $value->id; ?>" title="<?php echo $value->name; ?>"><?php echo $value->name; ?></a></h2>
                <p class="address">
                  <?php echo $value->address; ?>, 
                  <?php echo $value->ward_type; ?>  <?php echo $value->ward_name; ?>, 
                  <?php echo $value->district_type; ?> <?php echo $value->district_name; ?>,
                  <?php echo $value->province_type; ?> <?php echo $value->province_name; ?>, 
                  <?php echo $value->nation_type; ?> <?php echo $value->nation_name; ?>
                </p>
                <p class="hour-open">
                  <span class="time">
                    <var class="icon icon-clock-o"> </var> Thời gian hoạt động:</span>
                    <var>08:00 AM - 20:00 PM - thứ 2 đến thứ 7. Chủ nhật và các ngày lễ nghỉ.</var></p>
                <div class="fs-game">
                  <ul class="list-game">
                    <?php if($listTotal): ?>
                    <?php foreach ($listTotal as $val): ?>
                    <?php if($val['type'] == 1): ?>
                    <li><span class="game icon icon-technology"></span> <?php echo $val['count']; ?> trò chơi</li>
                    <?php endif; ?>
                    
                    <?php if($val['type'] == 2): ?>
                    <li><span class="tours icon icon-photographer"></span> <?php echo $val['count']; ?> điểm tham quan</li>
                    <?php endif; ?>
                    <?php endforeach; ?>
                    <?php endif; ?>
                    <li><p data-id="<?php echo $value->id; ?>" class="strict-views"><span class="icon icon-location-pin-on-map"></span> Bấm xem đường đi</p></li>
                  </ul>
                  <a class="views" href="javascript:void(0);" data-id="<?php echo $value->id; ?>" title="Xem ngay">Xem ngay</a>
                </div>
              </div>
            </div>
          </div>
        </li>
        <?php endforeach; ?>
        <li>
          <div class="paging">
            <?php
            echo $this->paginationControl($paginator, 'Sliding', 'paginationAjax', array(
                $this->route,
                'category' => $category->slug,
                'province' => $province,
                'district' => $district,
                'nation' => $nation,
                'page' => $page,
                'filter' => $filter,
                'sort' => $sort,
                'star' => $star,
                'min' => $min,
                'max' => $max,
                'area' => $area,
                'keyword' => $keyword
            ));
            ?>
        </div>
        </li>
        <?php else: ?>
        <li>
          <div class="data-empty">Dữ liệu đang cập nhât.</div>
        </li>
    <?php endif; ?>
