<div class="views-header">
  <div class="row">
    <div class="col-md-10">
      <h2><span class="icon icon-location"></span> Hướng dẫn đường đến đầm sem</h2>
    </div>
    <div class="col-md-2">
      <div class="views-close pull-right">
        <span class="icon icon-cancel-music"></span>
      </div>
    </div>
  </div>
</div>
<div class="views-content">
  <div class="views-content-wp map">
    <div id="view-map" style="width: 100%;height: 100%;"></div>
  </div>
</div>