<div class="warpper-video">
  <div class="close-video"><var class="icon icon-cancel-music"></var></div>
  <div class="container">
    <div class="content-video">
      <div class="row">
        <div class="col-md-8">
          <div class="player-container">
            <div class="player-position">
               <div id="player"></div>
            </div>
          </div>
          <div class="watch-header">
            <div class="watch7-headline">
              <h1 class="watch-title-container">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</h1>
            </div>
            <div class="watch-user-header">
              <div class="view">
                  1,621,070 views
                </div>
            </div>
            <div class="watch-action-buttons">
              <div class="watch-secondary-actions">
                <ul class="share">
                  <li><a href="#"><span>Chia sẻ lên facebook</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên google+</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên twiter</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên introgram</span></a></li>
                </ul>
              </div>
              <div class="watch-sentiment-actions">

                <span class="like"><var class="icon icon-thumbs-up-hand-symbol"></var> 123,545</span>
                <span class="unlike"><var class="icon icon-thumbs-up-hand-symbol"></var> 158</span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <a href="#"><img src="<?php echo $this->basePath('/assets/banner-video.jpg'); ?>"></a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="list-video">
            <ul class="row">
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="video-item">
                  <div class="video-thumbnail">
                    <a href="#">
                      <div class="play-icon">
                        <span class="icon icon-play-button">

                        </span>
                      </div>
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></a>
                  </div>
                  <div class="content">
                    <a class="title" href="#">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</a>
                    <p>
                      <a class="author" href="#">Bike Legend</a>
                    </p>
                    <p class="view">1,182,384 views</p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<script type="text/javascript">

// initialize jwplayer
var playerInstance = jwplayer('player');

// player dom elements
var playerContainerEl = document.querySelector('.player-container');

// returns video player position from top of document
function getElementOffsetTop(el) {
  var boundingClientRect = el.getBoundingClientRect();
  var bodyEl = document.body;
  var docEl = document.documentElement;
  var scrollTop = window.pageYOffset || docEl.scrollTop || bodyEl.scrollTop;
  var clientTop = docEl.clientTop || bodyEl.clientTop || 0;
  return Math.round(boundingClientRect.top + scrollTop - clientTop);
}

// returns the current y scroll position
function getScrollTop() {
  var docEl = document.documentElement;
  return (window.pageYOffset || docEl.scrollTop) - (docEl.clientTop || 0);
}

// configure jwplayer instance
playerInstance.setup({
  autostart: false,
  file: '//content.jwplatform.com/manifests/vM7nH0Kl.m3u8',
  primary: 'html5',
  setFullscreen: true,
  width: '100%'
});

// when jwplayer instance is ready
playerInstance.on('ready', function() {
        var config = playerInstance.getConfig();
        var utils = playerInstance.utils;
        // get height of player element
        var playerHeight = config.containerHeight;

        // get player element position from top of document
        var playerOffsetTop = getElementOffsetTop(playerContainerEl);

        // set player container to match height of actual video element
        // this prevents container from disappearing and changing element positions
        // on page when player becomes minimized. this also leaves a nice visual
        // placeholder space for minimized player to return to when appropriate
        playerContainerEl.style.height = playerHeight + 'px';

        // below we handle window scroll event without killing performance
        // this is a minimal approach. please consider implementing something more extensive:
        // i.e. http://joji.me/en-us/blog/how-to-develop-high-performance-onscroll-event

        // determine player display when scroll event is called
        // if inline player is no longer visible in viewport, add class
        // .player-minimize to minimize and float. otherwise, remove the class to put
        // player back to inline inline position
        function onScrollViewHandler() {
            var minimize = getScrollTop() >= playerOffsetTop;

            utils.toggleClass(playerContainerEl, 'player-minimize', minimize);
            // update the player's size so the controls are adjusted
            playerInstance.resize();
        }

        // namespace for whether or not we are waiting for setTimeout() to finish
        var isScrollTimeout = false;

        // window onscroll event handler
        window.onscroll = function() {
            // skip if we're waiting on a scroll update timeout to finish
            if (isScrollTimeout) return;
            // flag that a new timeout will begin
            isScrollTimeout = true;
            // otherwise, call scroll event view handler
            onScrollViewHandler();
            // set new timeout
            setTimeout(function() {
                // reset timeout flag to false (no longer waiting)
                isScrollTimeout = false;
            }, 80);

        };

    });
</script>