<div class="search">
  <div class="page-search">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="list-search">
            <div class="row">
              <div class="col-md-3">
                <select class="form-control selectpicker" data-live-search="true">
                  <option value="">-- Tỉnh/Thành Phố -- </option>
                  <option value="">Hồ Chí Minh</option>
                  <option value="">Lâm Đồng</option>
                  <option>Đồng Nai</option>
                  <option>Bình Dương</option>
                  <option>Bình Phước</option>
                  <option>Hà Nội</option>
                  <option>Hải Dương</option>
                  <option>Bình Định</option>
                  <option>Quản Trị</option>
                  <option>Quảng Nam</option>
                  <option>Huế</option>
                  <option>Đà Nẵng</option>
                  
                </select>
              </div>
              <div class="col-md-3">
                <select class="form-control">
                  <option value="">-- Quận/Huyện -- </option>
                </select>
              </div>
              <div class="col-md-3">
                <select class="form-control">
                  <option value="">-- Phường/Xã -- </option>
                </select>
              </div>
              <div class="col-md-3">
                <select class="form-control">
                  <option value="">-- Loại -- </option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> Danh sách Tỉnh / Thành Phố</h1>
    </div>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="province-container">
        <ul>
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          <li>
            <div class="province-item">
              <div class="province-img">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>">
                </a>
              </div>
              <div class="province-content">
                <h2><a href="#">Thành Phố Hồ Chí Minh</a></h2>
                <div class="list-count-content">
                  <div class="list-count-item">
                    <p class="tours"><span></span> Điểm du lịch</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="hotel"><span></span> Khách sạn</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="taste"><span></span> Điểm ăn uống</p>
                    <p><strong>1500</strong></p>
                  </div>
                  <div class="list-count-item">
                    <p class="park"><span></span> Công viên giải trí</p>
                    <p><strong>1500</strong></p>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content"></div>
</div>