<div class="popup-content">
  <div class="popup-header">
   <h2><span class="icon icon-location"></span> Khách sạn</h2>
   <div class="close-zoom pull-right">
     <div class="zoom"><a href="<?php echo $this->url('hotel-page-detail', array('slug' => 'chi-tiet-hotel', 'id' => '1312312')) ?>"><span class="icon icon-full-screen-selector"></span> Xem rộng hơn</a></div>
     <div class="popup-close"><span class="icon icon-cancel-music"></span></div>
   </div>
  </div>
  <div class="popup-body">
    <div class="slider">
      <div class="row">
        <div class="col-md-8">
          <div class="royalSlider rsDefault">
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />
             <img class="rsImg" src="<?php echo $this->basePath('/assets/demo/hotels.jpg'); ?>" data-rsTmb="<?php echo $this->basePath('/assets/demo/san-francisco.jpg'); ?>" alt="image description" />

           </div>
        </div>
        <div class="col-md-4">
          <div class="description">
             <h2>GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</h2>
             <p class="expt">Tour Campuchia – Lào – Đông Bắc Thái Lan Đi Về Bằng Xe Dành Cho 01 Khách
  – Chuyến Hành Trình 4 Ngày 3 Đêm Cực Kỳ Thú Vị Và Đặc Sắc. Voucher 
  7.890.000 VNĐ, Còn 5.790.000 VNĐ, Giảm 27%.</p>
             <div class="item">
               <p class="cost">Giá gốc: 800,000<span>đ</span></p>
               <p class="price-sale">1,800,000<span>đ</span> <var>-50%</var></p>
             </div>
             <div class="item">
               <div class="quanlity">
                 Số lượng: <input type="number" name="quanlity">
               </div>
               <div class="payment">
                 <a href="#" class="pull-right">Mua ngay</a>
               </div>
             </div>
             <div class="item">
               <p class="count-user-payment"><span class="icon icon-user-profile"></span>102 người đã mua</p>
               <p class="time">19 Ngày 04 : 36 : 09</p>
             </div>
             <div class="item">
               <p>Giao hàng miễn phí tại TP.HCM</p>
             </div>
          </div>
        </div>
      </div>
   </div>

    <div class="commitment">
      <div class="commitment-view">
        <div class="content">
          <div class="col-md-7">
           <h2>ĐIỂM NỔI BẬT</h2>
           <p>- Tour Campuchia – Lào – Đông Bắc Thái Lan trong 4N3Đ do Viet Kite Travel – đơn vị lữ hành giàu kinh nghiệm 
             đứng ra tổ chức.</p><p>
  - Tham gia vào chuyến hành trình, bạn sẽ được đặt chân đến nhiều địa danh khác nhau: Strung Treng 
  (Campuchia), Pakse (Lào), Ubon Ratchathani (Thái Lan).</p><p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
           <p>- Tour Campuchia – Lào – Đông Bắc Thái Lan trong 4N3Đ do Viet Kite Travel – đơn vị lữ hành giàu kinh nghiệm 
             đứng ra tổ chức.</p><p>
  - Tham gia vào chuyến hành trình, bạn sẽ được đặt chân đến nhiều địa danh khác nhau: Strung Treng 
  (Campuchia), Pakse (Lào), Ubon Ratchathani (Thái Lan).</p><p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
         </div>
         <div class="col-md-5">
           <h2>Quy định và lưu ý khi đặt phòng</h2>
           <p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
           <p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
           <p>
  - Ở mỗi vùng đất, bạn lại được mở rộng vốn hiểu biết về lối sống, phong tục tập quán của người dân nơi đó, 
  được chiêm ngưỡng nhiều cảnh đẹp, nhiều công trình mang giá trị văn hóa, lịch sử, bao gồm: Thác Khone 
  Phapheng – thác nước lớn nhất Đông Nam </p>
         </div>
        </div>
      </div>
      <div class="col-md-12 readmove">
        <a href="#"><span class="text">Xem thêm</span> <span class="icon icon-angle-down"></span></a>
      </div>
      <script>
        jQuery(document).ready(function($){
          $(".readmove a").on('click', function(){
            if($(this).hasClass('up')){
               $(".commitment .commitment-view .content").removeClass('expanded');
               $(".readmove a span.text").empty().append('Xem thêm');
               $(this).removeClass('up');
            }else{
               $(".commitment .commitment-view .content").addClass('expanded');
               $(".readmove a span.text").empty().append('Thu gọn');
               $(this).addClass('up');
            }

          });
        });
      </script>
    </div>


    <div class="utilities">
      <h2>TIỆN NGHI KHÁCH SẠN</h2>
      <ul>
        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Tắm hơp</p>
          </div>
        </li>
        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Dịch vụ dọn Phòng</p>
          </div>
        </li>
        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Cafe</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Gym</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Hồ bơi trong nhà</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Giặt ủi</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Dịch vụ phòng họp</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Dịch vụ phòng 24/24</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Nhà hàng</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Spa</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Wifi khu vực công cộng</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Thang máy</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Đưa đón sân bay</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Bàn làm việc</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Nhân viên vận chuyển</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Quán cafe</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Quầy bán Tour</p>
          </div>
        </li>


        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Lễ tân phục vụ 24 giờ</p>
          </div>
        </li>


        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Bãi đậu xe</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Bàn làm việc</p>
          </div>
        </li>

        <li>
          <div class="item">
            <p><span class="icon icon-cutlery"></span></p>
            <p>Buffet sáng</p>
          </div>
        </li>
      </ul>
    </div>

    <div class="list-room">
      <h2>Danh sách phòng</h2>
      <div class="choose-date">
        <div class="item-date">
          <p>Ngày nhận phòng</p>
          <input type="text" name="start_date" class="form-control">
          <div class="calendar"><span class="icon icon-calendar"></div>
        </div>
        <div class="item-date">
          <p>Ngày trả phòng</p>
          <input type="text" name="end_date" class="form-control">
          <div class="calendar"><span class="icon icon-calendar"></div>
        </div>
      </div>
      <div class="room">
        <div class="title">
          <h2><span>Tầng <var>1</var></span></h2>
        </div>
        <div class="list-hotel-room">
          <ul>

            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>


          </ul>
        </div>
      </div>


      <div class="room">
        <div class="title">
          <h2><span>Tầng <var>2</var></span></h2>
        </div>
        <div class="list-hotel-room">
          <ul>

            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>
            
            <li>
              <div class="blank">
                <div class="blank-title"><h3>Phòng P-10045</h3></div>
                <div class="blank-content">
                  <div class="item gift">
                    <img src="<?php echo $this->basePath('/assets/gift.png'); ?>">
                  </div>
                  <div class="item description">
                   <p>Loại phong: 
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                     <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                   </p>
                   <p><strong>Diện tích phòng: </strong> 15m2</p>
                   <p><strong>Ở tối đa: </strong> 2 người lớn, 1 trẻ em</p>
                  </div>
                  <div class="item blank-hot">
                    <h3>Điểm nổi bật:</h3>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                    <p>- Wifi miễn phí</p>
                  </div>
                  <div class="item price">
                    <p class="sale-pup">-40%</p>
                    <p class="cost"><span>500,000đ</span></p>
                    <p class="sale">400,000đ</p>
                  </div>
                  <div class="item views">
                    <a href="javascript:void(0);" class="pull-left views-room view-room-hotel">Xem phòng</a>
                    <a href="javascript:void(0);" class="pull-right book-now">Đặt ngay</a>
                  </div>
                </div>
              </div>
              <p><a href="javascript:void(0);" class="view-room-hotel">
                  <img src="<?php echo $this->basePath('/frontend/images/icon-room.png'); ?>"></a>
                  </p>
              <p>P-1002</p>
            </li>


          </ul>
        </div>
      </div>

    </div>
   <div class="content-page-popup">
     <div class="row">
       <div class="col-md-9 about">
         <div class="tab-title">
           <ul>
             <li class="active"><a href="#">Thông tin chi tiết</a></li>
             <li><a href="javascript:void(0)" id="tab-comment">Bình luận</a></li>
           </ul>
         </div>
         <div class="detail">
           <h2>Giới thiệu</h2>
           <div class="description">
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <p><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
  aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint 
  occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
           </div>
           <div  class="payment-now">
             <a href="#">Mua ngay</a>
           </div>
         </div>

         <div class="position-related">
           <h2>Địa điểm xung quanh</h2>
           <div class="related-map"></div>
         </div>
         <div class="comment" id="detail-comment">
           <h2><span>Bình luận</span> <a class="buttom-comment pull-right">Bình luận</a></h2>
           <ul class="list-comment">
             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li>
               <div class="comment-item">
                 <div class="avartar">
                    <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                 </div>
                 <div class="comment-content">
                   <div class="comment-info">
                     <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     <div class="list-gallery">
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                       <a href="#">
                         <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                       </a>
                     </div>
                     <div class="form-replies">
                       <a class="fs-comment">
                         Trả lời
                       </a>
                       <a class="fs-like">
                         Thích (10)
                       </a>
                       <a class="fs-share">
                         Chia sẻ
                       </a>
                     </div>
                   </div>
                   <div class="comment-replies">
                     <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                     <div class="comment-content">
                       <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

           </ul>
           <div class="views-all">
             <a>Xem thêm</a>
           </div>
         </div>

       </div>
       <div class="col-md-3">
         <div class="post-position">
           <h2>ĐỊA ĐIỂM SỬ DỤNG</h2>
           <h3>Vietkite Travel</h3>
           <p>512 Bùi Đình Túy, Phường 12, Quận Bình Thạnh</p>
           <p>Điện thoại: 0873003799</p>
           <div class="map-position"></div>
         </div>
         <div class="list-related">
           <ul class="row list-item">
             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>
             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>

             <li class="col-md-12">
               <div class="item">
                 <div class="img">
                   <div class="highlight"><span>HOT</span></div>
                   <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                   <div class="item-hover">
                     <div class="item-voucher">
                       Nhân voucher điện tử qua email/SMS
                     </div>
                     <div class="readmove">
                       <a href="#">Xem ngay</a>
                     </div>
                   </div>
                 </div>
                 <div class="item-content">
                   <div class="title">
                     <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                   </div>
                   <div class="price">
                     <p>
                       <span class="cost">350,000 <var>đ</var></span>
                       <span class="sale">-50%</span>
                     </p>
                   </div>
                   <div class="view-user">
                     <span class="price-sale">350,000</span>  <var>đ</var>
                     <div class="pull-right">
                       <span class="icon icon-user-profile"> 1124</span>
                     </div>
                   </div>
                 </div>
               </div>
             </li>


           </ul>
         </div>

       </div>
     </div>
   </div>
  </div>
  </div>

  <div class="poup-footer">
  <div class="row">
   <div class="col-md-4">
     <h2>Công ty TNHH Smart Connector</h2>
     <ul>
       <li>294 Hòa bình, P. Hiệp Tân, Q. Tân Phú, TP.HCM</li>
       <li>ĐT: 08.73055707 - Fax: 08.38666237</li>
       <li><a href="#">sales@abc.vn</a></li>
       <li>Mã số thuế: 0310955176 do Sở Kế hoạch đầu tư TP HCM 
  cấp ngày 29/06/2011</li>
     </ul>
   </div>
   <div class="col-md-2">
     <h2>Về chúng tôi</h2>
     <ul>
       <li><a href="#">Giới thiệu</a></li>
       <li><a href="#">Quy định</a></li>
       <li><a href="#">Trợ giúp</a></li>
       <li><a href="#">Đăng ký quảng cáo</a></li>
       <li><a href="#">Liên hệ</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chăm sóc khách hàng</h2>
     <ul class="support-footer">
       <li><span class="hotline">HOTLINE</span> <span class="hotline-phone">08 7300 5757</span></li>
       <li><a href="#">Chính sách giao hàng</a></li>
       <li><a href="#">Chính sách đổi sản phẩm</a></li>
       <li><a href="#">Chính sách bảo mật</a></li>
     </ul>
   </div>
   <div class="col-md-3">
     <h2>Chứng nhận</h2>
     <ul>
       <li><img src="/tours/public/frontend/images/bocongthuong.png"></li>
     </ul>
     <h2>Liên kết</h2>
     <ul class="connect">
       <li class="facebook"><a href="#"><span class="icon icon-facebook"></span></a></li>
       <li class="twitter"><a href="#"><span class="icon icon-twitter"></span></a></li>
       <li class="youtube"><a href="#"><span class="icon icon-youtube"></span></a></li>
       <li class="googleplus"><a href="#"><span class="icon icon-googleplus"></span></a></li>
       <li class="linkedin"><a href="#"><span class="icon icon-linkedin"></span></a></li>
       <li class="pinterest"><a href="#"><span class="icon icon-pinterest"></span></a></li>
     </ul>
   </div>
  </div>
  </div>

  <div class="coppyright">
  <div class="row">
    <div class="col-md-12">
       <p>Coppyright © 2015 Long.pham. All Rights Reserved</p>
     </div>
  </div>
  </div>