<div class="search">
  <div class="page-search">
    <div class="search-item">
      <div class="search-list">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="list-search">
                <div class="row">
                  <div class="col-md-3">
                    <select class="form-control selectpicker" data-live-search="true">
                      <option value="">-- Quốc gia -- </option>
                      <option value="">Việt Nam</option>
                      <option value="">Thái Lan</option>
                      <option>Ấn Độ</option>
                      <option>Mỹ</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select class="form-control selectpicker">
                      <option value="">-- Tỉnh/Thành Phố -- </option>
                      <option>Bình Phước</option>
                      <option>Hà Nội</option>
                      <option>Hải Dương</option>
                      <option>Bình Định</option>
                      <option>Quản Trị</option>
                      <option>Quảng Nam</option>
                      <option>Huế</option>
                      <option>Đà Nẵng</option>
                    </select>
                  </div>
                  <div class="col-md-3">
                    <div class="item-search-type">
                      <ul class="level">
                        <li class="item">
                          <a>
                            <span>-- Loại --</span>
                          </a>
                          <ul class="search-type">
                            <li class="tours">
                              <input type="checkbox" class="for-type" name="fs-travel" id="fs-travel">
                              <label class="fs-home" data-key="listings-1" for="fs-travel">
                                <span class="root-radius"></span>
                                <span>Điểm du lịch</span>
                              </label>
                            </li>
                            <li class="hotel">
                              <input type="checkbox" class="for-type" name="fs-hotel" id="fs-hotel">
                              <label class="fs-home" data-key="listings-2"  for="fs-hotel">
                                <span class="root-radius"></span>
                                <span>Khách sạn</span>
                              </label>
                            </li>
                            <li class="taste">
                              <input type="checkbox" class="for-type" name="fs-taste" id="fs-taste">
                              <label class="fs-home" data-key="listings-3" for="fs-taste">
                                <span class="root-radius"></span>
                                <span>Điểm ăn uống</span> 
                              </label>
                            </li>
                            <li class="park">
                              <input type="checkbox" class="for-type" name="fs-park" id="fs-park">
                              <label class="fs-home" data-key="listings-4" for="fs-park">
                                <span class="root-radius"></span>
                                <span>Công viên giải trí</span> 
                              </label>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                    <script>
                    jQuery(document).ready(function($){
                      var isClick = false;
                      $(".item-search-type ul>li").on('click', function(e){
                        $(".menu-search li").removeClass('selected');
                        if(isClick != true){
                          $(this).addClass('selected');
                          isClick = true;
                        }else{
                          $(this).removeClass('selected');
                          isClick = false;
                        }
                        e.stopPropagation();
                    });
                    $(document).click(function(e) {
                      isClick = false;
                      if (!$(e.target).is('.item, .item *')) {
                        $(".item-search-type li.item").removeClass('selected');
                      }
                    });
                  });
                    </script>
<!--                    <select class="form-control">
                      <option value="">-- Loại -- </option>
                    </select>-->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-search-title">
    <div class="item-title">
      <h1><span class="icon icon-menu"></span> Khách sạn</h1>
    </div>
  </div>
  
</div>
<div id="container">
  <div class="view">
    <div class="list-container-view">
      <div class="list-cat">
        <div class="filter">
          <ul>
            <li><a href="#">Bán chạy <span class="icon icon-down-thin"></span></a></li>
            <li><a href="#">Mới nhất <span class="icon icon-up-thin"></span></a></li>
            <li><a href="#">Giá <span class="icon icon-up-thin"></span></a></li>
            <li><a href="#">Khuyến mãi <span class="icon icon-up-thin"></span></a></li>
          </ul>
        </div>
        <ul class="row list-item">
          
          <li class="col-md-6">
            <div class="item">
              <div class="img">
                <div class="star">
                  <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                  <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                  <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                  <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                  <img src="<?php echo $this->basePath('/assets/star.png'); ?>">
                </div>
                <div class="highlight"><span>HOT</span></div>
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>" title="sdfsdf"></a>
                <div class="item-hover">
                  <div class="item-voucher">
                    Nhân voucher điện tử qua email/SMS
                  </div>
                  <div class="readmove">
                    <a href="javascript:void(0);" title="Xem ngay">Xem ngay</a>
                  </div>
                </div>
              </div>
              <div class="item-content">
                <div class="title">
                  <a href="javascript:void(0);" title="">Khách sạn Liberty Central Saigon Centre</a>
                </div>
                <div class="price">
                  <p>
                    <span class="cost">350,000 <var>đ</var></span>
                    <span class="sale">-50%</span>
                  </p>
                </div>
                <div class="view-user">
                  <span class="price-sale">350,000</span>  <var>đ</var>
                  <div class="pull-right">
                    <span class="icon icon-user-profile"> 1124</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          
          

        </ul>
      </div>
      <div class="footer-travel">
        <?php $this->footerTravel(); ?>
      </div>
    </div>
    
  </div>
  <div class="map-content">
    <div style="width: 100%; height: 100%;" id="map"></div>
  </div>
</div>
<script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: -33.867, lng: 151.195};

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 15
        });

        infowindow = new google.maps.InfoWindow();
        var service = new google.maps.places.PlacesService(map);
        service.nearbySearch({
          location: pyrmont,
          radius: 500,
          type: ['store']
        }, callback);
      }

      function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
          for (var i = 0; i < results.length; i++) {
            createMarker(results[i]);
          }
        }
      }

      function createMarker(place) {
        var placeLoc = place.geometry.location;
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkgZsd36ZnWXJFh-NcongJgSegi3WA68o&libraries=places&callback=initMap" async defer></script>
    <!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgHX9P3ACD0mO_95u17KzWyQZRiZRP4q0&libraries=places&callback=initMap" async defer></script>-->
     
     <script>
  jQuery(document).ready(function($){
    $(".list-cat .list-item li").on('click','a',function(){
      var id = 'abc';
      var url = 'http://localhost/tours/public/hotel/detail';
      $.ajax({
          url : url,
          type : 'POST',
          dataType : "json",
          data: {id: id},
          beforeSend: function(){
            $(".popup-page").addClass('on');
            $(".popup-page").append('<div class="loading"></div>');
          },
          success : function (data){
            $( ".loading" ).remove();
            $(".popup-container").empty().append(data.html);
            
            // call royalSlider
            var slider = $('.royalSlider').royalSlider({
            fullscreen: {
              enabled: true,
              nativeFS: true
            },
            controlNavigation: 'thumbnails',
            autoScaleSlider: true, 
            autoScaleSliderWidth: 1024,
            autoScaleSliderHeight: 614,
            loop: false,
            imageScaleMode: 'none',
            navigateByClick: true,
            numImagesToPreload:2,
            arrowsNav:true,
            arrowsNavAutoHide: true,
            arrowsNavHideOnTouch: true,
            keyboardNavEnabled: true,
            fadeinLoadedSlide: true,
            globalCaption: true,
            globalCaptionInside: false,
            imageScalePadding: 0,
            slidesSpacing: 0,
            thumbs: {
              appendSpan: true,
              firstMargin: true,
              paddingBottom: 4
            }
            }).data('royalSlider');

            $('.rsFullscreenBtn').click(function(e){
              slider.enterFullscreen();
              e.preventDefault();
            });

            slider.ev.on("rsEnterFullscreen", function() {
              // enter fullscreen mode 
              $(".popup-page").css('position', 'relative');
            });
            slider.ev.on('rsExitFullscreen', function(event) {
              // exit fullscreen mode
              $(".popup-page").removeAttr('style');
            });
            //hotel room hover
            $(".list-hotel-room ul > li").hover(
              function () {
                $(this).addClass('active');
              },
              function () {
                $(this).removeClass('active');
              }
            );
          }
        });
    });
    // close popup
    $(".popup-page").on('click','.popup-close' ,function(){
      $(".popup-page").removeClass('on');
      $(".popup-page .popup-container").empty();
    });
  });
</script>

<div class="popup-page">
  <div class="popup-container tour">
    
  </div>
</div>