<div class="modal fade" id="modal-comment" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <!--<h4 class="modal-title">Bình luận</h4>-->
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation"><a href="#tab-comment" aria-controls="tab-comment" role="tab" data-toggle="tab">Bình luận</a></li>
          <li role="presentation"><a href="#tab-rating" aria-controls="tab-rating" role="tab" data-toggle="tab">Đánh giá</a></li>
          <li role="presentation"><a href="#tab-video" aria-controls="tab-video" role="tab" data-toggle="tab">Upload Video</a></li>
          <li role="presentation" class="active"><a href="#share" aria-controls="share" role="tab" data-toggle="tab">Chia sẻ</a></li>
        </ul>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-7">
            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane" id="tab-comment">
                <div class="row">
                  <div class="col-md-12">
                      <div class="form-group">
                        <input type="text" class="form-control" ty placeholder="Tiêu đề">
                      </div>
                      <div class="form-group">
                        <textarea class="form-control" placeholder="Nội dung"></textarea>
                      </div>
                    <div class="form-group">
                      TẢI ẢNH LÊN
                    </div>
                    <div class="preview">
                      <ul>
                        <li><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></li>
                        <li><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></li>
                        <li><img src="<?php echo $this->basePath('/assets/taste.jpg'); ?>"></li>
                      </ul>
                      <a href="#">
                        <span class="icon icon-plus"></span>
                        <span>Thêm ảnh</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane" id="tab-rating">
                <div class="row">
                  <div class="col-md-12">
                    <div class="write-rating">
                      <div class="row rating-box">
                        <div class="col-md-12">
                          <div class="item-box">
                            <ul class="row">
                              <li class="col-md-12">
                                <div class="row">
                                  <div class="col-md-3">Vị trí</div>
                                  <div class="col-md-8">a</div>
                                  <div class="col-md-1">10</div>
                                </div>
                              </li>
                              <li class="col-md-12">
                                <div class="row">
                                  <div class="col-md-3">Chất lượng</div>
                                  <div class="col-md-8">a</div>
                                  <div class="col-md-1">10</div>
                                </div>
                              </li>
                              <li class="col-md-12">
                                <div class="row">
                                  <div class="col-md-3">Không gian</div>
                                  <div class="col-md-8">a</div>
                                  <div class="col-md-1">10</div>
                                </div>
                              </li>
                              <li class="col-md-12">
                                <div class="row">
                                  <div class="col-md-3">Giá cả</div>
                                  <div class="col-md-8">a</div>
                                  <div class="col-md-1">10</div>
                                </div>
                              </li>
                              <li class="col-md-12">
                                <div class="row">
                                  <div class="col-md-3">Phục vụ</div>
                                  <div class="col-md-8">a</div>
                                  <div class="col-md-1">10</div>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <ul class="row options-box">
                        <li class="col-md-4">
                          <select>
                            <option>Đã đến</option>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10+</option>
                          </select>
                        </li>
                        <li class="col-md-4">
                          <select>
                            <option>Chi phí</option>
                            <option>50,000đ+</option>
                            <option>100,000đ+</option>
                            <option>150,000đ+</option>
                            <option>200,000đ+</option>
                            <option>300,000đ+</option>
                            <option>500,000đ+</option>
                            <option>1,000,000đ+</option>
                            <option>1,500,000đ+</option>
                            <option>3,000,000đ+</option>
                            <option>3,000,000đ+</option>
                            <option>5,000,000đ+</option>
                            <option>7,000,000đ+</option>
                            <option>10,000,000đ+</option>
                          </select>
                        </li>
                        <li class="col-md-4">
                          <select>
                            <option>Quay lại</option>
                            <option>Chắc chắn</option>
                            <option>Có thể</option>
                            <option>Không</option>
                          </select>
                        </li>
                      </ul>
                    </div>

                  </div>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane" id="tab-video">
                <div class="row">
                  <div class="col-md-12">
                    <div class="file-video">
                      <input type="file" id="write-video" class="form-control">
                      <label class="btn-video-upload" for="write-video">
                        <span><var class="icon icon-video-camera"> </var>Tải video</span>
                        <span class="size">(Tối đa 30M)</span>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <div role="tabpanel" class="tab-pane active" id="share">
                <div class="row">
                  <div class="col-md-12">
                    <div class="write-share write-rating">
                      <ul class="row">
                        <li class="col-md-12">
                          <label>Đăng lên tường nhà </label>
                          <div class="switch">
                            <input type="checkbox" checked="checked" class="cmn-toggle-round" id="rev-set-share-wl">
                            <label for="rev-set-share-wl"></label>
                          </div>
                        </li>
                        <li class="col-md-12">
                          <label>Share lên Facebook</label>
                          <div class="switch">
                            <input type="checkbox" checked="checked" class="cmn-toggle-round" id="rev-set-share-fb">
                            <label for="rev-set-share-fb"></label>
                          </div>
                        </li>
                        <li class="col-md-12">
                          <label>Cho phép thảo luận</label>
                          <div class="switch">
                            <input type="checkbox" checked="checked" class="cmn-toggle-round" id="rev-set-share-cm">
                            <label for="rev-set-share-cm"></label>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-5">
            <div class="comment-post-view">
              <img src="<?php echo $this->basePath('/defaults/da-nang.jpg') ?>">
              <p class="title">Meet Fresh - Ngô Đức Kế</p>
              <p class="address">46 Ngô Đức Kế, Quận 1, TP. HCM</p>
              <div class="view-rating">
                <p class="total-comment">295 Bình luận</p>
                <ul>
                  <li>
                      <div class="counts">5</div>
                      <div>Tuyệt vời</div>
                  </li>
                  <li>
                      <div class="counts">167</div>
                      <div>Khá tốt</div>
                  </li>
                  <li>
                      <div class="counts">105</div>
                      <div>Trung bình</div>
                  </li>
                  <li>
                      <div class="counts">18</div>
                      <div>Kém</div>
                  </li>
              </ul>
              </div>
            </div>
            
          </div>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
        <button type="button" class="btn btn-primary">Gửi bình luận</button>
      </div>
    </div>
  </div>
</div>