<div class="warpper-video">
  <div class="close-video"><var class="icon icon-cancel-music"></var></div>
  <div class="container">
    <div class="content-video">
      <div class="row">
        <div class="col-md-8">
          <div class="player-container">
            <div class="image-item">
              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
            </div>
          </div>
          <div class="watch-header">
            <div class="watch7-headline">
              <h1 class="watch-title-container">Liên Khúc Nhạc Ngày Xưa Những Bài Hát Hay Vang Bóng Một Thời</h1>
            </div>
            <div class="watch-user-header">
              <div class="view">
                  1,621,070 views
                </div>
            </div>
            <div class="watch-action-buttons">
              <div class="watch-secondary-actions">
                <ul class="share">
                  <li><a href="#"><span>Chia sẻ lên facebook</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên google+</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên twiter</span></a></li>
                  <li><a href="#"><span>Chia sẻ lên introgram</span></a></li>
                </ul>
              </div>
              <div class="watch-sentiment-actions">

                <span class="like"><var class="icon icon-thumbs-up-hand-symbol"></var> 123,545</span>
                <span class="unlike"><var class="icon icon-thumbs-up-hand-symbol"></var> 158</span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <a href="#"><img src="<?php echo $this->basePath('/assets/banner-video.jpg'); ?>"></a>
        </div>
      </div>
    </div>

  </div>
</div>