<div class="warpper-video">
  <div class="close-video"><var class="icon icon-cancel-music"></var></div>
  <div class="container">
    <div class="content-video">
      <div class="row">
        <div class="col-md-8">
          <div class="player-container">
            <div class="image-item">
              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>" width="753">
            </div>
          </div>
          
        </div>
        <div class="col-md-4">
          <a href="#"><img style="height: 492px; width: 368px;" src="<?php echo $this->basePath('/assets/banner-video.jpg'); ?>"></a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="list-image">
            <ul class="row">
              <li class="col-md-2">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                </a>
              </li>
              <li class="col-md-2">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                </a>
              </li>
              <li class="col-md-2">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                </a>
              </li>
              <li class="col-md-2">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                </a>
              </li>
              <li class="col-md-2">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                </a>
              </li>
              <li class="col-md-2">
                <a href="#">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                </a>
              </li>
            </ul>>
          </div>
          
        </div>
      </div>
    </div>

  </div>
</div>