<div class="warpper-video">
  <div class="close-video"><var class="icon icon-cancel-music"></var></div>
  <div class="container">
    <div class="content-video">
      <div class="row">
        <div class="col-md-8">
          <div class="player-container">
            <div class="image-item">
              <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>" width="753">
            </div>
          </div>
          
        </div>
        <div class="col-md-4">
          <div class="comment-image">
            <div class="user-info">
              <div class="avatar">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </div>
              <div class="comment-content">
                <p>
                  <a href="#">
                    Thu Huong Nguyen
                  </a>
                </p>
                <p><var>08/07/2017 11:49:52</var></p>
              </div>
              
            </div>
            
            <div class="view-replies">
              <div class="fs-comment icon icon-comment">
                Bình luận
              </div>
              <div class="fs-like icon icon-heart-1">
                Thích (110,010,001)
              </div>
              <div class="fs-share">
                Chia sẻ
                <div class="share-page">
                  <ul>
                    <li>
                      <span>Điểm đia chơi</span>
                    </li>
                    <li>
                      <span>Chia sẻ lên Facebook</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-replies">
              <div class="list-comment-replies">
                <div class="comment-replies">
                  <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                  <div class="comment-content">
                    <p><strong><a href="#">
                      Pham Long </a></strong>
                      a afd adf      </p>
                          <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>18/07/2017 17:35:31</var></p>
                    </div>
                </div>
                
                <div class="comment-replies">
                  <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                  <div class="comment-content">
                    <p><strong><a href="#">
                      Pham Long </a></strong>
                      a afd adf      </p>
                          <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>18/07/2017 17:35:31</var></p>
                    </div>
                </div>
                
                <div class="comment-replies">
                  <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                  <div class="comment-content">
                    <p><strong><a href="#">
                      Pham Long </a></strong>
                      a afd adf      </p>
                          <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>18/07/2017 17:35:31</var></p>
                    </div>
                </div>
                
                <div class="comment-replies">
                  <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                  <div class="comment-content">
                    <p><strong><a href="#">
                      Pham Long </a></strong>
                      a afd adf      </p>
                          <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>18/07/2017 17:35:31</var></p>
                    </div>
                </div>
                
                <div class="comment-replies">
                  <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                  <div class="comment-content">
                    <p><strong><a href="#">
                      Pham Long </a></strong>
                      a afd adf      </p>
                          <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>18/07/2017 17:35:31</var></p>
                    </div>
                </div>
                
              </div>

              <div class="comment-form-replies">
                <div class="icon">
                  <div class="avartar">
                    <img src="/assets/demo/photo.jpg">
                 </div>
                </div>
                <div class="replies">
                  <textarea name="content" placeholder="Viết bình luận" data-post="1" class="form-control" id="data_comment_1"></textarea>
                  <input type="hidden" class="mid_1" value="c4ca4238a0b923820dcc509a6f75849b">
                </div>
              </div>
          </div>
            
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="list-image">
            <div class="swiper-container">
              <div class="swiper-wrapper">
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="swiper-slide">
                  <div class="image-related">
                    <a href="#">
                      <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                    </a>
                    <div class="user">
                      <a href="#">
                        <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
                        <span>Pham Van Long</span>
                      </a>
                    </div>
                  </div>
                </div>
                
              </div>
              <div class="prev"><span class="icon icon-left-chevron"></span></div>
              <div class="next"><span class="icon icon-right-chevron"></span></div>
            </div>
          </div>
          
        </div>
      </div>
    </div>

  </div>
</div>