<?php if($dataComment && $currentPage <= $totalPage): ?>
    <?php foreach ($dataComment as $value): ?>
    <li id="comment_<?php echo $value['id']; ?>">
      <div class="comment-item">
        <div class="avartar">
          <?php echo $currentPage; ?> - <?php echo $totalPage; ?>
           <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
        </div>
        <div class="comment-content">
          <div class="comment-info">
            <div class="user-comment-info">
              <p><a href="#"><b><?php echo $value['fullname']; ?></b></a></p>
              <?php if($value['device']): ?>
              <p><span class="icon icon-001-cell-phone"></span> Via <?php echo $value['device']; ?> <var><?php echo date('d/m/Y H:i:s', $value['created']); ?></var></p>
              <?php endif; ?>
            </div>
            <p><a href="#"><strong><?php echo $value['title']; ?> - <?php echo $value['id'] ?></strong></a></p>
            <p><?php echo $value['content']; ?></p>
            <div class="review-options">
              <ul>
                <?php if($value['persion']): ?>
                <li><span>Số người: <?php echo $value['persion'] ?></span></li>
                <?php endif; ?>
                <?php if($value['total_bill']): ?>
                <li><span>Chi phí: <?php echo number_format($value['total_bill'], 0, '.', '.'); ?>đ</span></li>
                <?php endif; ?>
                <?php if($value['come_back']): ?>
                <li><span>Muốn quay lại: 
                  <?php if($value['come_back'] == 1): ?>Chắc chắn
                  <?php endif; ?>
                  <?php if($value['come_back'] == 2): ?>Có thể
                  <?php endif; ?>
                  <?php if($value['come_back'] == 3): ?>Không
                  <?php endif; ?>
                  </span></li>
                <?php endif; ?>
              </ul>
            </div>
            <?php if($value['listImageComment']): ?>
            <div class="list-gallery">
              <?php foreach ($value['listImageComment'] as $img): ?>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <?php endforeach; ?>
            </div>
            <?php endif; ?>
          </div>
          <div class="form-replies">
            <div class="view-replies">
              <div class="fs-comment icon icon-comment">
                Bình luận
              </div>
              <div class="fs-like icon icon-heart-1">
                Thích (<?php echo number_format($value['total_like'], 0, ',', ','); ?>)
              </div>
              <div class="fs-share">
                Chia sẻ
                <div class="share-page">
                  <ul>
                    <li>
                      <span>Điểm đia chơi</span>
                    </li>
                    <li>
                      <span>Chia sẻ lên Facebook</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            
            <div class="list-comment-replies">
            <?php if($value['commentChild']): ?>
              <?php foreach ($value['commentChild'] as $child): ?>
              <div class="comment-replies">
                <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                <div class="comment-content">
                  <p><strong><a href="#">
                    <?php echo $value['fullname']; ?> </a></strong>
                    <?php echo $value['content']; ?>
                  </p>
                  <?php if($value['device']): ?>
              <p><span class="icon icon-001-cell-phone"></span> Via <?php echo $value['device']; ?> <var><?php echo date('d/m/Y H:i:s', $value['created']); ?></var></p>
              <?php endif; ?>
                </div>
              </div>
              <?php endforeach; ?>
            <?php endif; ?>
            </div>
            <?php if($value['countChildComment'] > LIMIT_COMMENT): ?>
            <div class="child-comment-readmore">
              <div ng-page="<?php echo $value['currentChildPage']; ?>" ng-data="<?php echo $postId; ?>" data-parent="<?php echo $value['id']; ?>" class="viewmore-child-comment">
                Xem thêm bình luận
              </div>
            </div>
            <?php endif; ?>
            
            <div class="comment-form-replies">
              <div class="icon">
                <div class="avartar">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
               </div>
              </div>
              <div class="replies">
                <div class="replies">
                  <textarea name="content" data-post="<?php echo $postId; ?>" class="form-control" placeholder="Viết bình luận" id="data_comment_<?php echo $value['id']; ?>"></textarea>
                  <input type="hidden" class="mid_<?php echo $value['id']; ?>" value="<?php echo md5($value['id']); ?>">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
    <?php endforeach; ?>
  <?php endif; ?>