<?php if($dataCommentChild): ?>
  <?php foreach ($dataCommentChild as $child): ?>
  <div class="comment-replies">
    <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
    <div class="comment-content">
      <p><strong><a href="#">
        <?php echo $child['username']; ?> </a></strong>
        <?php echo $child['content']; ?>
      </p>
      <?php if($child['device']): ?>
  <p><span class="icon icon-001-cell-phone"></span> Via <?php echo $child['device']; ?> <var><?php echo date('d/m/Y H:i:s', $child['created']); ?></var></p>
  <?php endif; ?>
    </div>
  </div>
  <?php endforeach; ?>
  <?php endif; ?>