<div id="rating" class="rating">
  <h2>Khách hàng nhận xét</h2>
  <ul>
    <li class="summary-rating">
      <p>Đánh Giá Trung Bình</p>
      <p>3.5/5</p>
      <p class="rating-post">
        <span class="rating-box">
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <span>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
          </span>
        </span>
      </p>
      <p>(10 nhận xét)</p>
    </li>
    <li class="rating__row">
      <div class="row-box">
        <div class="rrow__label">Tốt</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 70%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Rất tốt</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 70%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Trung bình</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 70%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Không tốt</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 90%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Rất tệ</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 30%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>
    </li>
  </ul>
</div>
<div class="comment">
  <h2><span>Bình luận</span> <a class="buttom-comment pull-right" data-toggle="modal" data-target="#modal-comment">Bình luận</a></h2>
  <ul class="list-comment">
    <li>
      <div class="comment-item">
        <div class="avartar">
           <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
        </div>
        <div class="comment-content">
          <div class="comment-info">
            <div class="user-comment-info">
              <p><a href="#"><b>Pham Van Long</b></a></p>
              <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
            </div>
            <p><a href="#"><strong>Facebook for Developers</strong></a></p>
            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
            <div class="review-options">
              <ul>
                <li><span>Số người: 4</span></li>
                <li><span>Chi phí: 1,000,000đ</span></li>
                <li><span>Muốn quay lại: Chắc chắn</span></li>
              </ul>
            </div>
            <div class="list-gallery">
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
            </div>
          </div>
          <div class="form-replies">
            <div class="view-replies">
              <div class="fs-comment icon icon-comment">
                Trả lời
              </div>
              <div class="fs-like icon icon-heart-1">
                Thích (10)
              </div>
              <div class="fs-share">
                Chia sẻ
                <div class="share-page">
                  <ul>
                    <li>
                      <span>Điểm đia chơi</span>
                    </li>
                    <li>
                      <span>Chia sẻ lên Facebook</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="comment-replies">
              <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
              <div class="comment-content">
                <p><strong><a href="#">Phạm Long </a></strong>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
              </div>
            </div>

            <div class="comment-form-replies">
              <div class="icon">
                <div class="avartar">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
               </div>
              </div>
              <div class="replies">
                <textarea class="form-control"></textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>

    <li>
      <div class="comment-item">
        <div class="avartar">
           <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
        </div>
        <div class="comment-content">
          <div class="comment-info">
            <div class="user-comment-info">
              <p><a href="#"><b>Pham Van Long</b></a></p>
              <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
            </div>
            <p><a href="#"><strong>Facebook for Developers</strong></a></p>
            <p>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
            <div class="list-gallery">
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
            </div>
          </div>
          <div class="form-replies">
            <div class="view-replies">
              <div class="fs-comment icon icon-comment">
                Trả lời
              </div>
              <div class="fs-like icon icon-heart-1">
                Thích (10)
              </div>
              <div class="fs-share">
                Chia sẻ
                <div class="share-page">
                  <ul>
                    <li>
                      <span>Điểm đia chơi</span>
                    </li>
                    <li>
                      <span>Chia sẻ lên Facebook</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="comment-replies">
              <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
              <div class="comment-content">
                <p><strong><a href="#">Phạm Long </a></strong>Hotdeal chào bạn! Hotdeal đã tiến hành kiểm tra thông tin, đơn hàng của bạn trong tình trạng đang giao hàng bạn nhé. Bạn sẽ nhận được voucher trong thời gian sớm nhất. Bạn vui lòng nghe điện thoại khi nhân viên giao hàng Hotdeal liên hệ nha. Cảm ơn bạn đã sử dụng dịch vụ của Hotdeal.</p>
                <p><span class="icon icon-001-cell-phone"></span> Via Iphone <var>20/3/2017 21:32</var></p>
              </div>
            </div>

            <div class="comment-form-replies">
              <div class="icon">
                <div class="avartar">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
               </div>
              </div>
              <div class="replies">
                <textarea class="form-control"></textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>






  </ul>
  <div class="views-all">
    <a>Xem thêm</a>
  </div>
  </div>