<div id="rating" class="rating">
  <h2>Khách hàng nhận xét</h2>
  <ul>
    <li class="summary-rating">
      <p>Đánh Giá Trung Bình</p>
      <p>3.5/5</p>
      <p class="rating-post">
        <span class="rating-box">
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <i class="icon icon-star"></i>
          <span>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
            <i class="icon icon-star"></i>
          </span>
        </span>
      </p>
      <p>(10 nhận xét)</p>
    </li>
    <li class="rating__row">
      <div class="row-box">
        <div class="rrow__label">Tốt</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 70%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Rất tốt</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 70%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Trung bình</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 70%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Không tốt</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 90%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>

      <div class="row-box">
        <div class="rrow__label">Rất tệ</div>
        <div class="rrow__percent">
          <div class="progress-bar">
            <div class="progress-bar__inner" style="width: 30%;"></div>
          </div>
        </div>
        <div class="rrow__counting">14</div>
        <div class="rrow__descr">đánh giá</div>
      </div>
    </li>
  </ul>
</div>
<div class="comment">
  <h2><span>Bình luận</span> <a class="buttom-comment pull-right" data-toggle="modal" data-target="#modal-comment">Bình luận</a></h2>
  <?php if($dataComment): ?>
  <ul class="list-comment">
    <?php foreach ($dataComment as $value): ?>
    <li>
      <div class="comment-item">
        <div class="avartar">
           <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
        </div>
        <div class="comment-content">
          <div class="comment-info">
            <div class="user-comment-info">
              <p><a href="#"><b><?php echo $value['fullname']; ?></b></a></p>
              <?php if($value['device']): ?>
              <p><span class="icon icon-001-cell-phone"></span> Via <?php echo $value['device']; ?> <var><?php echo date('d/m/Y H:i:s', $value['created']); ?></var></p>
              <?php endif; ?>
            </div>
            <p><a href="#"><strong><?php echo $value['title']; ?></strong></a></p>
            <p><?php echo $value['content']; ?></p>
            <div class="review-options">
              <ul>
                <?php if($value['persion']): ?>
                <li><span>Số người: <?php echo $value['persion'] ?></span></li>
                <?php endif; ?>
                <?php if($value['total_bill']): ?>
                <li><span>Chi phí: <?php echo number_format($value['total_bill'], 0, '.', '.'); ?>đ</span></li>
                <?php endif; ?>
                <?php if($value['come_back']): ?>
                <li><span>Muốn quay lại: 
                  <?php if($value['come_back'] == 1): ?>Chắc chắn
                  <?php endif; ?>
                  <?php if($value['come_back'] == 2): ?>Có thể
                  <?php endif; ?>
                  <?php if($value['come_back'] == 3): ?>Không
                  <?php endif; ?>
                  </span></li>
                <?php endif; ?>
              </ul>
            </div>
            <?php if($value['listImageComment']): ?>
            <div class="list-gallery">
              <?php foreach ($value['listImageComment'] as $img): ?>
              <a href="#">
                <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
              </a>
              <?php endforeach; ?>
            </div>
            <?php endif; ?>
          </div>
          <div class="form-replies">
            <div class="view-replies">
              <div class="fs-comment icon icon-comment">
                Trả lời
              </div>
              <div class="fs-like icon icon-heart-1">
                Thích (<?php echo number_format($value['total_like'], 0, ',', ','); ?>)
              </div>
              <div class="fs-share">
                Chia sẻ
                <div class="share-page">
                  <ul>
                    <li>
                      <span>Điểm đia chơi</span>
                    </li>
                    <li>
                      <span>Chia sẻ lên Facebook</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <?php if($value['commentChild']): ?>
            <div class="list-comment-replies">
              <?php foreach ($value['commentChild'] as $child): ?>
              <div class="comment-replies">
                <div class="avartar"><img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>"></div>
                <div class="comment-content">
                  <p><strong><a href="#">
                    <?php echo $value['fullname']; ?> </a></strong>
                    <?php echo $value['content']; ?>
                  </p>
                  <?php if($value['device']): ?>
              <p><span class="icon icon-001-cell-phone"></span> Via <?php echo $value['device']; ?> <var><?php echo date('d/m/Y H:i:s', $value['created']); ?></var></p>
              <?php endif; ?>
                </div>
              </div>
              <?php endforeach; ?>
            </div>
            <?php endif; ?>

            <div class="comment-form-replies">
              <div class="icon">
                <div class="avartar">
                  <img src="<?php echo $this->basePath('/assets/demo/photo.jpg'); ?>">
               </div>
              </div>
              <div class="replies">
                <textarea class="form-control"></textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
    <?php endforeach; ?>
    
  </ul>
  <?php endif; ?>
  <div class="views-all">
    <a>Xem thêm</a>
  </div>
  </div>