<?php
if($this->pageCount > 1){ ?>
    <?php 
    $urlParams = array(
        "category" => $category,
        "province" => $province,
        "nation" => $nation,
        "district" => $district,
        "page" => $page,
        'filter' => $filter,
        'star' => $star,
        'sort' => $sort,
        'min' => $min,
        'max' => $max,
        'area' => $area,
        'keyword' => $keyword
//        "order" => $this->order,
//        "category" => $this->category,
//        'slug' => $this->slug,
//        'detail' => $this->detail,
    );
    if($urlParams['province'] && $urlParams['district']){
      $url = $this->url('category', array('category' => $category, 'province' => $urlParams['province'], 'district' => $urlParams['district']));;
    }
    if($urlParams['province'] && $urlParams['district'] == ''){
      $url = $this->url('category', array('category' => $category, 'province' => $urlParams['province']));;
    }
    if($urlParams['province'] == '' && $urlParams['district'] == ''){
      $url = $this->url('category', array('category' => $category));
    }
    
    $arrString = array();
    if($urlParams['nation']){
      $arrString['nation'] = $urlParams['nation'];
    }
    if($urlParams['filter']){
      $arrString['filter'] = $urlParams['filter'];
    }
    if($urlParams['sort']){
      $arrString['sort'] = $urlParams['sort'];
    }
    if($urlParams['star']){
      $arrString['star'] = $urlParams['star'];
    }
    if($urlParams['min']){
      $arrString['min'] = $urlParams['min'];
    }
    if($urlParams['max']){
      $arrString['max'] = $urlParams['max'];
    }
    if($urlParams['area']){
      $arrString['area'] = $urlParams['area'];
    }
    if($urlParams['keyword']){
      $arrString['keyword'] = $urlParams['keyword'];
    }
    $paramString = '';
    if($arrString){
      $totalParam = count($arrString);
      $i = 1;
      foreach ($arrString as $key => $value){
        
        if($i === $totalParam){
          $paramString .= $key .'='.$value;
        }else{
          $paramString .= $key .'='.$value.'&';
        }
        $i++;
      }
    }
    ?>
    <ul class="pagination">
        <?php if(!isset($this->previous)){
            $this->previous = $this->first;
        } ?>
        <?php if ($this->current != 1) { 
          $urlParams['page'] = $this->first;
          ?>
                <li><a data-page="<?php echo $urlParams['page']; ?>" href="<?php echo $url ; ?>?page=<?php echo $this->first ?>&<?php echo $paramString; ?>">Trang đầu</a></li>
        <?php } ?>
                
        <?php $urlParams["page"] = $this->previous; ?>
        <?php if($this->current != $this->previous){ ?>
        <li><a data-page="<?php echo $urlParams['page']; ?>" href="<?php echo $url ; ?>?page=<?php echo $this->previous ?>&<?php echo $paramString; ?>">
                Lùi lại
            </a>
        </li>
        <?php } ?>
        <?php foreach($this->pagesInRange as $key => $page){ ?>
            <?php $urlParams["page"] = $page; ?>
        <?php if($this->current == $key): ?>
        <li class="active">
            <span>
                <?php echo $page; ?>
            </span>
        </li>
        <?php else: ?>
        <li>
            <a data-page="<?php echo $page; ?>" href="<?php echo $url ; ?>?page=<?php echo $page ?>&<?php echo $paramString; ?>">
                <?php echo $page; ?>
            </a>
        </li>
        <?php endif; ?>
        <?php } ?>
        <?php if(!isset($this->next)){
            $this->next = $this->last;
        } ?>
        <?php if ($urlParams["page"] != $this->next) {
          $urlParams["page"] = $this->next;
          ?>
        <li>
            <a data-page="<?php echo $urlParams['page']; ?>" href="<?php echo $url ; ?>?page=<?php echo $this->next ?>&<?php echo $paramString; ?>">
                Trang kế
            </a>
        </li>
        <?php } ?>
        <?php if ($this->current != $this->last) { 
          $urlParams["page"] = $this->last;
          ?>
        <li><a data-page="<?php echo $urlParams['page']; ?>" href="<?php echo $url ; ?>?page=<?php echo $this->last ?>&<?php echo $paramString; ?>" title="Trang Cuối">Trang cuối</a></li>
        <?php } ?> 
    </ul>
<?php } ?>  