<div class="tour-home-content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="tab-home"><a href="#"><span class="icon icon-suitcasesocial"></span> Du lịch</a></li>
          <li role="presentation" class="active"><a href="#tour-news" aria-controls="tour-news" role="tab" data-toggle="tab">Mới nhất</a></li>
          <li role="presentation"><a href="#tour-price" aria-controls="tour-price" role="tab" data-toggle="tab">Mua nhiều</a></li>
          <li role="presentation"><a href="#tour-hot" aria-controls="tour-hot" role="tab" data-toggle="tab">Giá tốt</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="tour-news">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-price">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-hot">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/deal.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row view-user-all">
      <div class="col-md-12">
        <a href="#">Xem tất cả</a>
      </div>
    </div>
  </div>
</div>



<div class="tour-home-content taste">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="tab-home"><a href="#"><span class="icon icon-suitcasesocial"></span> Điểm ăn uống</a></li>
          <li role="presentation" class="active"><a href="#tour-news" aria-controls="tour-news" role="tab" data-toggle="tab">Mới nhất</a></li>
          <li role="presentation"><a href="#tour-price" aria-controls="tour-price" role="tab" data-toggle="tab">Mua nhiều</a></li>
          <li role="presentation"><a href="#tour-hot" aria-controls="tour-hot" role="tab" data-toggle="tab">Giá tốt</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="tour-news">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-price">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-hot">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/taste.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row view-user-all">
      <div class="col-md-12">
        <a href="#">Xem tất cả</a>
      </div>
    </div>
  </div>
</div>


<div class="tour-home-content hotel">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="tab-home"><a href="#"><span class="icon icon-suitcasesocial"></span> Khách sạn</a></li>
          <li role="presentation" class="active"><a href="#tour-news" aria-controls="tour-news" role="tab" data-toggle="tab">Mới nhất</a></li>
          <li role="presentation"><a href="#tour-price" aria-controls="tour-price" role="tab" data-toggle="tab">Mua nhiều</a></li>
          <li role="presentation"><a href="#tour-hot" aria-controls="tour-hot" role="tab" data-toggle="tab">Giá tốt</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="tour-news">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-price">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              
            </ul>
          </div>
          <div role="tabpanel" class="tab-pane" id="tour-hot">
            <ul class="row list-item">
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
              <li class="col-md-3">
                <div class="item">
                  <div class="img">
                    <div class="highlight"><span>HOT</span></div>
                    <a href="#"><img src="<?php echo $this->basePath('/assets/demo/hotel.jpg'); ?>"></a>
                    <div class="item-hover">
                      <div class="item-voucher">
                        Nhân voucher điện tử qua email/SMS
                      </div>
                      <div class="readmove">
                        <a href="#">Xem ngay</a>
                      </div>
                    </div>
                  </div>
                  <div class="item-content">
                    <div class="title">
                      <a href="#">Tour Hà Nội - Bái Đính - KDL Tràng An Cổ - 01 Ngày - Dành Cho 01 Khách</a>
                    </div>
                    <div class="price">
                      <p>
                        <span class="cost">350,000 <var>đ</var></span>
                        <span class="sale">-50%</span>
                      </p>
                    </div>
                    <div class="view-user">
                      <span class="price-sale">350,000</span>  <var>đ</var>
                      <div class="pull-right">
                        <span class="icon icon-user-profile"> 1124</span>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row view-user-all">
      <div class="col-md-12">
        <a href="#">Xem tất cả</a>
      </div>
    </div>
  </div>
</div>