<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuTaste(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Tạo điểm ăn uống</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Tạo điểm ăn uống</h2>
                  <div class="page">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Tiêu đề</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Mô tả ngắn</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Địa chỉ</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giờ mở cửa</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giờ đóng cửa</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giá trung bình</label>
                          <input type="text" class="form-control" placeholder="10.000đ - 35.000đ" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Điện thoại hotline</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Video</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ngày bắt đầu</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ngày kết thúc</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ảnh đại điện</label>
                          <input type="file">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1"> Gallery </label>
                          <input type="file">
                        </div>
                        
                        
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Giới thiệu</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Điểm nổi bật</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Nội dung</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Lưu và tạo thực đơn</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>