<div class="user">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="sidebar-left">
              <?php $this->menuBlog(); ?>
            </div>
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Đăng blog</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Đăng blog</h2>
                  <div class="page">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Tiêu đề</label>
                          <input type="text" class="form-control" id="exampleInputEmail1">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Mô tả ngắn</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        <div class="form-group">
                          <label for="exampleInputEmail1">Ảnh đại điện</label>
                          <input type="file">
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Mô tả SEO</label>
                          <textarea class="form-control"></textarea>
                        </div>
                        
                        <div class="form-group">
                          <label for="exampleInputEmail1">Từ khóa SEO</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      <div class="col-md-12">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Nội dung</label>
                          <textarea class="form-control"></textarea>
                        </div>
                      </div>
                      
                      
                      
                      <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Đăng</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>