<div class="album">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="title"><a href="#"><span class="icon icon-camera"></span> Album</a></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="swiper-container">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a>
              <p class="position-name"><a href="#">Thành phố Đà Lạt</a></p>
            </div>
            <div class="swiper-slide">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a>
              <p class="position-name"><a href="#">Thành phố Đà Lạt</a></p>
            </div>
            <div class="swiper-slide">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a>
              <p class="position-name"><a href="#">Thành phố Đà Lạt</a></p>
            </div>
            <div class="swiper-slide">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a>
              <p class="position-name"><a href="#">Thành phố Đà Lạt</a></p>
            </div>
            <div class="swiper-slide">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a>
              <p class="position-name"><a href="#">Thành phố Đà Lạt</a></p>
            </div>
            <div class="swiper-slide">
              <a class="like" title="Thích">321 <span class="icon icon-heart"></span></a>
              <a href="#"><img src="<?php echo $this->basePath('/assets/demo/album.jpg'); ?>"></a>
              <p class="position-name"><a href="#">Thành phố Đà Lạt</a></p>
            </div>
          </div>
            
        </div>
        <!-- Add Pagination -->
        <div class="swiper-btn button-prev"><span class="icon icon-left-chevron"></span></div>
        <div class="swiper-btn button-next"><span class="icon icon-right-chevron"></span></div>
      </div>
    </div>
  </div>
</div>
<script>
    var swiper = new Swiper('.swiper-container', {
        nextButton: '.button-next',
        prevButton: '.button-prev',
        paginationClickable: true,
        slidesPerView: 4,
        spaceBetween: 15,
        breakpoints: {
            1024: {
                slidesPerView: 4,
                spaceBetween: 40
            },
            768: {
                slidesPerView: 3,
                spaceBetween: 30
            },
            640: {
                slidesPerView: 2,
                spaceBetween: 20
            },
            320: {
                slidesPerView: 1,
                spaceBetween: 10
            }
        }
    });
</script>