<div class="user album">
  <div class="post">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="post-container">
            <div class="content">
              <div class="user-breadcrumb">
                <ol class="breadcrumb">
                  <li>Trang chủ</li>
                  <li class="active">Hộp Mail</li>
                </ol>
              </div>
              <div class="body-container">
                <div class="body-content">
                  <h2 class="title">Hộp thư</h2>
                  <table class="list-table">
                    <tbody>
                      <tr class="active">
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      <tr class="active">
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      <tr class="active">
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                      <tr>
                        <td><input type="checkbox"></td>
                        <td>Phạm Văn Long</td>
                        <td><a href="#" target="_blank">GOLD HOTEL ĐÀ NẴNG 3 sao, gần Cầu Rồng + Buffet Sáng</a></td>
                        <td>20-08-2016:15:30:15</td>
                      </tr>
                      
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>